package spec

import (
	"fmt"
	"strings"
)

type amendmentEntry struct {
	Name    string
	Prompt  string
	Origin  string
	Finding *findingEntry
}

type findingEntry struct {
	Severity string
	File     string
	Line     int
	Text     string
}

// cuePath returns the CUE selector for a resource given its kind/context/name,
// matching the spec layout. Context-scoped kinds nest under contexts: <Ctx>;
// project-level kinds (asset, adapter) sit directly under project.
func cuePath(kind, contextName, name string) string {
	bucket := map[string]string{
		"valueObject":        "valueObjects",
		"aggregate":          "aggregates",
		"entity":             "entities",
		"asset":              "assets",
		"adapter":            "adapters",
		"repository":         "repositories",
		"domainService":      "domainServices",
		"applicationService": "applicationServices",
	}[kind]
	if bucket == "" {
		bucket = kind + "s"
	}
	if contextName != "" && kind != "asset" && kind != "adapter" {
		return fmt.Sprintf("project: contexts: %s: %s: %s", contextName, bucket, name)
	}
	return fmt.Sprintf("project: %s: %s", bucket, name)
}

// renderAmendmentOverride produces a CUE override body that attaches the given
// amendments to a resource UNDER ITS meta (amendments live on Meta). The caller
// passes the full desired amendments list (existing + new) so the file is
// self-contained and human-reviewable.
func renderAmendmentOverride(pkg, name, kind, contextName string, entries []amendmentEntry) string {
	var b strings.Builder
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	b.WriteString("// Amendment override (human-approved). Generated by spec/apply_amendments.\n")
	b.WriteString("// Each entry is a targeted, spec-resident correction; adding it re-renders\n")
	b.WriteString("// this resource in UPDATE mode. Edit or remove entries to change behavior.\n\n")
	fmt.Fprintf(&b, "%s: meta: amendments: [\n", cuePath(kind, contextName, name))
	for _, e := range entries {
		b.WriteString("\t{\n")
		fmt.Fprintf(&b, "\t\tname:   %q\n", e.Name)
		fmt.Fprintf(&b, "\t\tprompt: %q\n", e.Prompt)
		if e.Origin != "" {
			fmt.Fprintf(&b, "\t\torigin: %q\n", e.Origin)
		}
		if e.Finding != nil {
			b.WriteString("\t\tfinding: {\n")
			if e.Finding.Severity != "" {
				fmt.Fprintf(&b, "\t\t\tseverity: %q\n", e.Finding.Severity)
			}
			if e.Finding.File != "" {
				fmt.Fprintf(&b, "\t\t\tfile: %q\n", e.Finding.File)
			}
			if e.Finding.Line != 0 {
				fmt.Fprintf(&b, "\t\t\tline: %d\n", e.Finding.Line)
			}
			if e.Finding.Text != "" {
				fmt.Fprintf(&b, "\t\t\ttext: %q\n", e.Finding.Text)
			}
			b.WriteString("\t\t}\n")
		}
		b.WriteString("\t},\n")
	}
	b.WriteString("]\n")
	return b.String()
}
