package spec

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	cuepkg "github.com/crestenstclair/crest-spec/internal/cue"
)

type amendmentEntry struct {
	Name    string
	Prompt  string
	Origin  string
	Finding *findingEntry
}

type findingEntry struct {
	Severity string
	File     string
	Line     int
	Text     string
}

// cuePath returns the CUE selector for a resource given its kind/context/name,
// matching the spec layout. Context-scoped kinds nest under contexts: <Ctx>;
// project-level kinds (asset, adapter) sit directly under project.
func cuePath(kind, contextName, name string) string {
	bucket := map[string]string{
		"valueObject":        "valueObjects",
		"aggregate":          "aggregates",
		"entity":             "entities",
		"asset":              "assets",
		"adapter":            "adapters",
		"repository":         "repositories",
		"domainService":      "domainServices",
		"applicationService": "applicationServices",
	}[kind]
	if bucket == "" {
		bucket = kind + "s"
	}
	if contextName != "" && kind != "asset" && kind != "adapter" {
		return fmt.Sprintf("project: contexts: %s: %s: %s", contextName, bucket, name)
	}
	return fmt.Sprintf("project: %s: %s", bucket, name)
}

// renderAmendmentOverride produces a CUE override body that attaches the given
// amendments to a resource UNDER ITS meta (amendments live on Meta). The caller
// passes the full desired amendments list (existing + new) so the file is
// self-contained and human-reviewable.
func renderAmendmentOverride(pkg, name, kind, contextName string, entries []amendmentEntry) string {
	var b strings.Builder
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	b.WriteString("// Amendment override (human-approved). Generated by spec/apply_amendments.\n")
	b.WriteString("// Each entry is a targeted, spec-resident correction; adding it re-renders\n")
	b.WriteString("// this resource in UPDATE mode. Edit or remove entries to change behavior.\n\n")
	fmt.Fprintf(&b, "%s: meta: amendments: [\n", cuePath(kind, contextName, name))
	for _, e := range entries {
		b.WriteString("\t{\n")
		fmt.Fprintf(&b, "\t\tname:   %q\n", e.Name)
		fmt.Fprintf(&b, "\t\tprompt: %q\n", e.Prompt)
		if e.Origin != "" {
			fmt.Fprintf(&b, "\t\torigin: %q\n", e.Origin)
		}
		if e.Finding != nil {
			b.WriteString("\t\tfinding: {\n")
			if e.Finding.Severity != "" {
				fmt.Fprintf(&b, "\t\t\tseverity: %q\n", e.Finding.Severity)
			}
			if e.Finding.File != "" {
				fmt.Fprintf(&b, "\t\t\tfile: %q\n", e.Finding.File)
			}
			if e.Finding.Line != 0 {
				fmt.Fprintf(&b, "\t\t\tline: %d\n", e.Finding.Line)
			}
			if e.Finding.Text != "" {
				fmt.Fprintf(&b, "\t\t\ttext: %q\n", e.Finding.Text)
			}
			b.WriteString("\t\t}\n")
		}
		b.WriteString("\t},\n")
	}
	b.WriteString("]\n")
	return b.String()
}

// toEntry converts a loaded cue.Amendment into the renderer's amendmentEntry.
func toEntry(a cuepkg.Amendment) amendmentEntry {
	return amendmentEntry{
		Name:    a.Name,
		Prompt:  a.Prompt,
		Origin:  a.Origin,
		Finding: toFindingEntry(a.Finding),
	}
}

// toFindingEntry maps a cue.Finding to a findingEntry, nil-safe.
func toFindingEntry(f *cuepkg.Finding) *findingEntry {
	if f == nil {
		return nil
	}
	return &findingEntry{
		Severity: f.Severity,
		File:     f.File,
		Line:     f.Line,
		Text:     f.Text,
	}
}

// sortEntriesByName orders entries by Name for deterministic override output.
func sortEntriesByName(entries []amendmentEntry) {
	sort.Slice(entries, func(i, j int) bool { return entries[i].Name < entries[j].Name })
}

// resourceShortName returns the last "."-separated segment of a registry id
// (e.g. "valueObject.Audio.EqualTemperament" → "EqualTemperament").
func resourceShortName(id string) string {
	if i := strings.LastIndex(id, "."); i >= 0 {
		return id[i+1:]
	}
	return id
}

// cuePackageName reads the `package <name>` clause from any .cue file in the
// spec dir, defaulting to "crestsynth" when none is found.
func (s *Spec) cuePackageName() string {
	entries, err := os.ReadDir(s.cfg.SpecDir)
	if err != nil {
		return "crestsynth"
	}
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".cue") {
			continue
		}
		data, err := s.fs.ReadFile(filepath.Join(s.cfg.SpecDir, e.Name()))
		if err != nil {
			continue
		}
		for _, line := range strings.Split(string(data), "\n") {
			line = strings.TrimSpace(line)
			if strings.HasPrefix(line, "package ") {
				return strings.TrimSpace(strings.TrimPrefix(line, "package "))
			}
		}
	}
	return "crestsynth"
}

// amendmentOverridePath is the spec-dir path of a resource's override file.
func (s *Spec) amendmentOverridePath(shortName string) string {
	return filepath.Join(s.cfg.SpecDir, "override-"+shortName+".cue")
}
