// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_events.sql

package db

import (
	"context"
)

const createAgentEvent = `-- name: CreateAgentEvent :exec
INSERT INTO agent_events (id, generation_id, resource_id, apply_id, event_type, attempt, content, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAgentEventParams struct {
	ID           string
	GenerationID *string
	ResourceID   string
	ApplyID      *string
	EventType    string
	Attempt      *int64
	Content      *string
	CreatedAt    string
}

func (q *Queries) CreateAgentEvent(ctx context.Context, arg CreateAgentEventParams) error {
	_, err := q.db.ExecContext(ctx, createAgentEvent,
		arg.ID,
		arg.GenerationID,
		arg.ResourceID,
		arg.ApplyID,
		arg.EventType,
		arg.Attempt,
		arg.Content,
		arg.CreatedAt,
	)
	return err
}

const deleteAgentEventsBefore = `-- name: DeleteAgentEventsBefore :exec
DELETE FROM agent_events WHERE created_at < ?
`

func (q *Queries) DeleteAgentEventsBefore(ctx context.Context, createdAt string) error {
	_, err := q.db.ExecContext(ctx, deleteAgentEventsBefore, createdAt)
	return err
}

const listAgentEventsByApply = `-- name: ListAgentEventsByApply :many
SELECT id, generation_id, resource_id, apply_id, event_type, attempt, content, created_at FROM agent_events
WHERE apply_id = ?
ORDER BY created_at DESC
LIMIT ?
`

type ListAgentEventsByApplyParams struct {
	ApplyID *string
	Limit   int64
}

func (q *Queries) ListAgentEventsByApply(ctx context.Context, arg ListAgentEventsByApplyParams) ([]AgentEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAgentEventsByApply, arg.ApplyID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentEvent
	for rows.Next() {
		var i AgentEvent
		if err := rows.Scan(
			&i.ID,
			&i.GenerationID,
			&i.ResourceID,
			&i.ApplyID,
			&i.EventType,
			&i.Attempt,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentEventsByGeneration = `-- name: ListAgentEventsByGeneration :many
SELECT id, generation_id, resource_id, apply_id, event_type, attempt, content, created_at FROM agent_events
WHERE generation_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListAgentEventsByGeneration(ctx context.Context, generationID *string) ([]AgentEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAgentEventsByGeneration, generationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentEvent
	for rows.Next() {
		var i AgentEvent
		if err := rows.Scan(
			&i.ID,
			&i.GenerationID,
			&i.ResourceID,
			&i.ApplyID,
			&i.EventType,
			&i.Attempt,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentEventsByResource = `-- name: ListAgentEventsByResource :many
SELECT id, generation_id, resource_id, apply_id, event_type, attempt, content, created_at FROM agent_events
WHERE resource_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListAgentEventsByResource(ctx context.Context, resourceID string) ([]AgentEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAgentEventsByResource, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentEvent
	for rows.Next() {
		var i AgentEvent
		if err := rows.Scan(
			&i.ID,
			&i.GenerationID,
			&i.ResourceID,
			&i.ApplyID,
			&i.EventType,
			&i.Attempt,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentAgentEvents = `-- name: ListRecentAgentEvents :many
SELECT id, generation_id, resource_id, apply_id, event_type, attempt, content, created_at FROM agent_events
ORDER BY created_at DESC
LIMIT ?
`

func (q *Queries) ListRecentAgentEvents(ctx context.Context, limit int64) ([]AgentEvent, error) {
	rows, err := q.db.QueryContext(ctx, listRecentAgentEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentEvent
	for rows.Next() {
		var i AgentEvent
		if err := rows.Scan(
			&i.ID,
			&i.GenerationID,
			&i.ResourceID,
			&i.ApplyID,
			&i.EventType,
			&i.Attempt,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
