// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: amendments.sql

package db

import (
	"context"
)

const deleteAmendment = `-- name: DeleteAmendment :exec
DELETE FROM amendments WHERE resource_id = ? AND name = ?
`

type DeleteAmendmentParams struct {
	ResourceID string
	Name       string
}

func (q *Queries) DeleteAmendment(ctx context.Context, arg DeleteAmendmentParams) error {
	_, err := q.db.ExecContext(ctx, deleteAmendment, arg.ResourceID, arg.Name)
	return err
}

const getAmendment = `-- name: GetAmendment :one
SELECT id, resource_id, name, content_hash, origin, prompt, finding_json, validation_json, state, applied_spec_hash, created_at, applied_at, graduated_at FROM amendments WHERE resource_id = ? AND name = ?
`

type GetAmendmentParams struct {
	ResourceID string
	Name       string
}

func (q *Queries) GetAmendment(ctx context.Context, arg GetAmendmentParams) (Amendment, error) {
	row := q.db.QueryRowContext(ctx, getAmendment, arg.ResourceID, arg.Name)
	var i Amendment
	err := row.Scan(
		&i.ID,
		&i.ResourceID,
		&i.Name,
		&i.ContentHash,
		&i.Origin,
		&i.Prompt,
		&i.FindingJson,
		&i.ValidationJson,
		&i.State,
		&i.AppliedSpecHash,
		&i.CreatedAt,
		&i.AppliedAt,
		&i.GraduatedAt,
	)
	return i, err
}

const listAllAmendments = `-- name: ListAllAmendments :many
SELECT id, resource_id, name, content_hash, origin, prompt, finding_json, validation_json, state, applied_spec_hash, created_at, applied_at, graduated_at FROM amendments ORDER BY created_at ASC
`

func (q *Queries) ListAllAmendments(ctx context.Context) ([]Amendment, error) {
	rows, err := q.db.QueryContext(ctx, listAllAmendments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Amendment
	for rows.Next() {
		var i Amendment
		if err := rows.Scan(
			&i.ID,
			&i.ResourceID,
			&i.Name,
			&i.ContentHash,
			&i.Origin,
			&i.Prompt,
			&i.FindingJson,
			&i.ValidationJson,
			&i.State,
			&i.AppliedSpecHash,
			&i.CreatedAt,
			&i.AppliedAt,
			&i.GraduatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAmendmentsByResource = `-- name: ListAmendmentsByResource :many
SELECT id, resource_id, name, content_hash, origin, prompt, finding_json, validation_json, state, applied_spec_hash, created_at, applied_at, graduated_at FROM amendments WHERE resource_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListAmendmentsByResource(ctx context.Context, resourceID string) ([]Amendment, error) {
	rows, err := q.db.QueryContext(ctx, listAmendmentsByResource, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Amendment
	for rows.Next() {
		var i Amendment
		if err := rows.Scan(
			&i.ID,
			&i.ResourceID,
			&i.Name,
			&i.ContentHash,
			&i.Origin,
			&i.Prompt,
			&i.FindingJson,
			&i.ValidationJson,
			&i.State,
			&i.AppliedSpecHash,
			&i.CreatedAt,
			&i.AppliedAt,
			&i.GraduatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAmendmentsByState = `-- name: ListAmendmentsByState :many
SELECT id, resource_id, name, content_hash, origin, prompt, finding_json, validation_json, state, applied_spec_hash, created_at, applied_at, graduated_at FROM amendments WHERE state = ? ORDER BY created_at ASC
`

func (q *Queries) ListAmendmentsByState(ctx context.Context, state string) ([]Amendment, error) {
	rows, err := q.db.QueryContext(ctx, listAmendmentsByState, state)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Amendment
	for rows.Next() {
		var i Amendment
		if err := rows.Scan(
			&i.ID,
			&i.ResourceID,
			&i.Name,
			&i.ContentHash,
			&i.Origin,
			&i.Prompt,
			&i.FindingJson,
			&i.ValidationJson,
			&i.State,
			&i.AppliedSpecHash,
			&i.CreatedAt,
			&i.AppliedAt,
			&i.GraduatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAmendmentState = `-- name: UpdateAmendmentState :exec
UPDATE amendments SET state = ?, applied_spec_hash = ?, applied_at = ?, graduated_at = ? WHERE id = ?
`

type UpdateAmendmentStateParams struct {
	State           string
	AppliedSpecHash string
	AppliedAt       string
	GraduatedAt     string
	ID              string
}

func (q *Queries) UpdateAmendmentState(ctx context.Context, arg UpdateAmendmentStateParams) error {
	_, err := q.db.ExecContext(ctx, updateAmendmentState,
		arg.State,
		arg.AppliedSpecHash,
		arg.AppliedAt,
		arg.GraduatedAt,
		arg.ID,
	)
	return err
}

const upsertAmendment = `-- name: UpsertAmendment :exec
INSERT INTO amendments (id, resource_id, name, content_hash, origin, prompt, finding_json, validation_json, state, applied_spec_hash, created_at, applied_at, graduated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(resource_id, name) DO UPDATE SET
    content_hash      = excluded.content_hash,
    origin            = excluded.origin,
    prompt            = excluded.prompt,
    finding_json      = excluded.finding_json,
    validation_json   = excluded.validation_json,
    state             = excluded.state,
    applied_spec_hash = excluded.applied_spec_hash
`

type UpsertAmendmentParams struct {
	ID              string
	ResourceID      string
	Name            string
	ContentHash     string
	Origin          string
	Prompt          string
	FindingJson     string
	ValidationJson  string
	State           string
	AppliedSpecHash string
	CreatedAt       string
	AppliedAt       string
	GraduatedAt     string
}

func (q *Queries) UpsertAmendment(ctx context.Context, arg UpsertAmendmentParams) error {
	_, err := q.db.ExecContext(ctx, upsertAmendment,
		arg.ID,
		arg.ResourceID,
		arg.Name,
		arg.ContentHash,
		arg.Origin,
		arg.Prompt,
		arg.FindingJson,
		arg.ValidationJson,
		arg.State,
		arg.AppliedSpecHash,
		arg.CreatedAt,
		arg.AppliedAt,
		arg.GraduatedAt,
	)
	return err
}
