// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: applies.sql

package db

import (
	"context"
	"database/sql"
)

const completeApply = `-- name: CompleteApply :execresult
UPDATE applies SET status = 'completed', done_at = ?
WHERE id = ? AND status = 'running'
`

type CompleteApplyParams struct {
	DoneAt *string
	ID     string
}

func (q *Queries) CompleteApply(ctx context.Context, arg CompleteApplyParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, completeApply, arg.DoneAt, arg.ID)
}

const createApply = `-- name: CreateApply :exec
INSERT INTO applies (id, spec_hash, started_at)
VALUES (?, ?, ?)
`

type CreateApplyParams struct {
	ID        string
	SpecHash  string
	StartedAt string
}

func (q *Queries) CreateApply(ctx context.Context, arg CreateApplyParams) error {
	_, err := q.db.ExecContext(ctx, createApply, arg.ID, arg.SpecHash, arg.StartedAt)
	return err
}

const createApplyAction = `-- name: CreateApplyAction :exec
INSERT INTO apply_actions (id, apply_id, resource_id, action, started_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateApplyActionParams struct {
	ID         string
	ApplyID    string
	ResourceID string
	Action     string
	StartedAt  string
}

func (q *Queries) CreateApplyAction(ctx context.Context, arg CreateApplyActionParams) error {
	_, err := q.db.ExecContext(ctx, createApplyAction,
		arg.ID,
		arg.ApplyID,
		arg.ResourceID,
		arg.Action,
		arg.StartedAt,
	)
	return err
}

const failApply = `-- name: FailApply :execresult
UPDATE applies SET status = 'failed', done_at = ?
WHERE id = ? AND status = 'running'
`

type FailApplyParams struct {
	DoneAt *string
	ID     string
}

func (q *Queries) FailApply(ctx context.Context, arg FailApplyParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, failApply, arg.DoneAt, arg.ID)
}

const getApply = `-- name: GetApply :one
SELECT id, status, spec_hash, started_at, done_at FROM applies WHERE id = ?
`

func (q *Queries) GetApply(ctx context.Context, id string) (Apply, error) {
	row := q.db.QueryRowContext(ctx, getApply, id)
	var i Apply
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.SpecHash,
		&i.StartedAt,
		&i.DoneAt,
	)
	return i, err
}

const listApplies = `-- name: ListApplies :many
SELECT id, status, spec_hash, started_at, done_at FROM applies ORDER BY started_at DESC LIMIT ?
`

func (q *Queries) ListApplies(ctx context.Context, limit int64) ([]Apply, error) {
	rows, err := q.db.QueryContext(ctx, listApplies, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Apply
	for rows.Next() {
		var i Apply
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.SpecHash,
			&i.StartedAt,
			&i.DoneAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApplyActions = `-- name: ListApplyActions :many
SELECT id, apply_id, resource_id, "action", outcome, error, started_at, done_at FROM apply_actions WHERE apply_id = ? ORDER BY started_at
`

func (q *Queries) ListApplyActions(ctx context.Context, applyID string) ([]ApplyAction, error) {
	rows, err := q.db.QueryContext(ctx, listApplyActions, applyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApplyAction
	for rows.Next() {
		var i ApplyAction
		if err := rows.Scan(
			&i.ID,
			&i.ApplyID,
			&i.ResourceID,
			&i.Action,
			&i.Outcome,
			&i.Error,
			&i.StartedAt,
			&i.DoneAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApplyAction = `-- name: UpdateApplyAction :exec
UPDATE apply_actions SET outcome = ?, error = ?, done_at = ?
WHERE id = ?
`

type UpdateApplyActionParams struct {
	Outcome *string
	Error   *string
	DoneAt  *string
	ID      string
}

func (q *Queries) UpdateApplyAction(ctx context.Context, arg UpdateApplyActionParams) error {
	_, err := q.db.ExecContext(ctx, updateApplyAction,
		arg.Outcome,
		arg.Error,
		arg.DoneAt,
		arg.ID,
	)
	return err
}
