// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: behavioral.sql

package db

import (
	"context"
)

const deleteChecksByResource = `-- name: DeleteChecksByResource :exec
DELETE FROM checks WHERE resource_id = ?
`

func (q *Queries) DeleteChecksByResource(ctx context.Context, resourceID string) error {
	_, err := q.db.ExecContext(ctx, deleteChecksByResource, resourceID)
	return err
}

const deleteTasksByResource = `-- name: DeleteTasksByResource :exec
DELETE FROM tasks WHERE resource_id = ?
`

func (q *Queries) DeleteTasksByResource(ctx context.Context, resourceID string) error {
	_, err := q.db.ExecContext(ctx, deleteTasksByResource, resourceID)
	return err
}

const getCheck = `-- name: GetCheck :one
SELECT id, task_id, resource_id, behavior, check_json, state, created_at, updated_at FROM checks WHERE id = ?
`

func (q *Queries) GetCheck(ctx context.Context, id string) (Check, error) {
	row := q.db.QueryRowContext(ctx, getCheck, id)
	var i Check
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ResourceID,
		&i.Behavior,
		&i.CheckJson,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDesign = `-- name: GetDesign :one
SELECT context_name, spec_hash, contract_json, created_at, updated_at FROM designs WHERE context_name = ?
`

func (q *Queries) GetDesign(ctx context.Context, contextName string) (Design, error) {
	row := q.db.QueryRowContext(ctx, getDesign, contextName)
	var i Design
	err := row.Scan(
		&i.ContextName,
		&i.SpecHash,
		&i.ContractJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, resource_id, context_name, spec_hash, description, state, created_at, updated_at FROM tasks WHERE id = ?
`

func (q *Queries) GetTask(ctx context.Context, id string) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ResourceID,
		&i.ContextName,
		&i.SpecHash,
		&i.Description,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCheck = `-- name: InsertCheck :exec
INSERT INTO checks (id, task_id, resource_id, behavior, check_json, state, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, 'pending', ?, ?)
`

type InsertCheckParams struct {
	ID         string
	TaskID     string
	ResourceID string
	Behavior   string
	CheckJson  string
	CreatedAt  string
	UpdatedAt  string
}

func (q *Queries) InsertCheck(ctx context.Context, arg InsertCheckParams) error {
	_, err := q.db.ExecContext(ctx, insertCheck,
		arg.ID,
		arg.TaskID,
		arg.ResourceID,
		arg.Behavior,
		arg.CheckJson,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertTask = `-- name: InsertTask :exec
INSERT INTO tasks (id, resource_id, context_name, spec_hash, description, state, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, 'pending', ?, ?)
`

type InsertTaskParams struct {
	ID          string
	ResourceID  string
	ContextName string
	SpecHash    string
	Description string
	CreatedAt   string
	UpdatedAt   string
}

func (q *Queries) InsertTask(ctx context.Context, arg InsertTaskParams) error {
	_, err := q.db.ExecContext(ctx, insertTask,
		arg.ID,
		arg.ResourceID,
		arg.ContextName,
		arg.SpecHash,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertVerification = `-- name: InsertVerification :exec
INSERT INTO verifications (id, check_id, resource_id, real_obs_json, stub_obs_json, passed, theater, reason, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertVerificationParams struct {
	ID          string
	CheckID     string
	ResourceID  string
	RealObsJson string
	StubObsJson string
	Passed      int64
	Theater     int64
	Reason      string
	CreatedAt   string
}

func (q *Queries) InsertVerification(ctx context.Context, arg InsertVerificationParams) error {
	_, err := q.db.ExecContext(ctx, insertVerification,
		arg.ID,
		arg.CheckID,
		arg.ResourceID,
		arg.RealObsJson,
		arg.StubObsJson,
		arg.Passed,
		arg.Theater,
		arg.Reason,
		arg.CreatedAt,
	)
	return err
}

const listChecksByResource = `-- name: ListChecksByResource :many
SELECT id, task_id, resource_id, behavior, check_json, state, created_at, updated_at FROM checks WHERE resource_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListChecksByResource(ctx context.Context, resourceID string) ([]Check, error) {
	rows, err := q.db.QueryContext(ctx, listChecksByResource, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Check
	for rows.Next() {
		var i Check
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.ResourceID,
			&i.Behavior,
			&i.CheckJson,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChecksByTask = `-- name: ListChecksByTask :many
SELECT id, task_id, resource_id, behavior, check_json, state, created_at, updated_at FROM checks WHERE task_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListChecksByTask(ctx context.Context, taskID string) ([]Check, error) {
	rows, err := q.db.QueryContext(ctx, listChecksByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Check
	for rows.Next() {
		var i Check
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.ResourceID,
			&i.Behavior,
			&i.CheckJson,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDesigns = `-- name: ListDesigns :many
SELECT context_name, spec_hash, contract_json, created_at, updated_at FROM designs ORDER BY context_name ASC
`

func (q *Queries) ListDesigns(ctx context.Context) ([]Design, error) {
	rows, err := q.db.QueryContext(ctx, listDesigns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Design
	for rows.Next() {
		var i Design
		if err := rows.Scan(
			&i.ContextName,
			&i.SpecHash,
			&i.ContractJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByResource = `-- name: ListTasksByResource :many
SELECT id, resource_id, context_name, spec_hash, description, state, created_at, updated_at FROM tasks WHERE resource_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListTasksByResource(ctx context.Context, resourceID string) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByResource, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ResourceID,
			&i.ContextName,
			&i.SpecHash,
			&i.Description,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerificationsByCheck = `-- name: ListVerificationsByCheck :many
SELECT id, check_id, resource_id, real_obs_json, stub_obs_json, passed, theater, reason, created_at FROM verifications WHERE check_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListVerificationsByCheck(ctx context.Context, checkID string) ([]Verification, error) {
	rows, err := q.db.QueryContext(ctx, listVerificationsByCheck, checkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Verification
	for rows.Next() {
		var i Verification
		if err := rows.Scan(
			&i.ID,
			&i.CheckID,
			&i.ResourceID,
			&i.RealObsJson,
			&i.StubObsJson,
			&i.Passed,
			&i.Theater,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCheckState = `-- name: SetCheckState :exec
UPDATE checks SET state = ?, updated_at = ? WHERE id = ?
`

type SetCheckStateParams struct {
	State     string
	UpdatedAt string
	ID        string
}

func (q *Queries) SetCheckState(ctx context.Context, arg SetCheckStateParams) error {
	_, err := q.db.ExecContext(ctx, setCheckState, arg.State, arg.UpdatedAt, arg.ID)
	return err
}

const setTaskState = `-- name: SetTaskState :exec
UPDATE tasks SET state = ?, updated_at = ? WHERE id = ?
`

type SetTaskStateParams struct {
	State     string
	UpdatedAt string
	ID        string
}

func (q *Queries) SetTaskState(ctx context.Context, arg SetTaskStateParams) error {
	_, err := q.db.ExecContext(ctx, setTaskState, arg.State, arg.UpdatedAt, arg.ID)
	return err
}

const upsertDesign = `-- name: UpsertDesign :exec
INSERT INTO designs (context_name, spec_hash, contract_json, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(context_name) DO UPDATE SET
    spec_hash     = excluded.spec_hash,
    contract_json = excluded.contract_json,
    updated_at    = excluded.updated_at
`

type UpsertDesignParams struct {
	ContextName  string
	SpecHash     string
	ContractJson string
	CreatedAt    string
	UpdatedAt    string
}

func (q *Queries) UpsertDesign(ctx context.Context, arg UpsertDesignParams) error {
	_, err := q.db.ExecContext(ctx, upsertDesign,
		arg.ContextName,
		arg.SpecHash,
		arg.ContractJson,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
