// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: context_manifests.sql

package db

import (
	"context"
)

const countContentBlobs = `-- name: CountContentBlobs :one
SELECT COUNT(*) FROM content_blobs
`

func (q *Queries) CountContentBlobs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countContentBlobs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGenerationAttempts = `-- name: CountGenerationAttempts :one
SELECT COUNT(*) FROM generation_attempts
WHERE session_id = ? AND resource_id = ?
`

type CountGenerationAttemptsParams struct {
	SessionID  string
	ResourceID string
}

func (q *Queries) CountGenerationAttempts(ctx context.Context, arg CountGenerationAttemptsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countGenerationAttempts, arg.SessionID, arg.ResourceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createContextManifest = `-- name: CreateContextManifest :exec
INSERT INTO context_manifests (
    id, attempt_id, selector_version, estimator_version, selection_strategy,
    budget_tokens, estimated_tokens, original_bytes, selected_bytes,
    template_hashes_json, system_prompt_blob, rendered_prompt_blob,
    context_hash, blocked, blocked_reason, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateContextManifestParams struct {
	ID                 string
	AttemptID          string
	SelectorVersion    string
	EstimatorVersion   string
	SelectionStrategy  string
	BudgetTokens       int64
	EstimatedTokens    int64
	OriginalBytes      int64
	SelectedBytes      int64
	TemplateHashesJson string
	SystemPromptBlob   string
	RenderedPromptBlob string
	ContextHash        string
	Blocked            int64
	BlockedReason      string
	CreatedAt          string
}

func (q *Queries) CreateContextManifest(ctx context.Context, arg CreateContextManifestParams) error {
	_, err := q.db.ExecContext(ctx, createContextManifest,
		arg.ID,
		arg.AttemptID,
		arg.SelectorVersion,
		arg.EstimatorVersion,
		arg.SelectionStrategy,
		arg.BudgetTokens,
		arg.EstimatedTokens,
		arg.OriginalBytes,
		arg.SelectedBytes,
		arg.TemplateHashesJson,
		arg.SystemPromptBlob,
		arg.RenderedPromptBlob,
		arg.ContextHash,
		arg.Blocked,
		arg.BlockedReason,
		arg.CreatedAt,
	)
	return err
}

const createContextSection = `-- name: CreateContextSection :exec
INSERT INTO context_sections (
    id, manifest_id, ordinal, section_kind, title, source_kind, source_id,
    source_path, priority, mandatory, decision, reason, original_hash,
    content_blob, original_bytes, selected_bytes, estimated_tokens
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateContextSectionParams struct {
	ID              string
	ManifestID      string
	Ordinal         int64
	SectionKind     string
	Title           string
	SourceKind      string
	SourceID        string
	SourcePath      string
	Priority        int64
	Mandatory       int64
	Decision        string
	Reason          string
	OriginalHash    string
	ContentBlob     *string
	OriginalBytes   int64
	SelectedBytes   int64
	EstimatedTokens int64
}

func (q *Queries) CreateContextSection(ctx context.Context, arg CreateContextSectionParams) error {
	_, err := q.db.ExecContext(ctx, createContextSection,
		arg.ID,
		arg.ManifestID,
		arg.Ordinal,
		arg.SectionKind,
		arg.Title,
		arg.SourceKind,
		arg.SourceID,
		arg.SourcePath,
		arg.Priority,
		arg.Mandatory,
		arg.Decision,
		arg.Reason,
		arg.OriginalHash,
		arg.ContentBlob,
		arg.OriginalBytes,
		arg.SelectedBytes,
		arg.EstimatedTokens,
	)
	return err
}

const createGenerationAttempt = `-- name: CreateGenerationAttempt :exec
INSERT INTO generation_attempts (
    id, session_id, apply_id, resource_id, plan_operation_id,
    parent_attempt_id, retry_number, role, status, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateGenerationAttemptParams struct {
	ID              string
	SessionID       string
	ApplyID         string
	ResourceID      string
	PlanOperationID string
	ParentAttemptID *string
	RetryNumber     int64
	Role            string
	Status          string
	CreatedAt       string
}

func (q *Queries) CreateGenerationAttempt(ctx context.Context, arg CreateGenerationAttemptParams) error {
	_, err := q.db.ExecContext(ctx, createGenerationAttempt,
		arg.ID,
		arg.SessionID,
		arg.ApplyID,
		arg.ResourceID,
		arg.PlanOperationID,
		arg.ParentAttemptID,
		arg.RetryNumber,
		arg.Role,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}

const getContentBlob = `-- name: GetContentBlob :one
SELECT hash, content, byte_size, created_at FROM content_blobs WHERE hash = ?
`

func (q *Queries) GetContentBlob(ctx context.Context, hash string) (ContentBlob, error) {
	row := q.db.QueryRowContext(ctx, getContentBlob, hash)
	var i ContentBlob
	err := row.Scan(
		&i.Hash,
		&i.Content,
		&i.ByteSize,
		&i.CreatedAt,
	)
	return i, err
}

const getContextManifest = `-- name: GetContextManifest :one
SELECT id, attempt_id, selector_version, estimator_version, selection_strategy, budget_tokens, estimated_tokens, original_bytes, selected_bytes, template_hashes_json, system_prompt_blob, rendered_prompt_blob, context_hash, blocked, blocked_reason, created_at FROM context_manifests WHERE id = ?
`

func (q *Queries) GetContextManifest(ctx context.Context, id string) (ContextManifest, error) {
	row := q.db.QueryRowContext(ctx, getContextManifest, id)
	var i ContextManifest
	err := row.Scan(
		&i.ID,
		&i.AttemptID,
		&i.SelectorVersion,
		&i.EstimatorVersion,
		&i.SelectionStrategy,
		&i.BudgetTokens,
		&i.EstimatedTokens,
		&i.OriginalBytes,
		&i.SelectedBytes,
		&i.TemplateHashesJson,
		&i.SystemPromptBlob,
		&i.RenderedPromptBlob,
		&i.ContextHash,
		&i.Blocked,
		&i.BlockedReason,
		&i.CreatedAt,
	)
	return i, err
}

const getContextManifestByAttempt = `-- name: GetContextManifestByAttempt :one
SELECT id, attempt_id, selector_version, estimator_version, selection_strategy, budget_tokens, estimated_tokens, original_bytes, selected_bytes, template_hashes_json, system_prompt_blob, rendered_prompt_blob, context_hash, blocked, blocked_reason, created_at FROM context_manifests WHERE attempt_id = ?
`

func (q *Queries) GetContextManifestByAttempt(ctx context.Context, attemptID string) (ContextManifest, error) {
	row := q.db.QueryRowContext(ctx, getContextManifestByAttempt, attemptID)
	var i ContextManifest
	err := row.Scan(
		&i.ID,
		&i.AttemptID,
		&i.SelectorVersion,
		&i.EstimatorVersion,
		&i.SelectionStrategy,
		&i.BudgetTokens,
		&i.EstimatedTokens,
		&i.OriginalBytes,
		&i.SelectedBytes,
		&i.TemplateHashesJson,
		&i.SystemPromptBlob,
		&i.RenderedPromptBlob,
		&i.ContextHash,
		&i.Blocked,
		&i.BlockedReason,
		&i.CreatedAt,
	)
	return i, err
}

const getGenerationAttempt = `-- name: GetGenerationAttempt :one
SELECT id, session_id, apply_id, resource_id, plan_operation_id, parent_attempt_id, retry_number, role, status, created_at FROM generation_attempts WHERE id = ?
`

func (q *Queries) GetGenerationAttempt(ctx context.Context, id string) (GenerationAttempt, error) {
	row := q.db.QueryRowContext(ctx, getGenerationAttempt, id)
	var i GenerationAttempt
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ApplyID,
		&i.ResourceID,
		&i.PlanOperationID,
		&i.ParentAttemptID,
		&i.RetryNumber,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestGenerationAttempt = `-- name: GetLatestGenerationAttempt :one
SELECT id, session_id, apply_id, resource_id, plan_operation_id, parent_attempt_id, retry_number, role, status, created_at FROM generation_attempts
WHERE session_id = ? AND resource_id = ?
ORDER BY retry_number DESC LIMIT 1
`

type GetLatestGenerationAttemptParams struct {
	SessionID  string
	ResourceID string
}

func (q *Queries) GetLatestGenerationAttempt(ctx context.Context, arg GetLatestGenerationAttemptParams) (GenerationAttempt, error) {
	row := q.db.QueryRowContext(ctx, getLatestGenerationAttempt, arg.SessionID, arg.ResourceID)
	var i GenerationAttempt
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ApplyID,
		&i.ResourceID,
		&i.PlanOperationID,
		&i.ParentAttemptID,
		&i.RetryNumber,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listContextSections = `-- name: ListContextSections :many
SELECT id, manifest_id, ordinal, section_kind, title, source_kind, source_id, source_path, priority, mandatory, decision, reason, original_hash, content_blob, original_bytes, selected_bytes, estimated_tokens FROM context_sections WHERE manifest_id = ? ORDER BY ordinal
`

func (q *Queries) ListContextSections(ctx context.Context, manifestID string) ([]ContextSection, error) {
	rows, err := q.db.QueryContext(ctx, listContextSections, manifestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContextSection
	for rows.Next() {
		var i ContextSection
		if err := rows.Scan(
			&i.ID,
			&i.ManifestID,
			&i.Ordinal,
			&i.SectionKind,
			&i.Title,
			&i.SourceKind,
			&i.SourceID,
			&i.SourcePath,
			&i.Priority,
			&i.Mandatory,
			&i.Decision,
			&i.Reason,
			&i.OriginalHash,
			&i.ContentBlob,
			&i.OriginalBytes,
			&i.SelectedBytes,
			&i.EstimatedTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGenerationAttemptsByResource = `-- name: ListGenerationAttemptsByResource :many
SELECT id, session_id, apply_id, resource_id, plan_operation_id, parent_attempt_id, retry_number, role, status, created_at FROM generation_attempts
WHERE resource_id = ? ORDER BY created_at DESC, id DESC LIMIT ?
`

type ListGenerationAttemptsByResourceParams struct {
	ResourceID string
	Limit      int64
}

func (q *Queries) ListGenerationAttemptsByResource(ctx context.Context, arg ListGenerationAttemptsByResourceParams) ([]GenerationAttempt, error) {
	rows, err := q.db.QueryContext(ctx, listGenerationAttemptsByResource, arg.ResourceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GenerationAttempt
	for rows.Next() {
		var i GenerationAttempt
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ApplyID,
			&i.ResourceID,
			&i.PlanOperationID,
			&i.ParentAttemptID,
			&i.RetryNumber,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGenerationAttemptsBySession = `-- name: ListGenerationAttemptsBySession :many
SELECT id, session_id, apply_id, resource_id, plan_operation_id, parent_attempt_id, retry_number, role, status, created_at FROM generation_attempts
WHERE session_id = ? ORDER BY created_at, id
`

func (q *Queries) ListGenerationAttemptsBySession(ctx context.Context, sessionID string) ([]GenerationAttempt, error) {
	rows, err := q.db.QueryContext(ctx, listGenerationAttemptsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GenerationAttempt
	for rows.Next() {
		var i GenerationAttempt
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ApplyID,
			&i.ResourceID,
			&i.PlanOperationID,
			&i.ParentAttemptID,
			&i.RetryNumber,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentContextManifests = `-- name: ListRecentContextManifests :many
SELECT id, attempt_id, selector_version, estimator_version, selection_strategy, budget_tokens, estimated_tokens, original_bytes, selected_bytes, template_hashes_json, system_prompt_blob, rendered_prompt_blob, context_hash, blocked, blocked_reason, created_at FROM context_manifests ORDER BY created_at DESC, id DESC LIMIT ?
`

func (q *Queries) ListRecentContextManifests(ctx context.Context, limit int64) ([]ContextManifest, error) {
	rows, err := q.db.QueryContext(ctx, listRecentContextManifests, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContextManifest
	for rows.Next() {
		var i ContextManifest
		if err := rows.Scan(
			&i.ID,
			&i.AttemptID,
			&i.SelectorVersion,
			&i.EstimatorVersion,
			&i.SelectionStrategy,
			&i.BudgetTokens,
			&i.EstimatedTokens,
			&i.OriginalBytes,
			&i.SelectedBytes,
			&i.TemplateHashesJson,
			&i.SystemPromptBlob,
			&i.RenderedPromptBlob,
			&i.ContextHash,
			&i.Blocked,
			&i.BlockedReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentGenerationAttempts = `-- name: ListRecentGenerationAttempts :many
SELECT id, session_id, apply_id, resource_id, plan_operation_id, parent_attempt_id, retry_number, role, status, created_at FROM generation_attempts
ORDER BY created_at DESC, id DESC LIMIT ?
`

func (q *Queries) ListRecentGenerationAttempts(ctx context.Context, limit int64) ([]GenerationAttempt, error) {
	rows, err := q.db.QueryContext(ctx, listRecentGenerationAttempts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GenerationAttempt
	for rows.Next() {
		var i GenerationAttempt
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ApplyID,
			&i.ResourceID,
			&i.PlanOperationID,
			&i.ParentAttemptID,
			&i.RetryNumber,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putContentBlob = `-- name: PutContentBlob :exec
INSERT INTO content_blobs (hash, content, byte_size, created_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(hash) DO NOTHING
`

type PutContentBlobParams struct {
	Hash      string
	Content   []byte
	ByteSize  int64
	CreatedAt string
}

func (q *Queries) PutContentBlob(ctx context.Context, arg PutContentBlobParams) error {
	_, err := q.db.ExecContext(ctx, putContentBlob,
		arg.Hash,
		arg.Content,
		arg.ByteSize,
		arg.CreatedAt,
	)
	return err
}

const setSessionResourceDispatchedTx = `-- name: SetSessionResourceDispatchedTx :execrows
UPDATE session_resources
SET state = 'dispatched', phase = 'queued', dispatched_at = ?, updated_at = ?
WHERE session_id = ? AND resource_id = ?
`

type SetSessionResourceDispatchedTxParams struct {
	DispatchedAt string
	UpdatedAt    string
	SessionID    string
	ResourceID   string
}

func (q *Queries) SetSessionResourceDispatchedTx(ctx context.Context, arg SetSessionResourceDispatchedTxParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setSessionResourceDispatchedTx,
		arg.DispatchedAt,
		arg.UpdatedAt,
		arg.SessionID,
		arg.ResourceID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
