// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: evaluations.sql

package db

import (
	"context"
)

const addEvaluationDatasetCase = `-- name: AddEvaluationDatasetCase :exec
INSERT INTO evaluation_dataset_cases (dataset_id, case_id, split, ordinal)
VALUES (?, ?, ?, ?)
`

type AddEvaluationDatasetCaseParams struct {
	DatasetID string
	CaseID    string
	Split     string
	Ordinal   int64
}

func (q *Queries) AddEvaluationDatasetCase(ctx context.Context, arg AddEvaluationDatasetCaseParams) error {
	_, err := q.db.ExecContext(ctx, addEvaluationDatasetCase,
		arg.DatasetID,
		arg.CaseID,
		arg.Split,
		arg.Ordinal,
	)
	return err
}

const getEvaluationCase = `-- name: GetEvaluationCase :one
SELECT id, identity_hash, provenance, source_attempt_id, project_name, goal_id, capability_id, resource_id, spec_hash, repository_hash, resource_declaration_hash, plan_operation_id, context_manifest_id, execution_id, candidate_id, payload_blob, expected_outcome_blob, created_at FROM evaluation_cases WHERE id = ?
`

func (q *Queries) GetEvaluationCase(ctx context.Context, id string) (EvaluationCase, error) {
	row := q.db.QueryRowContext(ctx, getEvaluationCase, id)
	var i EvaluationCase
	err := row.Scan(
		&i.ID,
		&i.IdentityHash,
		&i.Provenance,
		&i.SourceAttemptID,
		&i.ProjectName,
		&i.GoalID,
		&i.CapabilityID,
		&i.ResourceID,
		&i.SpecHash,
		&i.RepositoryHash,
		&i.ResourceDeclarationHash,
		&i.PlanOperationID,
		&i.ContextManifestID,
		&i.ExecutionID,
		&i.CandidateID,
		&i.PayloadBlob,
		&i.ExpectedOutcomeBlob,
		&i.CreatedAt,
	)
	return i, err
}

const getEvaluationCaseAssessment = `-- name: GetEvaluationCaseAssessment :one
SELECT source_attempt_id, eligible, reason, case_id, assessed_at FROM evaluation_case_assessments WHERE source_attempt_id = ?
`

func (q *Queries) GetEvaluationCaseAssessment(ctx context.Context, sourceAttemptID string) (EvaluationCaseAssessment, error) {
	row := q.db.QueryRowContext(ctx, getEvaluationCaseAssessment, sourceAttemptID)
	var i EvaluationCaseAssessment
	err := row.Scan(
		&i.SourceAttemptID,
		&i.Eligible,
		&i.Reason,
		&i.CaseID,
		&i.AssessedAt,
	)
	return i, err
}

const getEvaluationCaseByIdentity = `-- name: GetEvaluationCaseByIdentity :one
SELECT id, identity_hash, provenance, source_attempt_id, project_name, goal_id, capability_id, resource_id, spec_hash, repository_hash, resource_declaration_hash, plan_operation_id, context_manifest_id, execution_id, candidate_id, payload_blob, expected_outcome_blob, created_at FROM evaluation_cases WHERE identity_hash = ?
`

func (q *Queries) GetEvaluationCaseByIdentity(ctx context.Context, identityHash string) (EvaluationCase, error) {
	row := q.db.QueryRowContext(ctx, getEvaluationCaseByIdentity, identityHash)
	var i EvaluationCase
	err := row.Scan(
		&i.ID,
		&i.IdentityHash,
		&i.Provenance,
		&i.SourceAttemptID,
		&i.ProjectName,
		&i.GoalID,
		&i.CapabilityID,
		&i.ResourceID,
		&i.SpecHash,
		&i.RepositoryHash,
		&i.ResourceDeclarationHash,
		&i.PlanOperationID,
		&i.ContextManifestID,
		&i.ExecutionID,
		&i.CandidateID,
		&i.PayloadBlob,
		&i.ExpectedOutcomeBlob,
		&i.CreatedAt,
	)
	return i, err
}

const getEvaluationConfiguration = `-- name: GetEvaluationConfiguration :one
SELECT id, name, identity_hash, planner_version, planner_policy_hash, context_selector_version, context_budget_tokens, template_hashes_json, role_policy_version, host_name, host_version, provider, model, inference_config_json, validation_version, learning_ids_json, payload_blob, created_at FROM evaluation_configurations WHERE id = ?
`

func (q *Queries) GetEvaluationConfiguration(ctx context.Context, id string) (EvaluationConfiguration, error) {
	row := q.db.QueryRowContext(ctx, getEvaluationConfiguration, id)
	var i EvaluationConfiguration
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IdentityHash,
		&i.PlannerVersion,
		&i.PlannerPolicyHash,
		&i.ContextSelectorVersion,
		&i.ContextBudgetTokens,
		&i.TemplateHashesJson,
		&i.RolePolicyVersion,
		&i.HostName,
		&i.HostVersion,
		&i.Provider,
		&i.Model,
		&i.InferenceConfigJson,
		&i.ValidationVersion,
		&i.LearningIdsJson,
		&i.PayloadBlob,
		&i.CreatedAt,
	)
	return i, err
}

const getEvaluationConfigurationByIdentity = `-- name: GetEvaluationConfigurationByIdentity :one
SELECT id, name, identity_hash, planner_version, planner_policy_hash, context_selector_version, context_budget_tokens, template_hashes_json, role_policy_version, host_name, host_version, provider, model, inference_config_json, validation_version, learning_ids_json, payload_blob, created_at FROM evaluation_configurations WHERE identity_hash = ?
`

func (q *Queries) GetEvaluationConfigurationByIdentity(ctx context.Context, identityHash string) (EvaluationConfiguration, error) {
	row := q.db.QueryRowContext(ctx, getEvaluationConfigurationByIdentity, identityHash)
	var i EvaluationConfiguration
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IdentityHash,
		&i.PlannerVersion,
		&i.PlannerPolicyHash,
		&i.ContextSelectorVersion,
		&i.ContextBudgetTokens,
		&i.TemplateHashesJson,
		&i.RolePolicyVersion,
		&i.HostName,
		&i.HostVersion,
		&i.Provider,
		&i.Model,
		&i.InferenceConfigJson,
		&i.ValidationVersion,
		&i.LearningIdsJson,
		&i.PayloadBlob,
		&i.CreatedAt,
	)
	return i, err
}

const getEvaluationDataset = `-- name: GetEvaluationDataset :one
SELECT id, name, description, identity_hash, status, created_at, sealed_at FROM evaluation_datasets WHERE id = ?
`

func (q *Queries) GetEvaluationDataset(ctx context.Context, id string) (EvaluationDataset, error) {
	row := q.db.QueryRowContext(ctx, getEvaluationDataset, id)
	var i EvaluationDataset
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IdentityHash,
		&i.Status,
		&i.CreatedAt,
		&i.SealedAt,
	)
	return i, err
}

const listEvaluationCases = `-- name: ListEvaluationCases :many
SELECT id, identity_hash, provenance, source_attempt_id, project_name, goal_id, capability_id, resource_id, spec_hash, repository_hash, resource_declaration_hash, plan_operation_id, context_manifest_id, execution_id, candidate_id, payload_blob, expected_outcome_blob, created_at FROM evaluation_cases ORDER BY created_at DESC, id DESC LIMIT ?
`

func (q *Queries) ListEvaluationCases(ctx context.Context, limit int64) ([]EvaluationCase, error) {
	rows, err := q.db.QueryContext(ctx, listEvaluationCases, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EvaluationCase
	for rows.Next() {
		var i EvaluationCase
		if err := rows.Scan(
			&i.ID,
			&i.IdentityHash,
			&i.Provenance,
			&i.SourceAttemptID,
			&i.ProjectName,
			&i.GoalID,
			&i.CapabilityID,
			&i.ResourceID,
			&i.SpecHash,
			&i.RepositoryHash,
			&i.ResourceDeclarationHash,
			&i.PlanOperationID,
			&i.ContextManifestID,
			&i.ExecutionID,
			&i.CandidateID,
			&i.PayloadBlob,
			&i.ExpectedOutcomeBlob,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvaluationConfigurations = `-- name: ListEvaluationConfigurations :many
SELECT id, name, identity_hash, planner_version, planner_policy_hash, context_selector_version, context_budget_tokens, template_hashes_json, role_policy_version, host_name, host_version, provider, model, inference_config_json, validation_version, learning_ids_json, payload_blob, created_at FROM evaluation_configurations ORDER BY created_at DESC, id DESC LIMIT ?
`

func (q *Queries) ListEvaluationConfigurations(ctx context.Context, limit int64) ([]EvaluationConfiguration, error) {
	rows, err := q.db.QueryContext(ctx, listEvaluationConfigurations, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EvaluationConfiguration
	for rows.Next() {
		var i EvaluationConfiguration
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IdentityHash,
			&i.PlannerVersion,
			&i.PlannerPolicyHash,
			&i.ContextSelectorVersion,
			&i.ContextBudgetTokens,
			&i.TemplateHashesJson,
			&i.RolePolicyVersion,
			&i.HostName,
			&i.HostVersion,
			&i.Provider,
			&i.Model,
			&i.InferenceConfigJson,
			&i.ValidationVersion,
			&i.LearningIdsJson,
			&i.PayloadBlob,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvaluationDatasetCases = `-- name: ListEvaluationDatasetCases :many
SELECT membership.dataset_id, membership.case_id, membership.split, membership.ordinal, evaluation_cases.identity_hash, evaluation_cases.provenance,
       evaluation_cases.project_name, evaluation_cases.goal_id,
       evaluation_cases.capability_id, evaluation_cases.resource_id,
       evaluation_cases.context_manifest_id, evaluation_cases.execution_id,
       evaluation_cases.candidate_id
FROM evaluation_dataset_cases membership
JOIN evaluation_cases ON evaluation_cases.id = membership.case_id
WHERE membership.dataset_id = ?
ORDER BY membership.ordinal
`

type ListEvaluationDatasetCasesRow struct {
	DatasetID         string
	CaseID            string
	Split             string
	Ordinal           int64
	IdentityHash      string
	Provenance        string
	ProjectName       string
	GoalID            string
	CapabilityID      string
	ResourceID        string
	ContextManifestID *string
	ExecutionID       *string
	CandidateID       *string
}

func (q *Queries) ListEvaluationDatasetCases(ctx context.Context, datasetID string) ([]ListEvaluationDatasetCasesRow, error) {
	rows, err := q.db.QueryContext(ctx, listEvaluationDatasetCases, datasetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEvaluationDatasetCasesRow
	for rows.Next() {
		var i ListEvaluationDatasetCasesRow
		if err := rows.Scan(
			&i.DatasetID,
			&i.CaseID,
			&i.Split,
			&i.Ordinal,
			&i.IdentityHash,
			&i.Provenance,
			&i.ProjectName,
			&i.GoalID,
			&i.CapabilityID,
			&i.ResourceID,
			&i.ContextManifestID,
			&i.ExecutionID,
			&i.CandidateID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvaluationDatasets = `-- name: ListEvaluationDatasets :many
SELECT id, name, description, identity_hash, status, created_at, sealed_at FROM evaluation_datasets ORDER BY created_at DESC, id DESC LIMIT ?
`

func (q *Queries) ListEvaluationDatasets(ctx context.Context, limit int64) ([]EvaluationDataset, error) {
	rows, err := q.db.QueryContext(ctx, listEvaluationDatasets, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EvaluationDataset
	for rows.Next() {
		var i EvaluationDataset
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IdentityHash,
			&i.Status,
			&i.CreatedAt,
			&i.SealedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvaluationSourceValidationRuns = `-- name: ListEvaluationSourceValidationRuns :many
SELECT id, definition_snapshot_id, definition_id, session_id, attempt_id, execution_id, source_tree_hash, classification, reason, started_at, completed_at, duration_ms, created_at FROM validation_runs
WHERE attempt_id = ?
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListEvaluationSourceValidationRuns(ctx context.Context, attemptID *string) ([]ValidationRun, error) {
	rows, err := q.db.QueryContext(ctx, listEvaluationSourceValidationRuns, attemptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ValidationRun
	for rows.Next() {
		var i ValidationRun
		if err := rows.Scan(
			&i.ID,
			&i.DefinitionSnapshotID,
			&i.DefinitionID,
			&i.SessionID,
			&i.AttemptID,
			&i.ExecutionID,
			&i.SourceTreeHash,
			&i.Classification,
			&i.Reason,
			&i.StartedAt,
			&i.CompletedAt,
			&i.DurationMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putEvaluationCase = `-- name: PutEvaluationCase :exec
INSERT INTO evaluation_cases (
    id, identity_hash, provenance, source_attempt_id, project_name, goal_id,
    capability_id, resource_id, spec_hash, repository_hash,
    resource_declaration_hash, plan_operation_id, context_manifest_id,
    execution_id, candidate_id, payload_blob, expected_outcome_blob, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(identity_hash) DO NOTHING
`

type PutEvaluationCaseParams struct {
	ID                      string
	IdentityHash            string
	Provenance              string
	SourceAttemptID         *string
	ProjectName             string
	GoalID                  string
	CapabilityID            string
	ResourceID              string
	SpecHash                string
	RepositoryHash          string
	ResourceDeclarationHash string
	PlanOperationID         string
	ContextManifestID       *string
	ExecutionID             *string
	CandidateID             *string
	PayloadBlob             string
	ExpectedOutcomeBlob     string
	CreatedAt               string
}

func (q *Queries) PutEvaluationCase(ctx context.Context, arg PutEvaluationCaseParams) error {
	_, err := q.db.ExecContext(ctx, putEvaluationCase,
		arg.ID,
		arg.IdentityHash,
		arg.Provenance,
		arg.SourceAttemptID,
		arg.ProjectName,
		arg.GoalID,
		arg.CapabilityID,
		arg.ResourceID,
		arg.SpecHash,
		arg.RepositoryHash,
		arg.ResourceDeclarationHash,
		arg.PlanOperationID,
		arg.ContextManifestID,
		arg.ExecutionID,
		arg.CandidateID,
		arg.PayloadBlob,
		arg.ExpectedOutcomeBlob,
		arg.CreatedAt,
	)
	return err
}

const putEvaluationCaseAssessment = `-- name: PutEvaluationCaseAssessment :exec
INSERT INTO evaluation_case_assessments (
    source_attempt_id, eligible, reason, case_id, assessed_at
) VALUES (?, ?, ?, ?, ?)
ON CONFLICT(source_attempt_id) DO UPDATE SET
    eligible = excluded.eligible,
    reason = excluded.reason,
    case_id = excluded.case_id,
    assessed_at = excluded.assessed_at
`

type PutEvaluationCaseAssessmentParams struct {
	SourceAttemptID string
	Eligible        int64
	Reason          string
	CaseID          *string
	AssessedAt      string
}

func (q *Queries) PutEvaluationCaseAssessment(ctx context.Context, arg PutEvaluationCaseAssessmentParams) error {
	_, err := q.db.ExecContext(ctx, putEvaluationCaseAssessment,
		arg.SourceAttemptID,
		arg.Eligible,
		arg.Reason,
		arg.CaseID,
		arg.AssessedAt,
	)
	return err
}

const putEvaluationConfiguration = `-- name: PutEvaluationConfiguration :exec
INSERT INTO evaluation_configurations (
    id, name, identity_hash, planner_version, planner_policy_hash,
    context_selector_version, context_budget_tokens, template_hashes_json,
    role_policy_version, host_name, host_version, provider, model,
    inference_config_json, validation_version, learning_ids_json,
    payload_blob, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(identity_hash) DO NOTHING
`

type PutEvaluationConfigurationParams struct {
	ID                     string
	Name                   string
	IdentityHash           string
	PlannerVersion         string
	PlannerPolicyHash      string
	ContextSelectorVersion string
	ContextBudgetTokens    int64
	TemplateHashesJson     string
	RolePolicyVersion      string
	HostName               string
	HostVersion            string
	Provider               string
	Model                  string
	InferenceConfigJson    string
	ValidationVersion      string
	LearningIdsJson        string
	PayloadBlob            string
	CreatedAt              string
}

func (q *Queries) PutEvaluationConfiguration(ctx context.Context, arg PutEvaluationConfigurationParams) error {
	_, err := q.db.ExecContext(ctx, putEvaluationConfiguration,
		arg.ID,
		arg.Name,
		arg.IdentityHash,
		arg.PlannerVersion,
		arg.PlannerPolicyHash,
		arg.ContextSelectorVersion,
		arg.ContextBudgetTokens,
		arg.TemplateHashesJson,
		arg.RolePolicyVersion,
		arg.HostName,
		arg.HostVersion,
		arg.Provider,
		arg.Model,
		arg.InferenceConfigJson,
		arg.ValidationVersion,
		arg.LearningIdsJson,
		arg.PayloadBlob,
		arg.CreatedAt,
	)
	return err
}

const putEvaluationDataset = `-- name: PutEvaluationDataset :exec
INSERT INTO evaluation_datasets (
    id, name, description, identity_hash, status, created_at, sealed_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type PutEvaluationDatasetParams struct {
	ID           string
	Name         string
	Description  string
	IdentityHash string
	Status       string
	CreatedAt    string
	SealedAt     *string
}

func (q *Queries) PutEvaluationDataset(ctx context.Context, arg PutEvaluationDatasetParams) error {
	_, err := q.db.ExecContext(ctx, putEvaluationDataset,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.IdentityHash,
		arg.Status,
		arg.CreatedAt,
		arg.SealedAt,
	)
	return err
}

const sealEvaluationDataset = `-- name: SealEvaluationDataset :execrows
UPDATE evaluation_datasets
SET identity_hash = ?, status = 'sealed', sealed_at = ?
WHERE id = ? AND status = 'draft'
`

type SealEvaluationDatasetParams struct {
	IdentityHash string
	SealedAt     *string
	ID           string
}

func (q *Queries) SealEvaluationDataset(ctx context.Context, arg SealEvaluationDatasetParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, sealEvaluationDataset, arg.IdentityHash, arg.SealedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
