// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: executions.sql

package db

import (
	"context"
)

const acceptAttemptHandoff = `-- name: AcceptAttemptHandoff :execrows
UPDATE attempt_handoffs
SET target_attempt_id = ?, status = 'accepted', accepted_at = ?
WHERE id = ? AND status = 'pending'
`

type AcceptAttemptHandoffParams struct {
	TargetAttemptID *string
	AcceptedAt      *string
	ID              string
}

func (q *Queries) AcceptAttemptHandoff(ctx context.Context, arg AcceptAttemptHandoffParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, acceptAttemptHandoff, arg.TargetAttemptID, arg.AcceptedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const acceptCandidateFile = `-- name: AcceptCandidateFile :exec
INSERT INTO candidate_file_acceptances (
    candidate_file_id, resource_id, path, accepted_at
) VALUES (?, ?, ?, ?)
`

type AcceptCandidateFileParams struct {
	CandidateFileID string
	ResourceID      string
	Path            string
	AcceptedAt      string
}

func (q *Queries) AcceptCandidateFile(ctx context.Context, arg AcceptCandidateFileParams) error {
	_, err := q.db.ExecContext(ctx, acceptCandidateFile,
		arg.CandidateFileID,
		arg.ResourceID,
		arg.Path,
		arg.AcceptedAt,
	)
	return err
}

const addFailureGoal = `-- name: AddFailureGoal :exec
INSERT INTO failure_goals (failure_id, goal_id) VALUES (?, ?)
`

type AddFailureGoalParams struct {
	FailureID string
	GoalID    string
}

func (q *Queries) AddFailureGoal(ctx context.Context, arg AddFailureGoalParams) error {
	_, err := q.db.ExecContext(ctx, addFailureGoal, arg.FailureID, arg.GoalID)
	return err
}

const createAttemptHandoff = `-- name: CreateAttemptHandoff :exec
INSERT INTO attempt_handoffs (
    id, source_attempt_id, target_attempt_id, source_role, target_role,
    reason, expected_outcome, failure_id, status, created_at, accepted_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAttemptHandoffParams struct {
	ID              string
	SourceAttemptID string
	TargetAttemptID *string
	SourceRole      string
	TargetRole      string
	Reason          string
	ExpectedOutcome string
	FailureID       *string
	Status          string
	CreatedAt       string
	AcceptedAt      *string
}

func (q *Queries) CreateAttemptHandoff(ctx context.Context, arg CreateAttemptHandoffParams) error {
	_, err := q.db.ExecContext(ctx, createAttemptHandoff,
		arg.ID,
		arg.SourceAttemptID,
		arg.TargetAttemptID,
		arg.SourceRole,
		arg.TargetRole,
		arg.Reason,
		arg.ExpectedOutcome,
		arg.FailureID,
		arg.Status,
		arg.CreatedAt,
		arg.AcceptedAt,
	)
	return err
}

const createCandidateFile = `-- name: CreateCandidateFile :exec
INSERT INTO candidate_files (
    id, candidate_id, path, content_blob, content_hash,
    byte_size, write_intent, ordinal
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateCandidateFileParams struct {
	ID          string
	CandidateID string
	Path        string
	ContentBlob string
	ContentHash string
	ByteSize    int64
	WriteIntent string
	Ordinal     int64
}

func (q *Queries) CreateCandidateFile(ctx context.Context, arg CreateCandidateFileParams) error {
	_, err := q.db.ExecContext(ctx, createCandidateFile,
		arg.ID,
		arg.CandidateID,
		arg.Path,
		arg.ContentBlob,
		arg.ContentHash,
		arg.ByteSize,
		arg.WriteIntent,
		arg.Ordinal,
	)
	return err
}

const createCandidateSet = `-- name: CreateCandidateSet :exec
INSERT INTO candidate_sets (
    id, execution_id, attempt_id, candidate_hash, status,
    disposition_reason, created_at, disposed_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateCandidateSetParams struct {
	ID                string
	ExecutionID       string
	AttemptID         string
	CandidateHash     string
	Status            string
	DispositionReason string
	CreatedAt         string
	DisposedAt        *string
}

func (q *Queries) CreateCandidateSet(ctx context.Context, arg CreateCandidateSetParams) error {
	_, err := q.db.ExecContext(ctx, createCandidateSet,
		arg.ID,
		arg.ExecutionID,
		arg.AttemptID,
		arg.CandidateHash,
		arg.Status,
		arg.DispositionReason,
		arg.CreatedAt,
		arg.DisposedAt,
	)
	return err
}

const createExecutionEvent = `-- name: CreateExecutionEvent :exec
INSERT INTO execution_events (
    id, execution_id, from_status, to_status, event_kind,
    details_json, details_hash, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateExecutionEventParams struct {
	ID          string
	ExecutionID string
	FromStatus  string
	ToStatus    string
	EventKind   string
	DetailsJson string
	DetailsHash string
	CreatedAt   string
}

func (q *Queries) CreateExecutionEvent(ctx context.Context, arg CreateExecutionEventParams) error {
	_, err := q.db.ExecContext(ctx, createExecutionEvent,
		arg.ID,
		arg.ExecutionID,
		arg.FromStatus,
		arg.ToStatus,
		arg.EventKind,
		arg.DetailsJson,
		arg.DetailsHash,
		arg.CreatedAt,
	)
	return err
}

const createExecutionManifest = `-- name: CreateExecutionManifest :exec
INSERT INTO execution_manifests (
    id, attempt_id, context_manifest_id, protocol_version, idempotency_key,
    plan_operation_id, role, role_policy_version, context_policy,
    host_name, host_version, provider, model,
    inference_config_json, inference_config_hash,
    agent_config_json, agent_config_hash,
    tool_permissions_json, tool_permissions_hash,
    template_hashes_json, template_hashes_hash,
    system_instructions_blob, context_hash, host_session_id,
    status, disposition_reason, started_at, completed_at,
    duration_ms, input_tokens, output_tokens, cost_usd, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateExecutionManifestParams struct {
	ID                     string
	AttemptID              string
	ContextManifestID      string
	ProtocolVersion        string
	IdempotencyKey         string
	PlanOperationID        string
	Role                   string
	RolePolicyVersion      string
	ContextPolicy          string
	HostName               string
	HostVersion            string
	Provider               string
	Model                  string
	InferenceConfigJson    string
	InferenceConfigHash    string
	AgentConfigJson        string
	AgentConfigHash        string
	ToolPermissionsJson    string
	ToolPermissionsHash    string
	TemplateHashesJson     string
	TemplateHashesHash     string
	SystemInstructionsBlob string
	ContextHash            string
	HostSessionID          string
	Status                 string
	DispositionReason      string
	StartedAt              string
	CompletedAt            *string
	DurationMs             int64
	InputTokens            int64
	OutputTokens           int64
	CostUsd                float64
	CreatedAt              string
	UpdatedAt              string
}

func (q *Queries) CreateExecutionManifest(ctx context.Context, arg CreateExecutionManifestParams) error {
	_, err := q.db.ExecContext(ctx, createExecutionManifest,
		arg.ID,
		arg.AttemptID,
		arg.ContextManifestID,
		arg.ProtocolVersion,
		arg.IdempotencyKey,
		arg.PlanOperationID,
		arg.Role,
		arg.RolePolicyVersion,
		arg.ContextPolicy,
		arg.HostName,
		arg.HostVersion,
		arg.Provider,
		arg.Model,
		arg.InferenceConfigJson,
		arg.InferenceConfigHash,
		arg.AgentConfigJson,
		arg.AgentConfigHash,
		arg.ToolPermissionsJson,
		arg.ToolPermissionsHash,
		arg.TemplateHashesJson,
		arg.TemplateHashesHash,
		arg.SystemInstructionsBlob,
		arg.ContextHash,
		arg.HostSessionID,
		arg.Status,
		arg.DispositionReason,
		arg.StartedAt,
		arg.CompletedAt,
		arg.DurationMs,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CostUsd,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createExecutionTool = `-- name: CreateExecutionTool :exec
INSERT INTO execution_tools (execution_id, name, permission, ordinal)
VALUES (?, ?, ?, ?)
`

type CreateExecutionToolParams struct {
	ExecutionID string
	Name        string
	Permission  string
	Ordinal     int64
}

func (q *Queries) CreateExecutionTool(ctx context.Context, arg CreateExecutionToolParams) error {
	_, err := q.db.ExecContext(ctx, createExecutionTool,
		arg.ExecutionID,
		arg.Name,
		arg.Permission,
		arg.Ordinal,
	)
	return err
}

const createFailureClassification = `-- name: CreateFailureClassification :exec
INSERT INTO failure_classifications (
    id, attempt_id, execution_id, resource_id, category, origin, confidence,
    evidence_source, evidence_reference, evidence_blob, corrective_action,
    next_role, blocks_retry, override_of, resolution, resolved_by_attempt,
    created_at, resolved_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateFailureClassificationParams struct {
	ID                string
	AttemptID         string
	ExecutionID       *string
	ResourceID        string
	Category          string
	Origin            string
	Confidence        float64
	EvidenceSource    string
	EvidenceReference string
	EvidenceBlob      *string
	CorrectiveAction  string
	NextRole          string
	BlocksRetry       int64
	OverrideOf        *string
	Resolution        string
	ResolvedByAttempt *string
	CreatedAt         string
	ResolvedAt        *string
}

func (q *Queries) CreateFailureClassification(ctx context.Context, arg CreateFailureClassificationParams) error {
	_, err := q.db.ExecContext(ctx, createFailureClassification,
		arg.ID,
		arg.AttemptID,
		arg.ExecutionID,
		arg.ResourceID,
		arg.Category,
		arg.Origin,
		arg.Confidence,
		arg.EvidenceSource,
		arg.EvidenceReference,
		arg.EvidenceBlob,
		arg.CorrectiveAction,
		arg.NextRole,
		arg.BlocksRetry,
		arg.OverrideOf,
		arg.Resolution,
		arg.ResolvedByAttempt,
		arg.CreatedAt,
		arg.ResolvedAt,
	)
	return err
}

const getAttemptHandoff = `-- name: GetAttemptHandoff :one
SELECT id, source_attempt_id, target_attempt_id, source_role, target_role, reason, expected_outcome, failure_id, status, created_at, accepted_at FROM attempt_handoffs WHERE id = ?
`

func (q *Queries) GetAttemptHandoff(ctx context.Context, id string) (AttemptHandoff, error) {
	row := q.db.QueryRowContext(ctx, getAttemptHandoff, id)
	var i AttemptHandoff
	err := row.Scan(
		&i.ID,
		&i.SourceAttemptID,
		&i.TargetAttemptID,
		&i.SourceRole,
		&i.TargetRole,
		&i.Reason,
		&i.ExpectedOutcome,
		&i.FailureID,
		&i.Status,
		&i.CreatedAt,
		&i.AcceptedAt,
	)
	return i, err
}

const getCandidateSet = `-- name: GetCandidateSet :one
SELECT id, execution_id, attempt_id, candidate_hash, status, disposition_reason, created_at, disposed_at FROM candidate_sets WHERE id = ?
`

func (q *Queries) GetCandidateSet(ctx context.Context, id string) (CandidateSet, error) {
	row := q.db.QueryRowContext(ctx, getCandidateSet, id)
	var i CandidateSet
	err := row.Scan(
		&i.ID,
		&i.ExecutionID,
		&i.AttemptID,
		&i.CandidateHash,
		&i.Status,
		&i.DispositionReason,
		&i.CreatedAt,
		&i.DisposedAt,
	)
	return i, err
}

const getCandidateSetByAttempt = `-- name: GetCandidateSetByAttempt :one
SELECT id, execution_id, attempt_id, candidate_hash, status, disposition_reason, created_at, disposed_at FROM candidate_sets WHERE attempt_id = ?
`

func (q *Queries) GetCandidateSetByAttempt(ctx context.Context, attemptID string) (CandidateSet, error) {
	row := q.db.QueryRowContext(ctx, getCandidateSetByAttempt, attemptID)
	var i CandidateSet
	err := row.Scan(
		&i.ID,
		&i.ExecutionID,
		&i.AttemptID,
		&i.CandidateHash,
		&i.Status,
		&i.DispositionReason,
		&i.CreatedAt,
		&i.DisposedAt,
	)
	return i, err
}

const getCandidateSetByExecution = `-- name: GetCandidateSetByExecution :one
SELECT id, execution_id, attempt_id, candidate_hash, status, disposition_reason, created_at, disposed_at FROM candidate_sets WHERE execution_id = ?
`

func (q *Queries) GetCandidateSetByExecution(ctx context.Context, executionID string) (CandidateSet, error) {
	row := q.db.QueryRowContext(ctx, getCandidateSetByExecution, executionID)
	var i CandidateSet
	err := row.Scan(
		&i.ID,
		&i.ExecutionID,
		&i.AttemptID,
		&i.CandidateHash,
		&i.Status,
		&i.DispositionReason,
		&i.CreatedAt,
		&i.DisposedAt,
	)
	return i, err
}

const getExecutionManifest = `-- name: GetExecutionManifest :one
SELECT id, attempt_id, context_manifest_id, protocol_version, idempotency_key, plan_operation_id, role, role_policy_version, context_policy, host_name, host_version, provider, model, inference_config_json, inference_config_hash, agent_config_json, agent_config_hash, tool_permissions_json, tool_permissions_hash, template_hashes_json, template_hashes_hash, system_instructions_blob, context_hash, host_session_id, status, disposition_reason, started_at, completed_at, duration_ms, input_tokens, output_tokens, cost_usd, created_at, updated_at FROM execution_manifests WHERE id = ?
`

func (q *Queries) GetExecutionManifest(ctx context.Context, id string) (ExecutionManifest, error) {
	row := q.db.QueryRowContext(ctx, getExecutionManifest, id)
	var i ExecutionManifest
	err := row.Scan(
		&i.ID,
		&i.AttemptID,
		&i.ContextManifestID,
		&i.ProtocolVersion,
		&i.IdempotencyKey,
		&i.PlanOperationID,
		&i.Role,
		&i.RolePolicyVersion,
		&i.ContextPolicy,
		&i.HostName,
		&i.HostVersion,
		&i.Provider,
		&i.Model,
		&i.InferenceConfigJson,
		&i.InferenceConfigHash,
		&i.AgentConfigJson,
		&i.AgentConfigHash,
		&i.ToolPermissionsJson,
		&i.ToolPermissionsHash,
		&i.TemplateHashesJson,
		&i.TemplateHashesHash,
		&i.SystemInstructionsBlob,
		&i.ContextHash,
		&i.HostSessionID,
		&i.Status,
		&i.DispositionReason,
		&i.StartedAt,
		&i.CompletedAt,
		&i.DurationMs,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CostUsd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExecutionManifestByAttempt = `-- name: GetExecutionManifestByAttempt :one
SELECT id, attempt_id, context_manifest_id, protocol_version, idempotency_key, plan_operation_id, role, role_policy_version, context_policy, host_name, host_version, provider, model, inference_config_json, inference_config_hash, agent_config_json, agent_config_hash, tool_permissions_json, tool_permissions_hash, template_hashes_json, template_hashes_hash, system_instructions_blob, context_hash, host_session_id, status, disposition_reason, started_at, completed_at, duration_ms, input_tokens, output_tokens, cost_usd, created_at, updated_at FROM execution_manifests WHERE attempt_id = ?
`

func (q *Queries) GetExecutionManifestByAttempt(ctx context.Context, attemptID string) (ExecutionManifest, error) {
	row := q.db.QueryRowContext(ctx, getExecutionManifestByAttempt, attemptID)
	var i ExecutionManifest
	err := row.Scan(
		&i.ID,
		&i.AttemptID,
		&i.ContextManifestID,
		&i.ProtocolVersion,
		&i.IdempotencyKey,
		&i.PlanOperationID,
		&i.Role,
		&i.RolePolicyVersion,
		&i.ContextPolicy,
		&i.HostName,
		&i.HostVersion,
		&i.Provider,
		&i.Model,
		&i.InferenceConfigJson,
		&i.InferenceConfigHash,
		&i.AgentConfigJson,
		&i.AgentConfigHash,
		&i.ToolPermissionsJson,
		&i.ToolPermissionsHash,
		&i.TemplateHashesJson,
		&i.TemplateHashesHash,
		&i.SystemInstructionsBlob,
		&i.ContextHash,
		&i.HostSessionID,
		&i.Status,
		&i.DispositionReason,
		&i.StartedAt,
		&i.CompletedAt,
		&i.DurationMs,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CostUsd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExecutionManifestByIdempotencyKey = `-- name: GetExecutionManifestByIdempotencyKey :one
SELECT id, attempt_id, context_manifest_id, protocol_version, idempotency_key, plan_operation_id, role, role_policy_version, context_policy, host_name, host_version, provider, model, inference_config_json, inference_config_hash, agent_config_json, agent_config_hash, tool_permissions_json, tool_permissions_hash, template_hashes_json, template_hashes_hash, system_instructions_blob, context_hash, host_session_id, status, disposition_reason, started_at, completed_at, duration_ms, input_tokens, output_tokens, cost_usd, created_at, updated_at FROM execution_manifests WHERE idempotency_key = ?
`

func (q *Queries) GetExecutionManifestByIdempotencyKey(ctx context.Context, idempotencyKey string) (ExecutionManifest, error) {
	row := q.db.QueryRowContext(ctx, getExecutionManifestByIdempotencyKey, idempotencyKey)
	var i ExecutionManifest
	err := row.Scan(
		&i.ID,
		&i.AttemptID,
		&i.ContextManifestID,
		&i.ProtocolVersion,
		&i.IdempotencyKey,
		&i.PlanOperationID,
		&i.Role,
		&i.RolePolicyVersion,
		&i.ContextPolicy,
		&i.HostName,
		&i.HostVersion,
		&i.Provider,
		&i.Model,
		&i.InferenceConfigJson,
		&i.InferenceConfigHash,
		&i.AgentConfigJson,
		&i.AgentConfigHash,
		&i.ToolPermissionsJson,
		&i.ToolPermissionsHash,
		&i.TemplateHashesJson,
		&i.TemplateHashesHash,
		&i.SystemInstructionsBlob,
		&i.ContextHash,
		&i.HostSessionID,
		&i.Status,
		&i.DispositionReason,
		&i.StartedAt,
		&i.CompletedAt,
		&i.DurationMs,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CostUsd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFailureClassification = `-- name: GetFailureClassification :one
SELECT id, attempt_id, execution_id, resource_id, category, origin, confidence, evidence_source, evidence_reference, evidence_blob, corrective_action, next_role, blocks_retry, override_of, resolution, resolved_by_attempt, created_at, resolved_at FROM failure_classifications WHERE id = ?
`

func (q *Queries) GetFailureClassification(ctx context.Context, id string) (FailureClassification, error) {
	row := q.db.QueryRowContext(ctx, getFailureClassification, id)
	var i FailureClassification
	err := row.Scan(
		&i.ID,
		&i.AttemptID,
		&i.ExecutionID,
		&i.ResourceID,
		&i.Category,
		&i.Origin,
		&i.Confidence,
		&i.EvidenceSource,
		&i.EvidenceReference,
		&i.EvidenceBlob,
		&i.CorrectiveAction,
		&i.NextRole,
		&i.BlocksRetry,
		&i.OverrideOf,
		&i.Resolution,
		&i.ResolvedByAttempt,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getLatestRejectedCandidateForResource = `-- name: GetLatestRejectedCandidateForResource :one
SELECT cs.id, cs.execution_id, cs.attempt_id, cs.candidate_hash, cs.status, cs.disposition_reason, cs.created_at, cs.disposed_at FROM candidate_sets cs
JOIN generation_attempts ga ON ga.id = cs.attempt_id
WHERE ga.session_id = ? AND ga.resource_id = ? AND cs.status = 'rejected'
ORDER BY cs.created_at DESC, cs.id DESC LIMIT 1
`

type GetLatestRejectedCandidateForResourceParams struct {
	SessionID  string
	ResourceID string
}

func (q *Queries) GetLatestRejectedCandidateForResource(ctx context.Context, arg GetLatestRejectedCandidateForResourceParams) (CandidateSet, error) {
	row := q.db.QueryRowContext(ctx, getLatestRejectedCandidateForResource, arg.SessionID, arg.ResourceID)
	var i CandidateSet
	err := row.Scan(
		&i.ID,
		&i.ExecutionID,
		&i.AttemptID,
		&i.CandidateHash,
		&i.Status,
		&i.DispositionReason,
		&i.CreatedAt,
		&i.DisposedAt,
	)
	return i, err
}

const listAttemptHandoffsBySource = `-- name: ListAttemptHandoffsBySource :many
SELECT id, source_attempt_id, target_attempt_id, source_role, target_role, reason, expected_outcome, failure_id, status, created_at, accepted_at FROM attempt_handoffs
WHERE source_attempt_id = ? ORDER BY created_at, id
`

func (q *Queries) ListAttemptHandoffsBySource(ctx context.Context, sourceAttemptID string) ([]AttemptHandoff, error) {
	rows, err := q.db.QueryContext(ctx, listAttemptHandoffsBySource, sourceAttemptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AttemptHandoff
	for rows.Next() {
		var i AttemptHandoff
		if err := rows.Scan(
			&i.ID,
			&i.SourceAttemptID,
			&i.TargetAttemptID,
			&i.SourceRole,
			&i.TargetRole,
			&i.Reason,
			&i.ExpectedOutcome,
			&i.FailureID,
			&i.Status,
			&i.CreatedAt,
			&i.AcceptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCandidateFiles = `-- name: ListCandidateFiles :many
SELECT id, candidate_id, path, content_blob, content_hash, byte_size, write_intent, ordinal FROM candidate_files WHERE candidate_id = ? ORDER BY ordinal, path
`

func (q *Queries) ListCandidateFiles(ctx context.Context, candidateID string) ([]CandidateFile, error) {
	rows, err := q.db.QueryContext(ctx, listCandidateFiles, candidateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CandidateFile
	for rows.Next() {
		var i CandidateFile
		if err := rows.Scan(
			&i.ID,
			&i.CandidateID,
			&i.Path,
			&i.ContentBlob,
			&i.ContentHash,
			&i.ByteSize,
			&i.WriteIntent,
			&i.Ordinal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExecutionEvents = `-- name: ListExecutionEvents :many
SELECT id, execution_id, from_status, to_status, event_kind, details_json, details_hash, created_at FROM execution_events WHERE execution_id = ? ORDER BY created_at, id
`

func (q *Queries) ListExecutionEvents(ctx context.Context, executionID string) ([]ExecutionEvent, error) {
	rows, err := q.db.QueryContext(ctx, listExecutionEvents, executionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExecutionEvent
	for rows.Next() {
		var i ExecutionEvent
		if err := rows.Scan(
			&i.ID,
			&i.ExecutionID,
			&i.FromStatus,
			&i.ToStatus,
			&i.EventKind,
			&i.DetailsJson,
			&i.DetailsHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExecutionTools = `-- name: ListExecutionTools :many
SELECT execution_id, name, permission, ordinal FROM execution_tools WHERE execution_id = ? ORDER BY ordinal, name
`

func (q *Queries) ListExecutionTools(ctx context.Context, executionID string) ([]ExecutionTool, error) {
	rows, err := q.db.QueryContext(ctx, listExecutionTools, executionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExecutionTool
	for rows.Next() {
		var i ExecutionTool
		if err := rows.Scan(
			&i.ExecutionID,
			&i.Name,
			&i.Permission,
			&i.Ordinal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFailureClassificationsByAttempt = `-- name: ListFailureClassificationsByAttempt :many
SELECT id, attempt_id, execution_id, resource_id, category, origin, confidence, evidence_source, evidence_reference, evidence_blob, corrective_action, next_role, blocks_retry, override_of, resolution, resolved_by_attempt, created_at, resolved_at FROM failure_classifications
WHERE attempt_id = ? ORDER BY created_at, id
`

func (q *Queries) ListFailureClassificationsByAttempt(ctx context.Context, attemptID string) ([]FailureClassification, error) {
	rows, err := q.db.QueryContext(ctx, listFailureClassificationsByAttempt, attemptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FailureClassification
	for rows.Next() {
		var i FailureClassification
		if err := rows.Scan(
			&i.ID,
			&i.AttemptID,
			&i.ExecutionID,
			&i.ResourceID,
			&i.Category,
			&i.Origin,
			&i.Confidence,
			&i.EvidenceSource,
			&i.EvidenceReference,
			&i.EvidenceBlob,
			&i.CorrectiveAction,
			&i.NextRole,
			&i.BlocksRetry,
			&i.OverrideOf,
			&i.Resolution,
			&i.ResolvedByAttempt,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFailureGoals = `-- name: ListFailureGoals :many
SELECT goal_id FROM failure_goals WHERE failure_id = ? ORDER BY goal_id
`

func (q *Queries) ListFailureGoals(ctx context.Context, failureID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listFailureGoals, failureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var goal_id string
		if err := rows.Scan(&goal_id); err != nil {
			return nil, err
		}
		items = append(items, goal_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingAttemptHandoffs = `-- name: ListPendingAttemptHandoffs :many
SELECT id, source_attempt_id, target_attempt_id, source_role, target_role, reason, expected_outcome, failure_id, status, created_at, accepted_at FROM attempt_handoffs
WHERE status = 'pending' ORDER BY created_at, id LIMIT ?
`

func (q *Queries) ListPendingAttemptHandoffs(ctx context.Context, limit int64) ([]AttemptHandoff, error) {
	rows, err := q.db.QueryContext(ctx, listPendingAttemptHandoffs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AttemptHandoff
	for rows.Next() {
		var i AttemptHandoff
		if err := rows.Scan(
			&i.ID,
			&i.SourceAttemptID,
			&i.TargetAttemptID,
			&i.SourceRole,
			&i.TargetRole,
			&i.Reason,
			&i.ExpectedOutcome,
			&i.FailureID,
			&i.Status,
			&i.CreatedAt,
			&i.AcceptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentExecutionManifests = `-- name: ListRecentExecutionManifests :many
SELECT id, attempt_id, context_manifest_id, protocol_version, idempotency_key, plan_operation_id, role, role_policy_version, context_policy, host_name, host_version, provider, model, inference_config_json, inference_config_hash, agent_config_json, agent_config_hash, tool_permissions_json, tool_permissions_hash, template_hashes_json, template_hashes_hash, system_instructions_blob, context_hash, host_session_id, status, disposition_reason, started_at, completed_at, duration_ms, input_tokens, output_tokens, cost_usd, created_at, updated_at FROM execution_manifests ORDER BY created_at DESC, id DESC LIMIT ?
`

func (q *Queries) ListRecentExecutionManifests(ctx context.Context, limit int64) ([]ExecutionManifest, error) {
	rows, err := q.db.QueryContext(ctx, listRecentExecutionManifests, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExecutionManifest
	for rows.Next() {
		var i ExecutionManifest
		if err := rows.Scan(
			&i.ID,
			&i.AttemptID,
			&i.ContextManifestID,
			&i.ProtocolVersion,
			&i.IdempotencyKey,
			&i.PlanOperationID,
			&i.Role,
			&i.RolePolicyVersion,
			&i.ContextPolicy,
			&i.HostName,
			&i.HostVersion,
			&i.Provider,
			&i.Model,
			&i.InferenceConfigJson,
			&i.InferenceConfigHash,
			&i.AgentConfigJson,
			&i.AgentConfigHash,
			&i.ToolPermissionsJson,
			&i.ToolPermissionsHash,
			&i.TemplateHashesJson,
			&i.TemplateHashesHash,
			&i.SystemInstructionsBlob,
			&i.ContextHash,
			&i.HostSessionID,
			&i.Status,
			&i.DispositionReason,
			&i.StartedAt,
			&i.CompletedAt,
			&i.DurationMs,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CostUsd,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentFailureClassifications = `-- name: ListRecentFailureClassifications :many
SELECT id, attempt_id, execution_id, resource_id, category, origin, confidence, evidence_source, evidence_reference, evidence_blob, corrective_action, next_role, blocks_retry, override_of, resolution, resolved_by_attempt, created_at, resolved_at FROM failure_classifications
ORDER BY created_at DESC, id DESC LIMIT ?
`

func (q *Queries) ListRecentFailureClassifications(ctx context.Context, limit int64) ([]FailureClassification, error) {
	rows, err := q.db.QueryContext(ctx, listRecentFailureClassifications, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FailureClassification
	for rows.Next() {
		var i FailureClassification
		if err := rows.Scan(
			&i.ID,
			&i.AttemptID,
			&i.ExecutionID,
			&i.ResourceID,
			&i.Category,
			&i.Origin,
			&i.Confidence,
			&i.EvidenceSource,
			&i.EvidenceReference,
			&i.EvidenceBlob,
			&i.CorrectiveAction,
			&i.NextRole,
			&i.BlocksRetry,
			&i.OverrideOf,
			&i.Resolution,
			&i.ResolvedByAttempt,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveFailureClassification = `-- name: ResolveFailureClassification :execrows
UPDATE failure_classifications
SET resolution = ?, resolved_by_attempt = ?, resolved_at = ?
WHERE id = ? AND resolved_at IS NULL
`

type ResolveFailureClassificationParams struct {
	Resolution        string
	ResolvedByAttempt *string
	ResolvedAt        *string
	ID                string
}

func (q *Queries) ResolveFailureClassification(ctx context.Context, arg ResolveFailureClassificationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, resolveFailureClassification,
		arg.Resolution,
		arg.ResolvedByAttempt,
		arg.ResolvedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateCandidateSetDisposition = `-- name: UpdateCandidateSetDisposition :execrows
UPDATE candidate_sets
SET status = ?, disposition_reason = ?, disposed_at = ?
WHERE id = ? AND status = 'submitted'
`

type UpdateCandidateSetDispositionParams struct {
	Status            string
	DispositionReason string
	DisposedAt        *string
	ID                string
}

func (q *Queries) UpdateCandidateSetDisposition(ctx context.Context, arg UpdateCandidateSetDispositionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateCandidateSetDisposition,
		arg.Status,
		arg.DispositionReason,
		arg.DisposedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateExecutionManifestStatus = `-- name: UpdateExecutionManifestStatus :execrows
UPDATE execution_manifests
SET status = ?, disposition_reason = ?, completed_at = ?, duration_ms = ?,
    input_tokens = ?, output_tokens = ?, cost_usd = ?, updated_at = ?
WHERE id = ? AND status = ?
`

type UpdateExecutionManifestStatusParams struct {
	Status            string
	DispositionReason string
	CompletedAt       *string
	DurationMs        int64
	InputTokens       int64
	OutputTokens      int64
	CostUsd           float64
	UpdatedAt         string
	ID                string
	Status_2          string
}

func (q *Queries) UpdateExecutionManifestStatus(ctx context.Context, arg UpdateExecutionManifestStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateExecutionManifestStatus,
		arg.Status,
		arg.DispositionReason,
		arg.CompletedAt,
		arg.DurationMs,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CostUsd,
		arg.UpdatedAt,
		arg.ID,
		arg.Status_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateGenerationAttemptStatus = `-- name: UpdateGenerationAttemptStatus :execrows
UPDATE generation_attempts SET status = ? WHERE id = ? AND status = ?
`

type UpdateGenerationAttemptStatusParams struct {
	Status   string
	ID       string
	Status_2 string
}

func (q *Queries) UpdateGenerationAttemptStatus(ctx context.Context, arg UpdateGenerationAttemptStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateGenerationAttemptStatus, arg.Status, arg.ID, arg.Status_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
