// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: generations.sql

package db

import (
	"context"
)

const createGeneration = `-- name: CreateGeneration :exec
INSERT INTO generations (id, apply_id, resource_id, prompt_text, prompt_hash, model, retry_count, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateGenerationParams struct {
	ID         string
	ApplyID    *string
	ResourceID string
	PromptText string
	PromptHash string
	Model      string
	RetryCount int64
	CreatedAt  string
}

func (q *Queries) CreateGeneration(ctx context.Context, arg CreateGenerationParams) error {
	_, err := q.db.ExecContext(ctx, createGeneration,
		arg.ID,
		arg.ApplyID,
		arg.ResourceID,
		arg.PromptText,
		arg.PromptHash,
		arg.Model,
		arg.RetryCount,
		arg.CreatedAt,
	)
	return err
}

const getGeneration = `-- name: GetGeneration :one
SELECT id, apply_id, resource_id, prompt_text, prompt_hash, output_text, model, outcome, rejection_reason, retry_count, duration_ms, input_tokens, output_tokens, cost_usd, created_at FROM generations WHERE id = ?
`

func (q *Queries) GetGeneration(ctx context.Context, id string) (Generation, error) {
	row := q.db.QueryRowContext(ctx, getGeneration, id)
	var i Generation
	err := row.Scan(
		&i.ID,
		&i.ApplyID,
		&i.ResourceID,
		&i.PromptText,
		&i.PromptHash,
		&i.OutputText,
		&i.Model,
		&i.Outcome,
		&i.RejectionReason,
		&i.RetryCount,
		&i.DurationMs,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CostUsd,
		&i.CreatedAt,
	)
	return i, err
}

const listGenerations = `-- name: ListGenerations :many
SELECT id, apply_id, resource_id, prompt_text, prompt_hash, output_text, model, outcome, rejection_reason, retry_count, duration_ms, input_tokens, output_tokens, cost_usd, created_at FROM generations WHERE resource_id = ?
ORDER BY created_at DESC LIMIT ?
`

type ListGenerationsParams struct {
	ResourceID string
	Limit      int64
}

func (q *Queries) ListGenerations(ctx context.Context, arg ListGenerationsParams) ([]Generation, error) {
	rows, err := q.db.QueryContext(ctx, listGenerations, arg.ResourceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Generation
	for rows.Next() {
		var i Generation
		if err := rows.Scan(
			&i.ID,
			&i.ApplyID,
			&i.ResourceID,
			&i.PromptText,
			&i.PromptHash,
			&i.OutputText,
			&i.Model,
			&i.Outcome,
			&i.RejectionReason,
			&i.RetryCount,
			&i.DurationMs,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CostUsd,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGeneration = `-- name: UpdateGeneration :exec
UPDATE generations SET output_text = ?, outcome = ?, rejection_reason = ?,
    duration_ms = ?, input_tokens = ?, output_tokens = ?, cost_usd = ?
WHERE id = ?
`

type UpdateGenerationParams struct {
	OutputText      *string
	Outcome         *string
	RejectionReason *string
	DurationMs      *int64
	InputTokens     *int64
	OutputTokens    *int64
	CostUsd         *float64
	ID              string
}

func (q *Queries) UpdateGeneration(ctx context.Context, arg UpdateGenerationParams) error {
	_, err := q.db.ExecContext(ctx, updateGeneration,
		arg.OutputText,
		arg.Outcome,
		arg.RejectionReason,
		arg.DurationMs,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CostUsd,
		arg.ID,
	)
	return err
}
