// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: goals.sql

package db

import (
	"context"
)

const clearAcceptanceEvidence = `-- name: ClearAcceptanceEvidence :exec
DELETE FROM acceptance_evidence WHERE scenario_id IN (
    SELECT acceptance_scenarios.id FROM acceptance_scenarios
    JOIN project_capabilities ON project_capabilities.id = acceptance_scenarios.capability_id
    WHERE project_capabilities.project_name = ?
)
`

func (q *Queries) ClearAcceptanceEvidence(ctx context.Context, projectName string) error {
	_, err := q.db.ExecContext(ctx, clearAcceptanceEvidence, projectName)
	return err
}

const clearAcceptanceSteps = `-- name: ClearAcceptanceSteps :exec
DELETE FROM acceptance_steps WHERE scenario_id IN (
    SELECT acceptance_scenarios.id FROM acceptance_scenarios
    JOIN project_capabilities ON project_capabilities.id = acceptance_scenarios.capability_id
    WHERE project_capabilities.project_name = ?
)
`

func (q *Queries) ClearAcceptanceSteps(ctx context.Context, projectName string) error {
	_, err := q.db.ExecContext(ctx, clearAcceptanceSteps, projectName)
	return err
}

const clearCapabilityGoals = `-- name: ClearCapabilityGoals :exec
DELETE FROM capability_goals WHERE capability_id IN (
    SELECT id FROM project_capabilities WHERE project_name = ?
)
`

func (q *Queries) ClearCapabilityGoals(ctx context.Context, projectName string) error {
	_, err := q.db.ExecContext(ctx, clearCapabilityGoals, projectName)
	return err
}

const clearGoalDependencies = `-- name: ClearGoalDependencies :exec
DELETE FROM goal_dependencies WHERE goal_id IN (
    SELECT id FROM project_goals WHERE project_name = ?
)
`

func (q *Queries) ClearGoalDependencies(ctx context.Context, projectName string) error {
	_, err := q.db.ExecContext(ctx, clearGoalDependencies, projectName)
	return err
}

const clearGoalIntentRelationships = `-- name: ClearGoalIntentRelationships :exec
DELETE FROM goal_actors WHERE goal_id IN (
    SELECT id FROM project_goals WHERE project_name = ?
)
`

func (q *Queries) ClearGoalIntentRelationships(ctx context.Context, projectName string) error {
	_, err := q.db.ExecContext(ctx, clearGoalIntentRelationships, projectName)
	return err
}

const clearProjectRequiredGoals = `-- name: ClearProjectRequiredGoals :exec
DELETE FROM project_required_goals WHERE project_name = ?
`

func (q *Queries) ClearProjectRequiredGoals(ctx context.Context, projectName string) error {
	_, err := q.db.ExecContext(ctx, clearProjectRequiredGoals, projectName)
	return err
}

const clearRequirementCapabilities = `-- name: ClearRequirementCapabilities :exec
DELETE FROM requirement_capabilities WHERE requirement_id IN (
    SELECT id FROM project_requirements WHERE project_name = ?
)
`

func (q *Queries) ClearRequirementCapabilities(ctx context.Context, projectName string) error {
	_, err := q.db.ExecContext(ctx, clearRequirementCapabilities, projectName)
	return err
}

const clearRequirementGoals = `-- name: ClearRequirementGoals :exec
DELETE FROM requirement_goals WHERE requirement_id IN (
    SELECT id FROM project_requirements WHERE project_name = ?
)
`

func (q *Queries) ClearRequirementGoals(ctx context.Context, projectName string) error {
	_, err := q.db.ExecContext(ctx, clearRequirementGoals, projectName)
	return err
}

const deactivateAcceptanceScenarios = `-- name: DeactivateAcceptanceScenarios :exec
UPDATE acceptance_scenarios SET active = 0, updated_at = ?
WHERE capability_id IN (
    SELECT id FROM project_capabilities WHERE project_name = ?
)
`

type DeactivateAcceptanceScenariosParams struct {
	UpdatedAt   string
	ProjectName string
}

func (q *Queries) DeactivateAcceptanceScenarios(ctx context.Context, arg DeactivateAcceptanceScenariosParams) error {
	_, err := q.db.ExecContext(ctx, deactivateAcceptanceScenarios, arg.UpdatedAt, arg.ProjectName)
	return err
}

const deactivateEvidenceRequirements = `-- name: DeactivateEvidenceRequirements :exec
UPDATE evidence_requirements SET active = 0, updated_at = ? WHERE project_name = ?
`

type DeactivateEvidenceRequirementsParams struct {
	UpdatedAt   string
	ProjectName string
}

func (q *Queries) DeactivateEvidenceRequirements(ctx context.Context, arg DeactivateEvidenceRequirementsParams) error {
	_, err := q.db.ExecContext(ctx, deactivateEvidenceRequirements, arg.UpdatedAt, arg.ProjectName)
	return err
}

const deactivateProjectActors = `-- name: DeactivateProjectActors :exec
UPDATE project_actors SET active = 0, updated_at = ? WHERE project_name = ?
`

type DeactivateProjectActorsParams struct {
	UpdatedAt   string
	ProjectName string
}

func (q *Queries) DeactivateProjectActors(ctx context.Context, arg DeactivateProjectActorsParams) error {
	_, err := q.db.ExecContext(ctx, deactivateProjectActors, arg.UpdatedAt, arg.ProjectName)
	return err
}

const deactivateProjectCapabilities = `-- name: DeactivateProjectCapabilities :exec
UPDATE project_capabilities SET active = 0, updated_at = ? WHERE project_name = ?
`

type DeactivateProjectCapabilitiesParams struct {
	UpdatedAt   string
	ProjectName string
}

func (q *Queries) DeactivateProjectCapabilities(ctx context.Context, arg DeactivateProjectCapabilitiesParams) error {
	_, err := q.db.ExecContext(ctx, deactivateProjectCapabilities, arg.UpdatedAt, arg.ProjectName)
	return err
}

const deactivateProjectGoals = `-- name: DeactivateProjectGoals :exec
UPDATE project_goals SET active = 0, updated_at = ? WHERE project_name = ?
`

type DeactivateProjectGoalsParams struct {
	UpdatedAt   string
	ProjectName string
}

func (q *Queries) DeactivateProjectGoals(ctx context.Context, arg DeactivateProjectGoalsParams) error {
	_, err := q.db.ExecContext(ctx, deactivateProjectGoals, arg.UpdatedAt, arg.ProjectName)
	return err
}

const deactivateProjectNonGoals = `-- name: DeactivateProjectNonGoals :exec
UPDATE project_non_goals SET active = 0, updated_at = ? WHERE project_name = ?
`

type DeactivateProjectNonGoalsParams struct {
	UpdatedAt   string
	ProjectName string
}

func (q *Queries) DeactivateProjectNonGoals(ctx context.Context, arg DeactivateProjectNonGoalsParams) error {
	_, err := q.db.ExecContext(ctx, deactivateProjectNonGoals, arg.UpdatedAt, arg.ProjectName)
	return err
}

const deactivateProjectRequirements = `-- name: DeactivateProjectRequirements :exec
UPDATE project_requirements SET active = 0, updated_at = ? WHERE project_name = ?
`

type DeactivateProjectRequirementsParams struct {
	UpdatedAt   string
	ProjectName string
}

func (q *Queries) DeactivateProjectRequirements(ctx context.Context, arg DeactivateProjectRequirementsParams) error {
	_, err := q.db.ExecContext(ctx, deactivateProjectRequirements, arg.UpdatedAt, arg.ProjectName)
	return err
}

const getProjectGoal = `-- name: GetProjectGoal :one
SELECT id, project_name, description, priority, status, status_reason, spec_hash, active, created_at, updated_at FROM project_goals WHERE id = ?
`

func (q *Queries) GetProjectGoal(ctx context.Context, id string) (ProjectGoal, error) {
	row := q.db.QueryRowContext(ctx, getProjectGoal, id)
	var i ProjectGoal
	err := row.Scan(
		&i.ID,
		&i.ProjectName,
		&i.Description,
		&i.Priority,
		&i.Status,
		&i.StatusReason,
		&i.SpecHash,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectState = `-- name: GetProjectState :one
SELECT project_name, mission, spec_hash, completion_status, active, created_at, updated_at, completion_reason FROM project_state WHERE project_name = ?
`

func (q *Queries) GetProjectState(ctx context.Context, projectName string) (ProjectState, error) {
	row := q.db.QueryRowContext(ctx, getProjectState, projectName)
	var i ProjectState
	err := row.Scan(
		&i.ProjectName,
		&i.Mission,
		&i.SpecHash,
		&i.CompletionStatus,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletionReason,
	)
	return i, err
}

const insertAcceptanceEvidence = `-- name: InsertAcceptanceEvidence :exec
INSERT INTO acceptance_evidence (scenario_id, evidence_id) VALUES (?, ?)
`

type InsertAcceptanceEvidenceParams struct {
	ScenarioID string
	EvidenceID string
}

func (q *Queries) InsertAcceptanceEvidence(ctx context.Context, arg InsertAcceptanceEvidenceParams) error {
	_, err := q.db.ExecContext(ctx, insertAcceptanceEvidence, arg.ScenarioID, arg.EvidenceID)
	return err
}

const insertAcceptanceStep = `-- name: InsertAcceptanceStep :exec
INSERT INTO acceptance_steps (scenario_id, ordinal, action, observes) VALUES (?, ?, ?, ?)
`

type InsertAcceptanceStepParams struct {
	ScenarioID string
	Ordinal    int64
	Action     string
	Observes   string
}

func (q *Queries) InsertAcceptanceStep(ctx context.Context, arg InsertAcceptanceStepParams) error {
	_, err := q.db.ExecContext(ctx, insertAcceptanceStep,
		arg.ScenarioID,
		arg.Ordinal,
		arg.Action,
		arg.Observes,
	)
	return err
}

const insertCapabilityGoal = `-- name: InsertCapabilityGoal :exec
INSERT INTO capability_goals (capability_id, goal_id) VALUES (?, ?)
`

type InsertCapabilityGoalParams struct {
	CapabilityID string
	GoalID       string
}

func (q *Queries) InsertCapabilityGoal(ctx context.Context, arg InsertCapabilityGoalParams) error {
	_, err := q.db.ExecContext(ctx, insertCapabilityGoal, arg.CapabilityID, arg.GoalID)
	return err
}

const insertGoalActor = `-- name: InsertGoalActor :exec
INSERT INTO goal_actors (goal_id, actor_id) VALUES (?, ?)
`

type InsertGoalActorParams struct {
	GoalID  string
	ActorID string
}

func (q *Queries) InsertGoalActor(ctx context.Context, arg InsertGoalActorParams) error {
	_, err := q.db.ExecContext(ctx, insertGoalActor, arg.GoalID, arg.ActorID)
	return err
}

const insertGoalDependency = `-- name: InsertGoalDependency :exec
INSERT INTO goal_dependencies (goal_id, dependency_goal_id) VALUES (?, ?)
`

type InsertGoalDependencyParams struct {
	GoalID           string
	DependencyGoalID string
}

func (q *Queries) InsertGoalDependency(ctx context.Context, arg InsertGoalDependencyParams) error {
	_, err := q.db.ExecContext(ctx, insertGoalDependency, arg.GoalID, arg.DependencyGoalID)
	return err
}

const insertGoalStatusHistory = `-- name: InsertGoalStatusHistory :exec
INSERT INTO goal_status_history (
    id, goal_id, from_status, to_status, reason,
    source_type, source_id, session_id, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertGoalStatusHistoryParams struct {
	ID         string
	GoalID     string
	FromStatus string
	ToStatus   string
	Reason     string
	SourceType string
	SourceID   string
	SessionID  *string
	CreatedAt  string
}

func (q *Queries) InsertGoalStatusHistory(ctx context.Context, arg InsertGoalStatusHistoryParams) error {
	_, err := q.db.ExecContext(ctx, insertGoalStatusHistory,
		arg.ID,
		arg.GoalID,
		arg.FromStatus,
		arg.ToStatus,
		arg.Reason,
		arg.SourceType,
		arg.SourceID,
		arg.SessionID,
		arg.CreatedAt,
	)
	return err
}

const insertProjectRequiredGoal = `-- name: InsertProjectRequiredGoal :exec
INSERT INTO project_required_goals (project_name, goal_id, ordinal) VALUES (?, ?, ?)
`

type InsertProjectRequiredGoalParams struct {
	ProjectName string
	GoalID      string
	Ordinal     int64
}

func (q *Queries) InsertProjectRequiredGoal(ctx context.Context, arg InsertProjectRequiredGoalParams) error {
	_, err := q.db.ExecContext(ctx, insertProjectRequiredGoal, arg.ProjectName, arg.GoalID, arg.Ordinal)
	return err
}

const insertProjectStatusHistory = `-- name: InsertProjectStatusHistory :exec
INSERT INTO project_status_history (
    id, project_name, from_status, to_status, reason,
    source_type, source_id, session_id, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertProjectStatusHistoryParams struct {
	ID          string
	ProjectName string
	FromStatus  string
	ToStatus    string
	Reason      string
	SourceType  string
	SourceID    string
	SessionID   *string
	CreatedAt   string
}

func (q *Queries) InsertProjectStatusHistory(ctx context.Context, arg InsertProjectStatusHistoryParams) error {
	_, err := q.db.ExecContext(ctx, insertProjectStatusHistory,
		arg.ID,
		arg.ProjectName,
		arg.FromStatus,
		arg.ToStatus,
		arg.Reason,
		arg.SourceType,
		arg.SourceID,
		arg.SessionID,
		arg.CreatedAt,
	)
	return err
}

const insertRequirementCapability = `-- name: InsertRequirementCapability :exec
INSERT INTO requirement_capabilities (requirement_id, capability_id) VALUES (?, ?)
`

type InsertRequirementCapabilityParams struct {
	RequirementID string
	CapabilityID  string
}

func (q *Queries) InsertRequirementCapability(ctx context.Context, arg InsertRequirementCapabilityParams) error {
	_, err := q.db.ExecContext(ctx, insertRequirementCapability, arg.RequirementID, arg.CapabilityID)
	return err
}

const insertRequirementGoal = `-- name: InsertRequirementGoal :exec
INSERT INTO requirement_goals (requirement_id, goal_id) VALUES (?, ?)
`

type InsertRequirementGoalParams struct {
	RequirementID string
	GoalID        string
}

func (q *Queries) InsertRequirementGoal(ctx context.Context, arg InsertRequirementGoalParams) error {
	_, err := q.db.ExecContext(ctx, insertRequirementGoal, arg.RequirementID, arg.GoalID)
	return err
}

const listAcceptanceEvidence = `-- name: ListAcceptanceEvidence :many
SELECT acceptance_evidence.scenario_id, acceptance_evidence.evidence_id FROM acceptance_evidence
JOIN acceptance_scenarios ON acceptance_scenarios.id = acceptance_evidence.scenario_id
JOIN project_capabilities ON project_capabilities.id = acceptance_scenarios.capability_id
WHERE project_capabilities.project_name = ?
ORDER BY acceptance_evidence.scenario_id, acceptance_evidence.evidence_id
`

func (q *Queries) ListAcceptanceEvidence(ctx context.Context, projectName string) ([]AcceptanceEvidence, error) {
	rows, err := q.db.QueryContext(ctx, listAcceptanceEvidence, projectName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AcceptanceEvidence
	for rows.Next() {
		var i AcceptanceEvidence
		if err := rows.Scan(&i.ScenarioID, &i.EvidenceID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAcceptanceScenarios = `-- name: ListAcceptanceScenarios :many
SELECT acceptance_scenarios.id, acceptance_scenarios.capability_id, acceptance_scenarios.actor_id, acceptance_scenarios.description, acceptance_scenarios.ordinal, acceptance_scenarios.spec_hash, acceptance_scenarios.active, acceptance_scenarios.updated_at FROM acceptance_scenarios
JOIN project_capabilities ON project_capabilities.id = acceptance_scenarios.capability_id
WHERE project_capabilities.project_name = ? AND acceptance_scenarios.active = 1
ORDER BY acceptance_scenarios.capability_id, acceptance_scenarios.ordinal, acceptance_scenarios.id
`

func (q *Queries) ListAcceptanceScenarios(ctx context.Context, projectName string) ([]AcceptanceScenario, error) {
	rows, err := q.db.QueryContext(ctx, listAcceptanceScenarios, projectName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AcceptanceScenario
	for rows.Next() {
		var i AcceptanceScenario
		if err := rows.Scan(
			&i.ID,
			&i.CapabilityID,
			&i.ActorID,
			&i.Description,
			&i.Ordinal,
			&i.SpecHash,
			&i.Active,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAcceptanceSteps = `-- name: ListAcceptanceSteps :many
SELECT acceptance_steps.scenario_id, acceptance_steps.ordinal, acceptance_steps."action", acceptance_steps.observes FROM acceptance_steps
JOIN acceptance_scenarios ON acceptance_scenarios.id = acceptance_steps.scenario_id
JOIN project_capabilities ON project_capabilities.id = acceptance_scenarios.capability_id
WHERE project_capabilities.project_name = ?
ORDER BY acceptance_steps.scenario_id, acceptance_steps.ordinal
`

func (q *Queries) ListAcceptanceSteps(ctx context.Context, projectName string) ([]AcceptanceStep, error) {
	rows, err := q.db.QueryContext(ctx, listAcceptanceSteps, projectName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AcceptanceStep
	for rows.Next() {
		var i AcceptanceStep
		if err := rows.Scan(
			&i.ScenarioID,
			&i.Ordinal,
			&i.Action,
			&i.Observes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCapabilityGoals = `-- name: ListCapabilityGoals :many
SELECT capability_goals.capability_id, capability_goals.goal_id FROM capability_goals
JOIN project_capabilities ON project_capabilities.id = capability_goals.capability_id
WHERE project_capabilities.project_name = ?
ORDER BY capability_goals.capability_id, capability_goals.goal_id
`

func (q *Queries) ListCapabilityGoals(ctx context.Context, projectName string) ([]CapabilityGoal, error) {
	rows, err := q.db.QueryContext(ctx, listCapabilityGoals, projectName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CapabilityGoal
	for rows.Next() {
		var i CapabilityGoal
		if err := rows.Scan(&i.CapabilityID, &i.GoalID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompletionBlockers = `-- name: ListCompletionBlockers :many
SELECT id, project_name, goal_id, category, reason, source_type, source_id, resolved, resolution, created_at, resolved_at FROM completion_blockers
WHERE project_name = ? AND resolved = 0
ORDER BY goal_id, category, created_at, id
`

func (q *Queries) ListCompletionBlockers(ctx context.Context, projectName string) ([]CompletionBlocker, error) {
	rows, err := q.db.QueryContext(ctx, listCompletionBlockers, projectName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompletionBlocker
	for rows.Next() {
		var i CompletionBlocker
		if err := rows.Scan(
			&i.ID,
			&i.ProjectName,
			&i.GoalID,
			&i.Category,
			&i.Reason,
			&i.SourceType,
			&i.SourceID,
			&i.Resolved,
			&i.Resolution,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvidenceRequirements = `-- name: ListEvidenceRequirements :many
SELECT id, project_name, kind, description, spec_hash, active, updated_at FROM evidence_requirements
WHERE project_name = ? AND active = 1 ORDER BY id
`

func (q *Queries) ListEvidenceRequirements(ctx context.Context, projectName string) ([]EvidenceRequirement, error) {
	rows, err := q.db.QueryContext(ctx, listEvidenceRequirements, projectName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EvidenceRequirement
	for rows.Next() {
		var i EvidenceRequirement
		if err := rows.Scan(
			&i.ID,
			&i.ProjectName,
			&i.Kind,
			&i.Description,
			&i.SpecHash,
			&i.Active,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoalActors = `-- name: ListGoalActors :many
SELECT goal_actors.goal_id, goal_actors.actor_id FROM goal_actors
JOIN project_goals ON project_goals.id = goal_actors.goal_id
WHERE project_goals.project_name = ?
ORDER BY goal_actors.goal_id, goal_actors.actor_id
`

func (q *Queries) ListGoalActors(ctx context.Context, projectName string) ([]GoalActor, error) {
	rows, err := q.db.QueryContext(ctx, listGoalActors, projectName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GoalActor
	for rows.Next() {
		var i GoalActor
		if err := rows.Scan(&i.GoalID, &i.ActorID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoalDependencies = `-- name: ListGoalDependencies :many
SELECT goal_dependencies.goal_id, goal_dependencies.dependency_goal_id FROM goal_dependencies
JOIN project_goals ON project_goals.id = goal_dependencies.goal_id
WHERE project_goals.project_name = ?
ORDER BY goal_dependencies.goal_id, goal_dependencies.dependency_goal_id
`

func (q *Queries) ListGoalDependencies(ctx context.Context, projectName string) ([]GoalDependency, error) {
	rows, err := q.db.QueryContext(ctx, listGoalDependencies, projectName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GoalDependency
	for rows.Next() {
		var i GoalDependency
		if err := rows.Scan(&i.GoalID, &i.DependencyGoalID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoalStatusHistory = `-- name: ListGoalStatusHistory :many
SELECT id, goal_id, from_status, to_status, reason, source_type, source_id, session_id, created_at FROM goal_status_history WHERE goal_id = ? ORDER BY created_at, id
`

func (q *Queries) ListGoalStatusHistory(ctx context.Context, goalID string) ([]GoalStatusHistory, error) {
	rows, err := q.db.QueryContext(ctx, listGoalStatusHistory, goalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GoalStatusHistory
	for rows.Next() {
		var i GoalStatusHistory
		if err := rows.Scan(
			&i.ID,
			&i.GoalID,
			&i.FromStatus,
			&i.ToStatus,
			&i.Reason,
			&i.SourceType,
			&i.SourceID,
			&i.SessionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectActors = `-- name: ListProjectActors :many
SELECT id, project_name, description, spec_hash, active, updated_at FROM project_actors
WHERE project_name = ? AND active = 1 ORDER BY id
`

func (q *Queries) ListProjectActors(ctx context.Context, projectName string) ([]ProjectActor, error) {
	rows, err := q.db.QueryContext(ctx, listProjectActors, projectName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectActor
	for rows.Next() {
		var i ProjectActor
		if err := rows.Scan(
			&i.ID,
			&i.ProjectName,
			&i.Description,
			&i.SpecHash,
			&i.Active,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectCapabilities = `-- name: ListProjectCapabilities :many
SELECT id, project_name, description, spec_hash, active, updated_at FROM project_capabilities
WHERE project_name = ? AND active = 1 ORDER BY id
`

func (q *Queries) ListProjectCapabilities(ctx context.Context, projectName string) ([]ProjectCapability, error) {
	rows, err := q.db.QueryContext(ctx, listProjectCapabilities, projectName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectCapability
	for rows.Next() {
		var i ProjectCapability
		if err := rows.Scan(
			&i.ID,
			&i.ProjectName,
			&i.Description,
			&i.SpecHash,
			&i.Active,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectGoals = `-- name: ListProjectGoals :many
SELECT id, project_name, description, priority, status, status_reason, spec_hash, active, created_at, updated_at FROM project_goals
WHERE project_name = ? AND active = 1
ORDER BY CASE priority WHEN 'required' THEN 0 ELSE 1 END, id
`

func (q *Queries) ListProjectGoals(ctx context.Context, projectName string) ([]ProjectGoal, error) {
	rows, err := q.db.QueryContext(ctx, listProjectGoals, projectName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectGoal
	for rows.Next() {
		var i ProjectGoal
		if err := rows.Scan(
			&i.ID,
			&i.ProjectName,
			&i.Description,
			&i.Priority,
			&i.Status,
			&i.StatusReason,
			&i.SpecHash,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectNonGoals = `-- name: ListProjectNonGoals :many
SELECT id, project_name, description, spec_hash, active, updated_at FROM project_non_goals
WHERE project_name = ? AND active = 1 ORDER BY id
`

func (q *Queries) ListProjectNonGoals(ctx context.Context, projectName string) ([]ProjectNonGoal, error) {
	rows, err := q.db.QueryContext(ctx, listProjectNonGoals, projectName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectNonGoal
	for rows.Next() {
		var i ProjectNonGoal
		if err := rows.Scan(
			&i.ID,
			&i.ProjectName,
			&i.Description,
			&i.SpecHash,
			&i.Active,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectRequiredGoals = `-- name: ListProjectRequiredGoals :many
SELECT project_name, goal_id, ordinal FROM project_required_goals WHERE project_name = ? ORDER BY ordinal, goal_id
`

func (q *Queries) ListProjectRequiredGoals(ctx context.Context, projectName string) ([]ProjectRequiredGoal, error) {
	rows, err := q.db.QueryContext(ctx, listProjectRequiredGoals, projectName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectRequiredGoal
	for rows.Next() {
		var i ProjectRequiredGoal
		if err := rows.Scan(&i.ProjectName, &i.GoalID, &i.Ordinal); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectRequirements = `-- name: ListProjectRequirements :many
SELECT id, project_name, kind, description, spec_hash, active, updated_at FROM project_requirements
WHERE project_name = ? AND active = 1 ORDER BY kind, id
`

func (q *Queries) ListProjectRequirements(ctx context.Context, projectName string) ([]ProjectRequirement, error) {
	rows, err := q.db.QueryContext(ctx, listProjectRequirements, projectName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectRequirement
	for rows.Next() {
		var i ProjectRequirement
		if err := rows.Scan(
			&i.ID,
			&i.ProjectName,
			&i.Kind,
			&i.Description,
			&i.SpecHash,
			&i.Active,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectStatusHistory = `-- name: ListProjectStatusHistory :many
SELECT id, project_name, from_status, to_status, reason, source_type, source_id, session_id, created_at FROM project_status_history WHERE project_name = ? ORDER BY created_at, id
`

func (q *Queries) ListProjectStatusHistory(ctx context.Context, projectName string) ([]ProjectStatusHistory, error) {
	rows, err := q.db.QueryContext(ctx, listProjectStatusHistory, projectName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectStatusHistory
	for rows.Next() {
		var i ProjectStatusHistory
		if err := rows.Scan(
			&i.ID,
			&i.ProjectName,
			&i.FromStatus,
			&i.ToStatus,
			&i.Reason,
			&i.SourceType,
			&i.SourceID,
			&i.SessionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequirementCapabilities = `-- name: ListRequirementCapabilities :many
SELECT requirement_capabilities.requirement_id, requirement_capabilities.capability_id FROM requirement_capabilities
JOIN project_requirements ON project_requirements.id = requirement_capabilities.requirement_id
WHERE project_requirements.project_name = ?
ORDER BY requirement_capabilities.requirement_id, requirement_capabilities.capability_id
`

func (q *Queries) ListRequirementCapabilities(ctx context.Context, projectName string) ([]RequirementCapability, error) {
	rows, err := q.db.QueryContext(ctx, listRequirementCapabilities, projectName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RequirementCapability
	for rows.Next() {
		var i RequirementCapability
		if err := rows.Scan(&i.RequirementID, &i.CapabilityID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequirementGoals = `-- name: ListRequirementGoals :many
SELECT requirement_goals.requirement_id, requirement_goals.goal_id FROM requirement_goals
JOIN project_requirements ON project_requirements.id = requirement_goals.requirement_id
WHERE project_requirements.project_name = ?
ORDER BY requirement_goals.requirement_id, requirement_goals.goal_id
`

func (q *Queries) ListRequirementGoals(ctx context.Context, projectName string) ([]RequirementGoal, error) {
	rows, err := q.db.QueryContext(ctx, listRequirementGoals, projectName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RequirementGoal
	for rows.Next() {
		var i RequirementGoal
		if err := rows.Scan(&i.RequirementID, &i.GoalID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProjectCompletionStatus = `-- name: UpdateProjectCompletionStatus :exec
UPDATE project_state
SET completion_status = ?, completion_reason = ?, updated_at = ?
WHERE project_name = ? AND active = 1
`

type UpdateProjectCompletionStatusParams struct {
	CompletionStatus string
	CompletionReason string
	UpdatedAt        string
	ProjectName      string
}

func (q *Queries) UpdateProjectCompletionStatus(ctx context.Context, arg UpdateProjectCompletionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateProjectCompletionStatus,
		arg.CompletionStatus,
		arg.CompletionReason,
		arg.UpdatedAt,
		arg.ProjectName,
	)
	return err
}

const updateProjectGoalStatus = `-- name: UpdateProjectGoalStatus :exec
UPDATE project_goals
SET status = ?, status_reason = ?, updated_at = ?
WHERE id = ? AND active = 1
`

type UpdateProjectGoalStatusParams struct {
	Status       string
	StatusReason string
	UpdatedAt    string
	ID           string
}

func (q *Queries) UpdateProjectGoalStatus(ctx context.Context, arg UpdateProjectGoalStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateProjectGoalStatus,
		arg.Status,
		arg.StatusReason,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const upsertAcceptanceScenario = `-- name: UpsertAcceptanceScenario :exec
INSERT INTO acceptance_scenarios (
    id, capability_id, actor_id, description, ordinal, spec_hash, active, updated_at
) VALUES (?, ?, ?, ?, ?, ?, 1, ?)
ON CONFLICT(id) DO UPDATE SET
    capability_id = excluded.capability_id,
    actor_id = excluded.actor_id,
    description = excluded.description,
    ordinal = excluded.ordinal,
    spec_hash = excluded.spec_hash,
    active = 1,
    updated_at = excluded.updated_at
`

type UpsertAcceptanceScenarioParams struct {
	ID           string
	CapabilityID string
	ActorID      *string
	Description  string
	Ordinal      int64
	SpecHash     string
	UpdatedAt    string
}

func (q *Queries) UpsertAcceptanceScenario(ctx context.Context, arg UpsertAcceptanceScenarioParams) error {
	_, err := q.db.ExecContext(ctx, upsertAcceptanceScenario,
		arg.ID,
		arg.CapabilityID,
		arg.ActorID,
		arg.Description,
		arg.Ordinal,
		arg.SpecHash,
		arg.UpdatedAt,
	)
	return err
}

const upsertEvidenceRequirement = `-- name: UpsertEvidenceRequirement :exec
INSERT INTO evidence_requirements (id, project_name, kind, description, spec_hash, active, updated_at)
VALUES (?, ?, ?, ?, ?, 1, ?)
ON CONFLICT(id) DO UPDATE SET
    project_name = excluded.project_name,
    kind = excluded.kind,
    description = excluded.description,
    spec_hash = excluded.spec_hash,
    active = 1,
    updated_at = excluded.updated_at
`

type UpsertEvidenceRequirementParams struct {
	ID          string
	ProjectName string
	Kind        string
	Description string
	SpecHash    string
	UpdatedAt   string
}

func (q *Queries) UpsertEvidenceRequirement(ctx context.Context, arg UpsertEvidenceRequirementParams) error {
	_, err := q.db.ExecContext(ctx, upsertEvidenceRequirement,
		arg.ID,
		arg.ProjectName,
		arg.Kind,
		arg.Description,
		arg.SpecHash,
		arg.UpdatedAt,
	)
	return err
}

const upsertProjectActor = `-- name: UpsertProjectActor :exec
INSERT INTO project_actors (id, project_name, description, spec_hash, active, updated_at)
VALUES (?, ?, ?, ?, 1, ?)
ON CONFLICT(id) DO UPDATE SET
    project_name = excluded.project_name,
    description = excluded.description,
    spec_hash = excluded.spec_hash,
    active = 1,
    updated_at = excluded.updated_at
`

type UpsertProjectActorParams struct {
	ID          string
	ProjectName string
	Description string
	SpecHash    string
	UpdatedAt   string
}

func (q *Queries) UpsertProjectActor(ctx context.Context, arg UpsertProjectActorParams) error {
	_, err := q.db.ExecContext(ctx, upsertProjectActor,
		arg.ID,
		arg.ProjectName,
		arg.Description,
		arg.SpecHash,
		arg.UpdatedAt,
	)
	return err
}

const upsertProjectCapability = `-- name: UpsertProjectCapability :exec
INSERT INTO project_capabilities (id, project_name, description, spec_hash, active, updated_at)
VALUES (?, ?, ?, ?, 1, ?)
ON CONFLICT(id) DO UPDATE SET
    project_name = excluded.project_name,
    description = excluded.description,
    spec_hash = excluded.spec_hash,
    active = 1,
    updated_at = excluded.updated_at
`

type UpsertProjectCapabilityParams struct {
	ID          string
	ProjectName string
	Description string
	SpecHash    string
	UpdatedAt   string
}

func (q *Queries) UpsertProjectCapability(ctx context.Context, arg UpsertProjectCapabilityParams) error {
	_, err := q.db.ExecContext(ctx, upsertProjectCapability,
		arg.ID,
		arg.ProjectName,
		arg.Description,
		arg.SpecHash,
		arg.UpdatedAt,
	)
	return err
}

const upsertProjectGoal = `-- name: UpsertProjectGoal :exec
INSERT INTO project_goals (
    id, project_name, description, priority, status, status_reason,
    spec_hash, active, created_at, updated_at
) VALUES (?, ?, ?, ?, 'declared',
    'goal is declared but no active implementation plan targets it',
    ?, 1, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    project_name = excluded.project_name,
    description = excluded.description,
    priority = excluded.priority,
    spec_hash = excluded.spec_hash,
    active = 1,
    updated_at = excluded.updated_at
`

type UpsertProjectGoalParams struct {
	ID          string
	ProjectName string
	Description string
	Priority    string
	SpecHash    string
	CreatedAt   string
	UpdatedAt   string
}

func (q *Queries) UpsertProjectGoal(ctx context.Context, arg UpsertProjectGoalParams) error {
	_, err := q.db.ExecContext(ctx, upsertProjectGoal,
		arg.ID,
		arg.ProjectName,
		arg.Description,
		arg.Priority,
		arg.SpecHash,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertProjectNonGoal = `-- name: UpsertProjectNonGoal :exec
INSERT INTO project_non_goals (id, project_name, description, spec_hash, active, updated_at)
VALUES (?, ?, ?, ?, 1, ?)
ON CONFLICT(id) DO UPDATE SET
    project_name = excluded.project_name,
    description = excluded.description,
    spec_hash = excluded.spec_hash,
    active = 1,
    updated_at = excluded.updated_at
`

type UpsertProjectNonGoalParams struct {
	ID          string
	ProjectName string
	Description string
	SpecHash    string
	UpdatedAt   string
}

func (q *Queries) UpsertProjectNonGoal(ctx context.Context, arg UpsertProjectNonGoalParams) error {
	_, err := q.db.ExecContext(ctx, upsertProjectNonGoal,
		arg.ID,
		arg.ProjectName,
		arg.Description,
		arg.SpecHash,
		arg.UpdatedAt,
	)
	return err
}

const upsertProjectRequirement = `-- name: UpsertProjectRequirement :exec
INSERT INTO project_requirements (id, project_name, kind, description, spec_hash, active, updated_at)
VALUES (?, ?, ?, ?, ?, 1, ?)
ON CONFLICT(id) DO UPDATE SET
    project_name = excluded.project_name,
    kind = excluded.kind,
    description = excluded.description,
    spec_hash = excluded.spec_hash,
    active = 1,
    updated_at = excluded.updated_at
`

type UpsertProjectRequirementParams struct {
	ID          string
	ProjectName string
	Kind        string
	Description string
	SpecHash    string
	UpdatedAt   string
}

func (q *Queries) UpsertProjectRequirement(ctx context.Context, arg UpsertProjectRequirementParams) error {
	_, err := q.db.ExecContext(ctx, upsertProjectRequirement,
		arg.ID,
		arg.ProjectName,
		arg.Kind,
		arg.Description,
		arg.SpecHash,
		arg.UpdatedAt,
	)
	return err
}

const upsertProjectState = `-- name: UpsertProjectState :exec
INSERT INTO project_state (
    project_name, mission, spec_hash, completion_status, active, created_at, updated_at
) VALUES (?, ?, ?, 'declared', 1, ?, ?)
ON CONFLICT(project_name) DO UPDATE SET
    mission = excluded.mission,
    spec_hash = excluded.spec_hash,
    active = 1,
    updated_at = excluded.updated_at
`

type UpsertProjectStateParams struct {
	ProjectName string
	Mission     string
	SpecHash    string
	CreatedAt   string
	UpdatedAt   string
}

func (q *Queries) UpsertProjectState(ctx context.Context, arg UpsertProjectStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertProjectState,
		arg.ProjectName,
		arg.Mission,
		arg.SpecHash,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
