// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invariant_checks.sql

package db

import (
	"context"
)

const createInvariantCheck = `-- name: CreateInvariantCheck :exec
INSERT INTO invariant_checks (id, apply_id, resource_id, invariant, passed, details, checked_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateInvariantCheckParams struct {
	ID         string
	ApplyID    string
	ResourceID string
	Invariant  string
	Passed     int64
	Details    *string
	CheckedAt  string
}

func (q *Queries) CreateInvariantCheck(ctx context.Context, arg CreateInvariantCheckParams) error {
	_, err := q.db.ExecContext(ctx, createInvariantCheck,
		arg.ID,
		arg.ApplyID,
		arg.ResourceID,
		arg.Invariant,
		arg.Passed,
		arg.Details,
		arg.CheckedAt,
	)
	return err
}

const listInvariantChecks = `-- name: ListInvariantChecks :many
SELECT id, apply_id, resource_id, invariant, passed, details, checked_at FROM invariant_checks WHERE apply_id = ? ORDER BY checked_at
`

func (q *Queries) ListInvariantChecks(ctx context.Context, applyID string) ([]InvariantCheck, error) {
	rows, err := q.db.QueryContext(ctx, listInvariantChecks, applyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InvariantCheck
	for rows.Next() {
		var i InvariantCheck
		if err := rows.Scan(
			&i.ID,
			&i.ApplyID,
			&i.ResourceID,
			&i.Invariant,
			&i.Passed,
			&i.Details,
			&i.CheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvariantChecksByResource = `-- name: ListInvariantChecksByResource :many
SELECT id, apply_id, resource_id, invariant, passed, details, checked_at FROM invariant_checks WHERE apply_id = ? AND resource_id = ? ORDER BY checked_at
`

type ListInvariantChecksByResourceParams struct {
	ApplyID    string
	ResourceID string
}

func (q *Queries) ListInvariantChecksByResource(ctx context.Context, arg ListInvariantChecksByResourceParams) ([]InvariantCheck, error) {
	rows, err := q.db.QueryContext(ctx, listInvariantChecksByResource, arg.ApplyID, arg.ResourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InvariantCheck
	for rows.Next() {
		var i InvariantCheck
		if err := rows.Scan(
			&i.ID,
			&i.ApplyID,
			&i.ResourceID,
			&i.Invariant,
			&i.Passed,
			&i.Details,
			&i.CheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
