// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package db

import (
	"context"
	"database/sql"
)

const cancelJob = `-- name: CancelJob :execresult
UPDATE jobs SET status = 'cancelled', done_at = ?
WHERE id = ? AND status = 'running'
`

type CancelJobParams struct {
	DoneAt *string
	ID     string
}

func (q *Queries) CancelJob(ctx context.Context, arg CancelJobParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, cancelJob, arg.DoneAt, arg.ID)
}

const completeJob = `-- name: CompleteJob :execresult
UPDATE jobs SET status = 'completed', result = ?, done_at = ?
WHERE id = ? AND status = 'running'
`

type CompleteJobParams struct {
	Result *string
	DoneAt *string
	ID     string
}

func (q *Queries) CompleteJob(ctx context.Context, arg CompleteJobParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, completeJob, arg.Result, arg.DoneAt, arg.ID)
}

const createJob = `-- name: CreateJob :exec
INSERT INTO jobs (id, tool, status, pid, started_at)
VALUES (?, ?, 'running', ?, ?)
`

type CreateJobParams struct {
	ID        string
	Tool      string
	Pid       int64
	StartedAt string
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) error {
	_, err := q.db.ExecContext(ctx, createJob,
		arg.ID,
		arg.Tool,
		arg.Pid,
		arg.StartedAt,
	)
	return err
}

const deleteJob = `-- name: DeleteJob :exec
UPDATE jobs SET status = 'deleted', done_at = ?
WHERE id = ?
`

type DeleteJobParams struct {
	DoneAt *string
	ID     string
}

func (q *Queries) DeleteJob(ctx context.Context, arg DeleteJobParams) error {
	_, err := q.db.ExecContext(ctx, deleteJob, arg.DoneAt, arg.ID)
	return err
}

const failJob = `-- name: FailJob :execresult
UPDATE jobs SET status = 'failed', error = ?, done_at = ?
WHERE id = ? AND status = 'running'
`

type FailJobParams struct {
	Error  *string
	DoneAt *string
	ID     string
}

func (q *Queries) FailJob(ctx context.Context, arg FailJobParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, failJob, arg.Error, arg.DoneAt, arg.ID)
}

const getJob = `-- name: GetJob :one
SELECT id, tool, status, result, error, pid, started_at, done_at, progress_json FROM jobs WHERE id = ?
`

func (q *Queries) GetJob(ctx context.Context, id string) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Tool,
		&i.Status,
		&i.Result,
		&i.Error,
		&i.Pid,
		&i.StartedAt,
		&i.DoneAt,
		&i.ProgressJson,
	)
	return i, err
}

const listJobs = `-- name: ListJobs :many
SELECT id, tool, status, result, error, pid, started_at, done_at, progress_json FROM jobs
WHERE status != 'deleted'
ORDER BY started_at DESC
LIMIT ?
`

func (q *Queries) ListJobs(ctx context.Context, limit int64) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Tool,
			&i.Status,
			&i.Result,
			&i.Error,
			&i.Pid,
			&i.StartedAt,
			&i.DoneAt,
			&i.ProgressJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunningJobs = `-- name: ListRunningJobs :many
SELECT id, tool, status, result, error, pid, started_at, done_at, progress_json FROM jobs WHERE status = 'running'
`

func (q *Queries) ListRunningJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listRunningJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Tool,
			&i.Status,
			&i.Result,
			&i.Error,
			&i.Pid,
			&i.StartedAt,
			&i.DoneAt,
			&i.ProgressJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobProgress = `-- name: UpdateJobProgress :exec
UPDATE jobs SET progress_json = ?
WHERE id = ? AND status = 'running'
`

type UpdateJobProgressParams struct {
	ProgressJson *string
	ID           string
}

func (q *Queries) UpdateJobProgress(ctx context.Context, arg UpdateJobProgressParams) error {
	_, err := q.db.ExecContext(ctx, updateJobProgress, arg.ProgressJson, arg.ID)
	return err
}
