// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: learnings.sql

package db

import (
	"context"
)

const createLearning = `-- name: CreateLearning :exec
INSERT INTO learnings (id, scope_lang, scope_kind, text, rationale, source_generation_id, source_apply_id, confidence, status, times_applied, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateLearningParams struct {
	ID                 string
	ScopeLang          string
	ScopeKind          string
	Text               string
	Rationale          string
	SourceGenerationID *string
	SourceApplyID      *string
	Confidence         float64
	Status             string
	TimesApplied       int64
	CreatedAt          string
	UpdatedAt          string
}

func (q *Queries) CreateLearning(ctx context.Context, arg CreateLearningParams) error {
	_, err := q.db.ExecContext(ctx, createLearning,
		arg.ID,
		arg.ScopeLang,
		arg.ScopeKind,
		arg.Text,
		arg.Rationale,
		arg.SourceGenerationID,
		arg.SourceApplyID,
		arg.Confidence,
		arg.Status,
		arg.TimesApplied,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const incrementLearningApplied = `-- name: IncrementLearningApplied :exec
UPDATE learnings SET times_applied = times_applied + 1, updated_at = ? WHERE id = ?
`

type IncrementLearningAppliedParams struct {
	UpdatedAt string
	ID        string
}

func (q *Queries) IncrementLearningApplied(ctx context.Context, arg IncrementLearningAppliedParams) error {
	_, err := q.db.ExecContext(ctx, incrementLearningApplied, arg.UpdatedAt, arg.ID)
	return err
}

const listActiveLearnings = `-- name: ListActiveLearnings :many
SELECT id, scope_lang, scope_kind, text, rationale, source_generation_id, source_apply_id, confidence, status, times_applied, created_at, updated_at FROM learnings
WHERE status = 'active'
  AND (scope_lang = '' OR scope_lang = ?)
  AND (scope_kind = '' OR scope_kind = ?)
ORDER BY confidence DESC, created_at DESC
LIMIT ?
`

type ListActiveLearningsParams struct {
	ScopeLang string
	ScopeKind string
	Limit     int64
}

func (q *Queries) ListActiveLearnings(ctx context.Context, arg ListActiveLearningsParams) ([]Learning, error) {
	rows, err := q.db.QueryContext(ctx, listActiveLearnings, arg.ScopeLang, arg.ScopeKind, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Learning
	for rows.Next() {
		var i Learning
		if err := rows.Scan(
			&i.ID,
			&i.ScopeLang,
			&i.ScopeKind,
			&i.Text,
			&i.Rationale,
			&i.SourceGenerationID,
			&i.SourceApplyID,
			&i.Confidence,
			&i.Status,
			&i.TimesApplied,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLearningsByStatus = `-- name: ListLearningsByStatus :many
SELECT id, scope_lang, scope_kind, text, rationale, source_generation_id, source_apply_id, confidence, status, times_applied, created_at, updated_at FROM learnings
WHERE status = ?
ORDER BY confidence DESC, created_at DESC
`

func (q *Queries) ListLearningsByStatus(ctx context.Context, status string) ([]Learning, error) {
	rows, err := q.db.QueryContext(ctx, listLearningsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Learning
	for rows.Next() {
		var i Learning
		if err := rows.Scan(
			&i.ID,
			&i.ScopeLang,
			&i.ScopeKind,
			&i.Text,
			&i.Rationale,
			&i.SourceGenerationID,
			&i.SourceApplyID,
			&i.Confidence,
			&i.Status,
			&i.TimesApplied,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLearningStatus = `-- name: UpdateLearningStatus :exec
UPDATE learnings SET status = ?, updated_at = ? WHERE id = ?
`

type UpdateLearningStatusParams struct {
	Status    string
	UpdatedAt string
	ID        string
}

func (q *Queries) UpdateLearningStatus(ctx context.Context, arg UpdateLearningStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateLearningStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}
