// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lock.sql

package db

import (
	"context"
)

const deleteLock = `-- name: DeleteLock :exec
DELETE FROM lock WHERE id = 1
`

func (q *Queries) DeleteLock(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteLock)
	return err
}

const getLock = `-- name: GetLock :one
SELECT id, holder, pid, acquired_at FROM lock WHERE id = 1
`

func (q *Queries) GetLock(ctx context.Context) (Lock, error) {
	row := q.db.QueryRowContext(ctx, getLock)
	var i Lock
	err := row.Scan(
		&i.ID,
		&i.Holder,
		&i.Pid,
		&i.AcquiredAt,
	)
	return i, err
}

const insertLock = `-- name: InsertLock :exec
INSERT INTO lock (id, holder, pid, acquired_at)
VALUES (1, ?, ?, ?)
`

type InsertLockParams struct {
	Holder     string
	Pid        int64
	AcquiredAt string
}

func (q *Queries) InsertLock(ctx context.Context, arg InsertLockParams) error {
	_, err := q.db.ExecContext(ctx, insertLock, arg.Holder, arg.Pid, arg.AcquiredAt)
	return err
}
