// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type AgentNote struct {
	ResourceID string
	ApplyID    string
	Content    string
	CreatedAt  string
}

type AgentSession struct {
	ID          string
	PlanJson    string
	WavesJson   string
	HashesJson  string
	CurrentWave int64
	Status      string
	CreatedAt   string
	UpdatedAt   string
	ApplyID     string
}

type Apply struct {
	ID        string
	Status    string
	SpecHash  string
	StartedAt string
	DoneAt    *string
}

type ApplyAction struct {
	ID         string
	ApplyID    string
	ResourceID string
	Action     string
	Outcome    *string
	Error      *string
	StartedAt  string
	DoneAt     *string
}

type Dependency struct {
	SourceID string
	TargetID string
	Kind     string
}

type GeneratedFile struct {
	Path        string
	ResourceID  string
	ContentHash string
	PromptHash  string
	Model       string
	CreatedAt   string
}

type Generation struct {
	ID              string
	ApplyID         *string
	ResourceID      string
	PromptText      string
	PromptHash      string
	OutputText      *string
	Model           string
	Outcome         *string
	RejectionReason *string
	RetryCount      int64
	DurationMs      *int64
	InputTokens     *int64
	OutputTokens    *int64
	CostUsd         *float64
	CreatedAt       string
}

type InvariantCheck struct {
	ID         string
	ApplyID    string
	ResourceID string
	Invariant  string
	Passed     int64
	Details    *string
	CheckedAt  string
}

type Job struct {
	ID        string
	Tool      string
	Status    string
	Result    *string
	Error     *string
	Pid       int64
	StartedAt string
	DoneAt    *string
}

type Lock struct {
	ID         int64
	Holder     string
	Pid        int64
	AcquiredAt string
}

type Resource struct {
	ID              string
	Kind            string
	ContextName     *string
	DeclarationHash string
	EffectiveHash   string
	Model           *string
	SettledAt       string
}

type SessionResource struct {
	SessionID  string
	ResourceID string
	State      string
	WaveIndex  int64
	Attempts   int64
	MaxRetries int64
	LastError  *string
	LastOutput *string
	JobID      *string
	UpdatedAt  string
}
