// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type AcceptanceEvidence struct {
	ScenarioID string
	EvidenceID string
}

type AcceptanceScenario struct {
	ID           string
	CapabilityID string
	ActorID      *string
	Description  string
	Ordinal      int64
	SpecHash     string
	Active       int64
	UpdatedAt    string
}

type AcceptanceStep struct {
	ScenarioID string
	Ordinal    int64
	Action     string
	Observes   string
}

type AgentEvent struct {
	ID           string
	GenerationID *string
	ResourceID   string
	ApplyID      *string
	EventType    string
	Attempt      *int64
	Content      *string
	CreatedAt    string
}

type AgentNote struct {
	ResourceID string
	ApplyID    string
	Content    string
	CreatedAt  string
}

type AgentSession struct {
	ID          string
	PlanJson    string
	WavesJson   string
	HashesJson  string
	CurrentWave int64
	Status      string
	CreatedAt   string
	UpdatedAt   string
	ApplyID     string
}

type Amendment struct {
	ID              string
	ResourceID      string
	Name            string
	ContentHash     string
	Origin          string
	Prompt          string
	FindingJson     string
	ValidationJson  string
	State           string
	AppliedSpecHash string
	CreatedAt       string
	AppliedAt       string
	GraduatedAt     string
}

type Apply struct {
	ID        string
	Status    string
	SpecHash  string
	StartedAt string
	DoneAt    *string
}

type ApplyAction struct {
	ID         string
	ApplyID    string
	ResourceID string
	Action     string
	Outcome    *string
	Error      *string
	StartedAt  string
	DoneAt     *string
}

type AttemptHandoff struct {
	ID              string
	SourceAttemptID string
	TargetAttemptID *string
	SourceRole      string
	TargetRole      string
	Reason          string
	ExpectedOutcome string
	FailureID       *string
	Status          string
	CreatedAt       string
	AcceptedAt      *string
}

type CandidateFile struct {
	ID          string
	CandidateID string
	Path        string
	ContentBlob string
	ContentHash string
	ByteSize    int64
	WriteIntent string
	Ordinal     int64
}

type CandidateFileAcceptance struct {
	CandidateFileID string
	ResourceID      string
	Path            string
	AcceptedAt      string
}

type CandidateSet struct {
	ID                string
	ExecutionID       string
	AttemptID         string
	CandidateHash     string
	Status            string
	DispositionReason string
	CreatedAt         string
	DisposedAt        *string
}

type CapabilityGoal struct {
	CapabilityID string
	GoalID       string
}

type Check struct {
	ID         string
	TaskID     string
	ResourceID string
	Behavior   string
	CheckJson  string
	State      string
	CreatedAt  string
	UpdatedAt  string
}

type CompletionBlocker struct {
	ID          string
	ProjectName string
	GoalID      *string
	Category    string
	Reason      string
	SourceType  string
	SourceID    string
	Resolved    int64
	Resolution  string
	CreatedAt   string
	ResolvedAt  *string
}

type ContentBlob struct {
	Hash      string
	Content   []byte
	ByteSize  int64
	CreatedAt string
}

type ContextManifest struct {
	ID                 string
	AttemptID          string
	SelectorVersion    string
	EstimatorVersion   string
	SelectionStrategy  string
	BudgetTokens       int64
	EstimatedTokens    int64
	OriginalBytes      int64
	SelectedBytes      int64
	TemplateHashesJson string
	SystemPromptBlob   string
	RenderedPromptBlob string
	ContextHash        string
	Blocked            int64
	BlockedReason      string
	CreatedAt          string
}

type ContextSection struct {
	ID              string
	ManifestID      string
	Ordinal         int64
	SectionKind     string
	Title           string
	SourceKind      string
	SourceID        string
	SourcePath      string
	Priority        int64
	Mandatory       int64
	Decision        string
	Reason          string
	OriginalHash    string
	ContentBlob     *string
	OriginalBytes   int64
	SelectedBytes   int64
	EstimatedTokens int64
}

type Dependency struct {
	SourceID string
	TargetID string
	Kind     string
}

type Design struct {
	ContextName  string
	SpecHash     string
	ContractJson string
	CreatedAt    string
	UpdatedAt    string
}

type EvidenceRequirement struct {
	ID          string
	ProjectName string
	Kind        string
	Description string
	SpecHash    string
	Active      int64
	UpdatedAt   string
}

type ExecutionEvent struct {
	ID          string
	ExecutionID string
	FromStatus  string
	ToStatus    string
	EventKind   string
	DetailsJson string
	DetailsHash string
	CreatedAt   string
}

type ExecutionManifest struct {
	ID                     string
	AttemptID              string
	ContextManifestID      string
	ProtocolVersion        string
	IdempotencyKey         string
	PlanOperationID        string
	Role                   string
	RolePolicyVersion      string
	ContextPolicy          string
	HostName               string
	HostVersion            string
	Provider               string
	Model                  string
	InferenceConfigJson    string
	InferenceConfigHash    string
	AgentConfigJson        string
	AgentConfigHash        string
	ToolPermissionsJson    string
	ToolPermissionsHash    string
	TemplateHashesJson     string
	TemplateHashesHash     string
	SystemInstructionsBlob string
	ContextHash            string
	HostSessionID          string
	Status                 string
	DispositionReason      string
	StartedAt              string
	CompletedAt            *string
	DurationMs             int64
	InputTokens            int64
	OutputTokens           int64
	CostUsd                float64
	CreatedAt              string
	UpdatedAt              string
}

type ExecutionTool struct {
	ExecutionID string
	Name        string
	Permission  string
	Ordinal     int64
}

type FailureClassification struct {
	ID                string
	AttemptID         string
	ExecutionID       *string
	ResourceID        string
	Category          string
	Origin            string
	Confidence        float64
	EvidenceSource    string
	EvidenceReference string
	EvidenceBlob      *string
	CorrectiveAction  string
	NextRole          string
	BlocksRetry       int64
	OverrideOf        *string
	Resolution        string
	ResolvedByAttempt *string
	CreatedAt         string
	ResolvedAt        *string
}

type FailureGoal struct {
	FailureID string
	GoalID    string
}

type GeneratedFile struct {
	Path        string
	ResourceID  string
	ContentHash string
	PromptHash  string
	Model       string
	CreatedAt   string
}

type Generation struct {
	ID              string
	ApplyID         *string
	ResourceID      string
	PromptText      string
	PromptHash      string
	OutputText      *string
	Model           string
	Outcome         *string
	RejectionReason *string
	RetryCount      int64
	DurationMs      *int64
	InputTokens     *int64
	OutputTokens    *int64
	CostUsd         *float64
	CreatedAt       string
	ExecutionID     *string
}

type GenerationAttempt struct {
	ID                string
	SessionID         string
	ApplyID           string
	ResourceID        string
	PlanOperationID   string
	ParentAttemptID   *string
	RetryNumber       int64
	Role              string
	Status            string
	CreatedAt         string
	RolePolicyVersion string
}

type GoalActor struct {
	GoalID  string
	ActorID string
}

type GoalDependency struct {
	GoalID           string
	DependencyGoalID string
}

type GoalStatusHistory struct {
	ID         string
	GoalID     string
	FromStatus string
	ToStatus   string
	Reason     string
	SourceType string
	SourceID   string
	SessionID  *string
	CreatedAt  string
}

type InvariantCheck struct {
	ID         string
	ApplyID    string
	ResourceID string
	Invariant  string
	Passed     int64
	Details    *string
	CheckedAt  string
}

type Job struct {
	ID           string
	Tool         string
	Status       string
	Result       *string
	Error        *string
	Pid          int64
	StartedAt    string
	DoneAt       *string
	ProgressJson *string
}

type Learning struct {
	ID                 string
	ScopeLang          string
	ScopeKind          string
	Text               string
	Rationale          string
	SourceGenerationID *string
	SourceApplyID      *string
	Confidence         float64
	Status             string
	TimesApplied       int64
	CreatedAt          string
	UpdatedAt          string
}

type Lock struct {
	ID         int64
	Holder     string
	Pid        int64
	AcquiredAt string
}

type ProjectActor struct {
	ID          string
	ProjectName string
	Description string
	SpecHash    string
	Active      int64
	UpdatedAt   string
}

type ProjectCapability struct {
	ID          string
	ProjectName string
	Description string
	SpecHash    string
	Active      int64
	UpdatedAt   string
}

type ProjectGoal struct {
	ID           string
	ProjectName  string
	Description  string
	Priority     string
	Status       string
	StatusReason string
	SpecHash     string
	Active       int64
	CreatedAt    string
	UpdatedAt    string
}

type ProjectNonGoal struct {
	ID          string
	ProjectName string
	Description string
	SpecHash    string
	Active      int64
	UpdatedAt   string
}

type ProjectRequiredGoal struct {
	ProjectName string
	GoalID      string
	Ordinal     int64
}

type ProjectRequirement struct {
	ID          string
	ProjectName string
	Kind        string
	Description string
	SpecHash    string
	Active      int64
	UpdatedAt   string
}

type ProjectState struct {
	ProjectName      string
	Mission          string
	SpecHash         string
	CompletionStatus string
	Active           int64
	CreatedAt        string
	UpdatedAt        string
	CompletionReason string
}

type ProjectStatusHistory struct {
	ID          string
	ProjectName string
	FromStatus  string
	ToStatus    string
	Reason      string
	SourceType  string
	SourceID    string
	SessionID   *string
	CreatedAt   string
}

type RequirementCapability struct {
	RequirementID string
	CapabilityID  string
}

type RequirementGoal struct {
	RequirementID string
	GoalID        string
}

type Resource struct {
	ID              string
	Kind            string
	ContextName     *string
	DeclarationHash string
	EffectiveHash   string
	Model           *string
	SettledAt       string
}

type ResourceAssetProfile struct {
	ResourceID     string
	ProjectName    string
	ProfileKind    string
	Ecosystem      string
	Witness        string
	Source         string
	SecretPolicy   string
	FailurePolicy  string
	ConstraintText string
	Audience       string
	Predecessor    string
	Compatibility  string
	Rollback       string
	SpecHash       string
	Active         int64
	UpdatedAt      string
}

type ResourceAssetProfileItem struct {
	ResourceID string
	ItemKind   string
	Ordinal    int64
	Value      string
}

type ResourceBoundaryProfile struct {
	ResourceID   string
	ProjectName  string
	ResourceKind string
	Direction    string
	ProfileKind  string
	Method       string
	Path         string
	Protocol     string
	Topology     string
	Device       string
	Medium       string
	SystemName   string
	Topic        string
	TriggerName  string
	SpecHash     string
	Active       int64
	UpdatedAt    string
}

type ResourceBoundaryProfileItem struct {
	ResourceID string
	ItemKind   string
	Ordinal    int64
	Value      string
}

type ResourceCapabilityContribution struct {
	ProjectName  string
	ResourceID   string
	ResourceKind string
	CapabilityID string
	Contribution string
	SpecHash     string
	Active       int64
	UpdatedAt    string
}

type SessionResource struct {
	SessionID    string
	ResourceID   string
	State        string
	WaveIndex    int64
	Attempts     int64
	MaxRetries   int64
	LastError    *string
	LastOutput   *string
	JobID        *string
	UpdatedAt    string
	Phase        string
	DispatchedAt string
}

type Task struct {
	ID          string
	ResourceID  string
	ContextName string
	SpecHash    string
	Description string
	State       string
	CreatedAt   string
	UpdatedAt   string
}

type Verification struct {
	ID          string
	CheckID     string
	ResourceID  string
	RealObsJson string
	StubObsJson string
	Passed      int64
	Theater     int64
	Reason      string
	CreatedAt   string
}
