// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resources.sql

package db

import (
	"context"
)

const deleteDependencies = `-- name: DeleteDependencies :exec
DELETE FROM dependencies WHERE source_id = ?
`

func (q *Queries) DeleteDependencies(ctx context.Context, sourceID string) error {
	_, err := q.db.ExecContext(ctx, deleteDependencies, sourceID)
	return err
}

const deleteGeneratedFiles = `-- name: DeleteGeneratedFiles :exec
DELETE FROM generated_files WHERE resource_id = ?
`

func (q *Queries) DeleteGeneratedFiles(ctx context.Context, resourceID string) error {
	_, err := q.db.ExecContext(ctx, deleteGeneratedFiles, resourceID)
	return err
}

const deleteResource = `-- name: DeleteResource :exec
DELETE FROM resources WHERE id = ?
`

func (q *Queries) DeleteResource(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteResource, id)
	return err
}

const getDependencies = `-- name: GetDependencies :many
SELECT source_id, target_id, kind FROM dependencies WHERE source_id = ?
`

func (q *Queries) GetDependencies(ctx context.Context, sourceID string) ([]Dependency, error) {
	rows, err := q.db.QueryContext(ctx, getDependencies, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Dependency
	for rows.Next() {
		var i Dependency
		if err := rows.Scan(&i.SourceID, &i.TargetID, &i.Kind); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGeneratedFiles = `-- name: GetGeneratedFiles :many
SELECT path, resource_id, content_hash, prompt_hash, model, created_at FROM generated_files WHERE resource_id = ?
`

// Generated files
func (q *Queries) GetGeneratedFiles(ctx context.Context, resourceID string) ([]GeneratedFile, error) {
	rows, err := q.db.QueryContext(ctx, getGeneratedFiles, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GeneratedFile
	for rows.Next() {
		var i GeneratedFile
		if err := rows.Scan(
			&i.Path,
			&i.ResourceID,
			&i.ContentHash,
			&i.PromptHash,
			&i.Model,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResource = `-- name: GetResource :one
SELECT id, kind, context_name, declaration_hash, effective_hash, model, settled_at FROM resources WHERE id = ?
`

// Resource state
func (q *Queries) GetResource(ctx context.Context, id string) (Resource, error) {
	row := q.db.QueryRowContext(ctx, getResource, id)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ContextName,
		&i.DeclarationHash,
		&i.EffectiveHash,
		&i.Model,
		&i.SettledAt,
	)
	return i, err
}

const listResources = `-- name: ListResources :many
SELECT id, kind, context_name, declaration_hash, effective_hash, model, settled_at FROM resources ORDER BY id
`

func (q *Queries) ListResources(ctx context.Context) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Resource
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.ContextName,
			&i.DeclarationHash,
			&i.EffectiveHash,
			&i.Model,
			&i.SettledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDependency = `-- name: SetDependency :exec
INSERT INTO dependencies (source_id, target_id, kind)
VALUES (?, ?, ?)
ON CONFLICT(source_id, target_id, kind) DO NOTHING
`

type SetDependencyParams struct {
	SourceID string
	TargetID string
	Kind     string
}

// Dependencies
func (q *Queries) SetDependency(ctx context.Context, arg SetDependencyParams) error {
	_, err := q.db.ExecContext(ctx, setDependency, arg.SourceID, arg.TargetID, arg.Kind)
	return err
}

const setGeneratedFile = `-- name: SetGeneratedFile :exec
INSERT INTO generated_files (path, resource_id, content_hash, prompt_hash, model, created_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(path) DO UPDATE SET
    resource_id = excluded.resource_id,
    content_hash = excluded.content_hash,
    prompt_hash = excluded.prompt_hash,
    model = excluded.model,
    created_at = excluded.created_at
`

type SetGeneratedFileParams struct {
	Path        string
	ResourceID  string
	ContentHash string
	PromptHash  string
	Model       string
	CreatedAt   string
}

func (q *Queries) SetGeneratedFile(ctx context.Context, arg SetGeneratedFileParams) error {
	_, err := q.db.ExecContext(ctx, setGeneratedFile,
		arg.Path,
		arg.ResourceID,
		arg.ContentHash,
		arg.PromptHash,
		arg.Model,
		arg.CreatedAt,
	)
	return err
}

const setResource = `-- name: SetResource :exec
INSERT INTO resources (id, kind, context_name, declaration_hash, effective_hash, model, settled_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    kind = excluded.kind,
    context_name = excluded.context_name,
    declaration_hash = excluded.declaration_hash,
    effective_hash = excluded.effective_hash,
    model = excluded.model,
    settled_at = excluded.settled_at
`

type SetResourceParams struct {
	ID              string
	Kind            string
	ContextName     *string
	DeclarationHash string
	EffectiveHash   string
	Model           *string
	SettledAt       string
}

func (q *Queries) SetResource(ctx context.Context, arg SetResourceParams) error {
	_, err := q.db.ExecContext(ctx, setResource,
		arg.ID,
		arg.Kind,
		arg.ContextName,
		arg.DeclarationHash,
		arg.EffectiveHash,
		arg.Model,
		arg.SettledAt,
	)
	return err
}
