// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session_resources.sql

package db

import (
	"context"
)

const deleteSessionResources = `-- name: DeleteSessionResources :exec
DELETE FROM session_resources WHERE session_id = ?
`

func (q *Queries) DeleteSessionResources(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionResources, sessionID)
	return err
}

const getSessionResource = `-- name: GetSessionResource :one
SELECT session_id, resource_id, state, wave_index, attempts, max_retries, last_error, last_output, job_id, updated_at FROM session_resources WHERE session_id = ? AND resource_id = ?
`

type GetSessionResourceParams struct {
	SessionID  string
	ResourceID string
}

func (q *Queries) GetSessionResource(ctx context.Context, arg GetSessionResourceParams) (SessionResource, error) {
	row := q.db.QueryRowContext(ctx, getSessionResource, arg.SessionID, arg.ResourceID)
	var i SessionResource
	err := row.Scan(
		&i.SessionID,
		&i.ResourceID,
		&i.State,
		&i.WaveIndex,
		&i.Attempts,
		&i.MaxRetries,
		&i.LastError,
		&i.LastOutput,
		&i.JobID,
		&i.UpdatedAt,
	)
	return i, err
}

const listSessionResources = `-- name: ListSessionResources :many
SELECT session_id, resource_id, state, wave_index, attempts, max_retries, last_error, last_output, job_id, updated_at FROM session_resources WHERE session_id = ? ORDER BY wave_index, resource_id
`

func (q *Queries) ListSessionResources(ctx context.Context, sessionID string) ([]SessionResource, error) {
	rows, err := q.db.QueryContext(ctx, listSessionResources, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionResource
	for rows.Next() {
		var i SessionResource
		if err := rows.Scan(
			&i.SessionID,
			&i.ResourceID,
			&i.State,
			&i.WaveIndex,
			&i.Attempts,
			&i.MaxRetries,
			&i.LastError,
			&i.LastOutput,
			&i.JobID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionResourcesByState = `-- name: ListSessionResourcesByState :many
SELECT session_id, resource_id, state, wave_index, attempts, max_retries, last_error, last_output, job_id, updated_at FROM session_resources WHERE session_id = ? AND state = ? ORDER BY wave_index, resource_id
`

type ListSessionResourcesByStateParams struct {
	SessionID string
	State     string
}

func (q *Queries) ListSessionResourcesByState(ctx context.Context, arg ListSessionResourcesByStateParams) ([]SessionResource, error) {
	rows, err := q.db.QueryContext(ctx, listSessionResourcesByState, arg.SessionID, arg.State)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionResource
	for rows.Next() {
		var i SessionResource
		if err := rows.Scan(
			&i.SessionID,
			&i.ResourceID,
			&i.State,
			&i.WaveIndex,
			&i.Attempts,
			&i.MaxRetries,
			&i.LastError,
			&i.LastOutput,
			&i.JobID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionResourcesByWave = `-- name: ListSessionResourcesByWave :many
SELECT session_id, resource_id, state, wave_index, attempts, max_retries, last_error, last_output, job_id, updated_at FROM session_resources WHERE session_id = ? AND wave_index = ? ORDER BY resource_id
`

type ListSessionResourcesByWaveParams struct {
	SessionID string
	WaveIndex int64
}

func (q *Queries) ListSessionResourcesByWave(ctx context.Context, arg ListSessionResourcesByWaveParams) ([]SessionResource, error) {
	rows, err := q.db.QueryContext(ctx, listSessionResourcesByWave, arg.SessionID, arg.WaveIndex)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionResource
	for rows.Next() {
		var i SessionResource
		if err := rows.Scan(
			&i.SessionID,
			&i.ResourceID,
			&i.State,
			&i.WaveIndex,
			&i.Attempts,
			&i.MaxRetries,
			&i.LastError,
			&i.LastOutput,
			&i.JobID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionResourceState = `-- name: UpdateSessionResourceState :exec
UPDATE session_resources SET state = ?, last_error = ?, last_output = ?, attempts = ?, job_id = ?, updated_at = ?
WHERE session_id = ? AND resource_id = ?
`

type UpdateSessionResourceStateParams struct {
	State      string
	LastError  *string
	LastOutput *string
	Attempts   int64
	JobID      *string
	UpdatedAt  string
	SessionID  string
	ResourceID string
}

func (q *Queries) UpdateSessionResourceState(ctx context.Context, arg UpdateSessionResourceStateParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionResourceState,
		arg.State,
		arg.LastError,
		arg.LastOutput,
		arg.Attempts,
		arg.JobID,
		arg.UpdatedAt,
		arg.SessionID,
		arg.ResourceID,
	)
	return err
}

const upsertSessionResource = `-- name: UpsertSessionResource :exec
INSERT INTO session_resources (session_id, resource_id, state, wave_index, attempts, max_retries, last_error, last_output, job_id, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(session_id, resource_id) DO UPDATE SET
    state = excluded.state,
    attempts = excluded.attempts,
    last_error = excluded.last_error,
    last_output = excluded.last_output,
    job_id = excluded.job_id,
    updated_at = excluded.updated_at
`

type UpsertSessionResourceParams struct {
	SessionID  string
	ResourceID string
	State      string
	WaveIndex  int64
	Attempts   int64
	MaxRetries int64
	LastError  *string
	LastOutput *string
	JobID      *string
	UpdatedAt  string
}

func (q *Queries) UpsertSessionResource(ctx context.Context, arg UpsertSessionResourceParams) error {
	_, err := q.db.ExecContext(ctx, upsertSessionResource,
		arg.SessionID,
		arg.ResourceID,
		arg.State,
		arg.WaveIndex,
		arg.Attempts,
		arg.MaxRetries,
		arg.LastError,
		arg.LastOutput,
		arg.JobID,
		arg.UpdatedAt,
	)
	return err
}
