// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
)

const createNote = `-- name: CreateNote :exec
INSERT INTO agent_notes (resource_id, apply_id, content, created_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(resource_id, apply_id) DO UPDATE SET content = excluded.content, created_at = excluded.created_at
`

type CreateNoteParams struct {
	ResourceID string
	ApplyID    string
	Content    string
	CreatedAt  string
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) error {
	_, err := q.db.ExecContext(ctx, createNote,
		arg.ResourceID,
		arg.ApplyID,
		arg.Content,
		arg.CreatedAt,
	)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO agent_sessions (id, plan_json, waves_json, hashes_json, status, created_at, updated_at)
VALUES (?, ?, ?, ?, 'active', ?, ?)
`

type CreateSessionParams struct {
	ID         string
	PlanJson   string
	WavesJson  string
	HashesJson string
	CreatedAt  string
	UpdatedAt  string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.PlanJson,
		arg.WavesJson,
		arg.HashesJson,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getActiveSession = `-- name: GetActiveSession :one
SELECT id, plan_json, waves_json, hashes_json, current_wave, status, created_at, updated_at FROM agent_sessions WHERE status = 'active' LIMIT 1
`

func (q *Queries) GetActiveSession(ctx context.Context) (AgentSession, error) {
	row := q.db.QueryRowContext(ctx, getActiveSession)
	var i AgentSession
	err := row.Scan(
		&i.ID,
		&i.PlanJson,
		&i.WavesJson,
		&i.HashesJson,
		&i.CurrentWave,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNote = `-- name: GetNote :one
SELECT resource_id, apply_id, content, created_at FROM agent_notes WHERE resource_id = ? AND apply_id = ?
`

type GetNoteParams struct {
	ResourceID string
	ApplyID    string
}

func (q *Queries) GetNote(ctx context.Context, arg GetNoteParams) (AgentNote, error) {
	row := q.db.QueryRowContext(ctx, getNote, arg.ResourceID, arg.ApplyID)
	var i AgentNote
	err := row.Scan(
		&i.ResourceID,
		&i.ApplyID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, plan_json, waves_json, hashes_json, current_wave, status, created_at, updated_at FROM agent_sessions WHERE id = ?
`

func (q *Queries) GetSession(ctx context.Context, id string) (AgentSession, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i AgentSession
	err := row.Scan(
		&i.ID,
		&i.PlanJson,
		&i.WavesJson,
		&i.HashesJson,
		&i.CurrentWave,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNotes = `-- name: ListNotes :many
SELECT resource_id, apply_id, content, created_at FROM agent_notes WHERE apply_id = ?
`

func (q *Queries) ListNotes(ctx context.Context, applyID string) ([]AgentNote, error) {
	rows, err := q.db.QueryContext(ctx, listNotes, applyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentNote
	for rows.Next() {
		var i AgentNote
		if err := rows.Scan(
			&i.ResourceID,
			&i.ApplyID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionStatus = `-- name: UpdateSessionStatus :exec
UPDATE agent_sessions SET status = ?, current_wave = ?, updated_at = ?
WHERE id = ?
`

type UpdateSessionStatusParams struct {
	Status      string
	CurrentWave int64
	UpdatedAt   string
	ID          string
}

func (q *Queries) UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionStatus,
		arg.Status,
		arg.CurrentWave,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
