// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: traceability.sql

package db

import (
	"context"
)

const clearAssetProfileItems = `-- name: ClearAssetProfileItems :exec
DELETE FROM resource_asset_profile_items WHERE resource_id IN (
    SELECT resource_id FROM resource_asset_profiles WHERE project_name = ?
)
`

func (q *Queries) ClearAssetProfileItems(ctx context.Context, projectName string) error {
	_, err := q.db.ExecContext(ctx, clearAssetProfileItems, projectName)
	return err
}

const clearBoundaryProfileItems = `-- name: ClearBoundaryProfileItems :exec
DELETE FROM resource_boundary_profile_items WHERE resource_id IN (
    SELECT resource_id FROM resource_boundary_profiles WHERE project_name = ?
)
`

func (q *Queries) ClearBoundaryProfileItems(ctx context.Context, projectName string) error {
	_, err := q.db.ExecContext(ctx, clearBoundaryProfileItems, projectName)
	return err
}

const deactivateAssetProfiles = `-- name: DeactivateAssetProfiles :exec
UPDATE resource_asset_profiles SET active = 0, updated_at = ? WHERE project_name = ?
`

type DeactivateAssetProfilesParams struct {
	UpdatedAt   string
	ProjectName string
}

func (q *Queries) DeactivateAssetProfiles(ctx context.Context, arg DeactivateAssetProfilesParams) error {
	_, err := q.db.ExecContext(ctx, deactivateAssetProfiles, arg.UpdatedAt, arg.ProjectName)
	return err
}

const deactivateBoundaryProfiles = `-- name: DeactivateBoundaryProfiles :exec
UPDATE resource_boundary_profiles SET active = 0, updated_at = ? WHERE project_name = ?
`

type DeactivateBoundaryProfilesParams struct {
	UpdatedAt   string
	ProjectName string
}

func (q *Queries) DeactivateBoundaryProfiles(ctx context.Context, arg DeactivateBoundaryProfilesParams) error {
	_, err := q.db.ExecContext(ctx, deactivateBoundaryProfiles, arg.UpdatedAt, arg.ProjectName)
	return err
}

const deactivateResourceContributions = `-- name: DeactivateResourceContributions :exec
UPDATE resource_capability_contributions SET active = 0, updated_at = ? WHERE project_name = ?
`

type DeactivateResourceContributionsParams struct {
	UpdatedAt   string
	ProjectName string
}

func (q *Queries) DeactivateResourceContributions(ctx context.Context, arg DeactivateResourceContributionsParams) error {
	_, err := q.db.ExecContext(ctx, deactivateResourceContributions, arg.UpdatedAt, arg.ProjectName)
	return err
}

const insertAssetProfileItem = `-- name: InsertAssetProfileItem :exec
INSERT INTO resource_asset_profile_items (resource_id, item_kind, ordinal, value) VALUES (?, ?, ?, ?)
`

type InsertAssetProfileItemParams struct {
	ResourceID string
	ItemKind   string
	Ordinal    int64
	Value      string
}

func (q *Queries) InsertAssetProfileItem(ctx context.Context, arg InsertAssetProfileItemParams) error {
	_, err := q.db.ExecContext(ctx, insertAssetProfileItem,
		arg.ResourceID,
		arg.ItemKind,
		arg.Ordinal,
		arg.Value,
	)
	return err
}

const insertBoundaryProfileItem = `-- name: InsertBoundaryProfileItem :exec
INSERT INTO resource_boundary_profile_items (resource_id, item_kind, ordinal, value) VALUES (?, ?, ?, ?)
`

type InsertBoundaryProfileItemParams struct {
	ResourceID string
	ItemKind   string
	Ordinal    int64
	Value      string
}

func (q *Queries) InsertBoundaryProfileItem(ctx context.Context, arg InsertBoundaryProfileItemParams) error {
	_, err := q.db.ExecContext(ctx, insertBoundaryProfileItem,
		arg.ResourceID,
		arg.ItemKind,
		arg.Ordinal,
		arg.Value,
	)
	return err
}

const listAssetProfileItems = `-- name: ListAssetProfileItems :many
SELECT resource_asset_profile_items.resource_id, resource_asset_profile_items.item_kind, resource_asset_profile_items.ordinal, resource_asset_profile_items.value FROM resource_asset_profile_items
JOIN resource_asset_profiles USING (resource_id)
WHERE resource_asset_profiles.project_name = ? AND resource_asset_profiles.active = 1
ORDER BY resource_asset_profile_items.resource_id, item_kind, ordinal
`

func (q *Queries) ListAssetProfileItems(ctx context.Context, projectName string) ([]ResourceAssetProfileItem, error) {
	rows, err := q.db.QueryContext(ctx, listAssetProfileItems, projectName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResourceAssetProfileItem
	for rows.Next() {
		var i ResourceAssetProfileItem
		if err := rows.Scan(
			&i.ResourceID,
			&i.ItemKind,
			&i.Ordinal,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetProfiles = `-- name: ListAssetProfiles :many
SELECT resource_id, project_name, profile_kind, ecosystem, witness, source, secret_policy, failure_policy, constraint_text, audience, predecessor, compatibility, "rollback", spec_hash, active, updated_at FROM resource_asset_profiles WHERE project_name = ? AND active = 1 ORDER BY resource_id
`

func (q *Queries) ListAssetProfiles(ctx context.Context, projectName string) ([]ResourceAssetProfile, error) {
	rows, err := q.db.QueryContext(ctx, listAssetProfiles, projectName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResourceAssetProfile
	for rows.Next() {
		var i ResourceAssetProfile
		if err := rows.Scan(
			&i.ResourceID,
			&i.ProjectName,
			&i.ProfileKind,
			&i.Ecosystem,
			&i.Witness,
			&i.Source,
			&i.SecretPolicy,
			&i.FailurePolicy,
			&i.ConstraintText,
			&i.Audience,
			&i.Predecessor,
			&i.Compatibility,
			&i.Rollback,
			&i.SpecHash,
			&i.Active,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBoundaryProfileItems = `-- name: ListBoundaryProfileItems :many
SELECT resource_boundary_profile_items.resource_id, resource_boundary_profile_items.item_kind, resource_boundary_profile_items.ordinal, resource_boundary_profile_items.value FROM resource_boundary_profile_items
JOIN resource_boundary_profiles USING (resource_id)
WHERE resource_boundary_profiles.project_name = ? AND resource_boundary_profiles.active = 1
ORDER BY resource_boundary_profile_items.resource_id, item_kind, ordinal
`

func (q *Queries) ListBoundaryProfileItems(ctx context.Context, projectName string) ([]ResourceBoundaryProfileItem, error) {
	rows, err := q.db.QueryContext(ctx, listBoundaryProfileItems, projectName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResourceBoundaryProfileItem
	for rows.Next() {
		var i ResourceBoundaryProfileItem
		if err := rows.Scan(
			&i.ResourceID,
			&i.ItemKind,
			&i.Ordinal,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBoundaryProfiles = `-- name: ListBoundaryProfiles :many
SELECT resource_id, project_name, resource_kind, direction, profile_kind, method, path, protocol, topology, device, medium, system_name, topic, trigger_name, spec_hash, active, updated_at FROM resource_boundary_profiles WHERE project_name = ? AND active = 1 ORDER BY resource_id
`

func (q *Queries) ListBoundaryProfiles(ctx context.Context, projectName string) ([]ResourceBoundaryProfile, error) {
	rows, err := q.db.QueryContext(ctx, listBoundaryProfiles, projectName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResourceBoundaryProfile
	for rows.Next() {
		var i ResourceBoundaryProfile
		if err := rows.Scan(
			&i.ResourceID,
			&i.ProjectName,
			&i.ResourceKind,
			&i.Direction,
			&i.ProfileKind,
			&i.Method,
			&i.Path,
			&i.Protocol,
			&i.Topology,
			&i.Device,
			&i.Medium,
			&i.SystemName,
			&i.Topic,
			&i.TriggerName,
			&i.SpecHash,
			&i.Active,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContributionsByCapability = `-- name: ListContributionsByCapability :many
SELECT project_name, resource_id, resource_kind, capability_id, contribution, spec_hash, active, updated_at FROM resource_capability_contributions
WHERE capability_id = ? AND active = 1 ORDER BY resource_id
`

func (q *Queries) ListContributionsByCapability(ctx context.Context, capabilityID string) ([]ResourceCapabilityContribution, error) {
	rows, err := q.db.QueryContext(ctx, listContributionsByCapability, capabilityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResourceCapabilityContribution
	for rows.Next() {
		var i ResourceCapabilityContribution
		if err := rows.Scan(
			&i.ProjectName,
			&i.ResourceID,
			&i.ResourceKind,
			&i.CapabilityID,
			&i.Contribution,
			&i.SpecHash,
			&i.Active,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContributionsByResource = `-- name: ListContributionsByResource :many
SELECT project_name, resource_id, resource_kind, capability_id, contribution, spec_hash, active, updated_at FROM resource_capability_contributions
WHERE resource_id = ? AND active = 1 ORDER BY capability_id
`

func (q *Queries) ListContributionsByResource(ctx context.Context, resourceID string) ([]ResourceCapabilityContribution, error) {
	rows, err := q.db.QueryContext(ctx, listContributionsByResource, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResourceCapabilityContribution
	for rows.Next() {
		var i ResourceCapabilityContribution
		if err := rows.Scan(
			&i.ProjectName,
			&i.ResourceID,
			&i.ResourceKind,
			&i.CapabilityID,
			&i.Contribution,
			&i.SpecHash,
			&i.Active,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourceContributions = `-- name: ListResourceContributions :many
SELECT project_name, resource_id, resource_kind, capability_id, contribution, spec_hash, active, updated_at FROM resource_capability_contributions
WHERE project_name = ? AND active = 1
ORDER BY capability_id, resource_id
`

func (q *Queries) ListResourceContributions(ctx context.Context, projectName string) ([]ResourceCapabilityContribution, error) {
	rows, err := q.db.QueryContext(ctx, listResourceContributions, projectName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResourceCapabilityContribution
	for rows.Next() {
		var i ResourceCapabilityContribution
		if err := rows.Scan(
			&i.ProjectName,
			&i.ResourceID,
			&i.ResourceKind,
			&i.CapabilityID,
			&i.Contribution,
			&i.SpecHash,
			&i.Active,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAssetProfile = `-- name: UpsertAssetProfile :exec
INSERT INTO resource_asset_profiles (
    resource_id, project_name, profile_kind, ecosystem, witness, source,
    secret_policy, failure_policy, constraint_text, audience, predecessor,
    compatibility, rollback, spec_hash, active, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1, ?)
ON CONFLICT(resource_id) DO UPDATE SET
    project_name = excluded.project_name,
    profile_kind = excluded.profile_kind,
    ecosystem = excluded.ecosystem,
    witness = excluded.witness,
    source = excluded.source,
    secret_policy = excluded.secret_policy,
    failure_policy = excluded.failure_policy,
    constraint_text = excluded.constraint_text,
    audience = excluded.audience,
    predecessor = excluded.predecessor,
    compatibility = excluded.compatibility,
    rollback = excluded.rollback,
    spec_hash = excluded.spec_hash,
    active = 1,
    updated_at = excluded.updated_at
`

type UpsertAssetProfileParams struct {
	ResourceID     string
	ProjectName    string
	ProfileKind    string
	Ecosystem      string
	Witness        string
	Source         string
	SecretPolicy   string
	FailurePolicy  string
	ConstraintText string
	Audience       string
	Predecessor    string
	Compatibility  string
	Rollback       string
	SpecHash       string
	UpdatedAt      string
}

func (q *Queries) UpsertAssetProfile(ctx context.Context, arg UpsertAssetProfileParams) error {
	_, err := q.db.ExecContext(ctx, upsertAssetProfile,
		arg.ResourceID,
		arg.ProjectName,
		arg.ProfileKind,
		arg.Ecosystem,
		arg.Witness,
		arg.Source,
		arg.SecretPolicy,
		arg.FailurePolicy,
		arg.ConstraintText,
		arg.Audience,
		arg.Predecessor,
		arg.Compatibility,
		arg.Rollback,
		arg.SpecHash,
		arg.UpdatedAt,
	)
	return err
}

const upsertBoundaryProfile = `-- name: UpsertBoundaryProfile :exec
INSERT INTO resource_boundary_profiles (
    resource_id, project_name, resource_kind, direction, profile_kind,
    method, path, protocol, topology, device, medium, system_name, topic,
    trigger_name, spec_hash, active, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1, ?)
ON CONFLICT(resource_id) DO UPDATE SET
    project_name = excluded.project_name,
    resource_kind = excluded.resource_kind,
    direction = excluded.direction,
    profile_kind = excluded.profile_kind,
    method = excluded.method,
    path = excluded.path,
    protocol = excluded.protocol,
    topology = excluded.topology,
    device = excluded.device,
    medium = excluded.medium,
    system_name = excluded.system_name,
    topic = excluded.topic,
    trigger_name = excluded.trigger_name,
    spec_hash = excluded.spec_hash,
    active = 1,
    updated_at = excluded.updated_at
`

type UpsertBoundaryProfileParams struct {
	ResourceID   string
	ProjectName  string
	ResourceKind string
	Direction    string
	ProfileKind  string
	Method       string
	Path         string
	Protocol     string
	Topology     string
	Device       string
	Medium       string
	SystemName   string
	Topic        string
	TriggerName  string
	SpecHash     string
	UpdatedAt    string
}

func (q *Queries) UpsertBoundaryProfile(ctx context.Context, arg UpsertBoundaryProfileParams) error {
	_, err := q.db.ExecContext(ctx, upsertBoundaryProfile,
		arg.ResourceID,
		arg.ProjectName,
		arg.ResourceKind,
		arg.Direction,
		arg.ProfileKind,
		arg.Method,
		arg.Path,
		arg.Protocol,
		arg.Topology,
		arg.Device,
		arg.Medium,
		arg.SystemName,
		arg.Topic,
		arg.TriggerName,
		arg.SpecHash,
		arg.UpdatedAt,
	)
	return err
}

const upsertResourceContribution = `-- name: UpsertResourceContribution :exec
INSERT INTO resource_capability_contributions (
    project_name, resource_id, resource_kind, capability_id,
    contribution, spec_hash, active, updated_at
) VALUES (?, ?, ?, ?, ?, ?, 1, ?)
ON CONFLICT(resource_id, capability_id) DO UPDATE SET
    project_name = excluded.project_name,
    resource_kind = excluded.resource_kind,
    contribution = excluded.contribution,
    spec_hash = excluded.spec_hash,
    active = 1,
    updated_at = excluded.updated_at
`

type UpsertResourceContributionParams struct {
	ProjectName  string
	ResourceID   string
	ResourceKind string
	CapabilityID string
	Contribution string
	SpecHash     string
	UpdatedAt    string
}

func (q *Queries) UpsertResourceContribution(ctx context.Context, arg UpsertResourceContributionParams) error {
	_, err := q.db.ExecContext(ctx, upsertResourceContribution,
		arg.ProjectName,
		arg.ResourceID,
		arg.ResourceKind,
		arg.CapabilityID,
		arg.Contribution,
		arg.SpecHash,
		arg.UpdatedAt,
	)
	return err
}
