// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: validation_evidence.sql

package db

import (
	"context"
)

const clearVerificationDefinitionTargets = `-- name: ClearVerificationDefinitionTargets :exec
DELETE FROM verification_definition_targets WHERE snapshot_id = ?
`

func (q *Queries) ClearVerificationDefinitionTargets(ctx context.Context, snapshotID string) error {
	_, err := q.db.ExecContext(ctx, clearVerificationDefinitionTargets, snapshotID)
	return err
}

const deactivateVerificationDefinitions = `-- name: DeactivateVerificationDefinitions :exec
UPDATE verification_definitions SET active = 0, updated_at = ? WHERE project_name = ?
`

type DeactivateVerificationDefinitionsParams struct {
	UpdatedAt   string
	ProjectName string
}

func (q *Queries) DeactivateVerificationDefinitions(ctx context.Context, arg DeactivateVerificationDefinitionsParams) error {
	_, err := q.db.ExecContext(ctx, deactivateVerificationDefinitions, arg.UpdatedAt, arg.ProjectName)
	return err
}

const getActiveVerificationDefinition = `-- name: GetActiveVerificationDefinition :one
SELECT snapshot_id, definition_id, project_name, definition_type, scope, kind, definition_hash, definition_json, spec_hash, active, created_at, updated_at FROM verification_definitions
WHERE project_name = ? AND definition_id = ? AND active = 1
`

type GetActiveVerificationDefinitionParams struct {
	ProjectName  string
	DefinitionID string
}

func (q *Queries) GetActiveVerificationDefinition(ctx context.Context, arg GetActiveVerificationDefinitionParams) (VerificationDefinition, error) {
	row := q.db.QueryRowContext(ctx, getActiveVerificationDefinition, arg.ProjectName, arg.DefinitionID)
	var i VerificationDefinition
	err := row.Scan(
		&i.SnapshotID,
		&i.DefinitionID,
		&i.ProjectName,
		&i.DefinitionType,
		&i.Scope,
		&i.Kind,
		&i.DefinitionHash,
		&i.DefinitionJson,
		&i.SpecHash,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getParsedObservation = `-- name: GetParsedObservation :one
SELECT execution_id, schema_json, schema_hash, observation_json, observation_hash, parse_error FROM parsed_observations WHERE execution_id = ?
`

func (q *Queries) GetParsedObservation(ctx context.Context, executionID string) (ParsedObservation, error) {
	row := q.db.QueryRowContext(ctx, getParsedObservation, executionID)
	var i ParsedObservation
	err := row.Scan(
		&i.ExecutionID,
		&i.SchemaJson,
		&i.SchemaHash,
		&i.ObservationJson,
		&i.ObservationHash,
		&i.ParseError,
	)
	return i, err
}

const getValidationRun = `-- name: GetValidationRun :one
SELECT id, definition_snapshot_id, definition_id, session_id, attempt_id, execution_id, source_tree_hash, classification, reason, started_at, completed_at, duration_ms, created_at FROM validation_runs WHERE id = ?
`

func (q *Queries) GetValidationRun(ctx context.Context, id string) (ValidationRun, error) {
	row := q.db.QueryRowContext(ctx, getValidationRun, id)
	var i ValidationRun
	err := row.Scan(
		&i.ID,
		&i.DefinitionSnapshotID,
		&i.DefinitionID,
		&i.SessionID,
		&i.AttemptID,
		&i.ExecutionID,
		&i.SourceTreeHash,
		&i.Classification,
		&i.Reason,
		&i.StartedAt,
		&i.CompletedAt,
		&i.DurationMs,
		&i.CreatedAt,
	)
	return i, err
}

const getVerificationDefinition = `-- name: GetVerificationDefinition :one
SELECT snapshot_id, definition_id, project_name, definition_type, scope, kind, definition_hash, definition_json, spec_hash, active, created_at, updated_at FROM verification_definitions WHERE snapshot_id = ?
`

func (q *Queries) GetVerificationDefinition(ctx context.Context, snapshotID string) (VerificationDefinition, error) {
	row := q.db.QueryRowContext(ctx, getVerificationDefinition, snapshotID)
	var i VerificationDefinition
	err := row.Scan(
		&i.SnapshotID,
		&i.DefinitionID,
		&i.ProjectName,
		&i.DefinitionType,
		&i.Scope,
		&i.Kind,
		&i.DefinitionHash,
		&i.DefinitionJson,
		&i.SpecHash,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertVerificationDefinitionTarget = `-- name: InsertVerificationDefinitionTarget :exec
INSERT INTO verification_definition_targets (snapshot_id, target_kind, target_id) VALUES (?, ?, ?)
`

type InsertVerificationDefinitionTargetParams struct {
	SnapshotID string
	TargetKind string
	TargetID   string
}

func (q *Queries) InsertVerificationDefinitionTarget(ctx context.Context, arg InsertVerificationDefinitionTargetParams) error {
	_, err := q.db.ExecContext(ctx, insertVerificationDefinitionTarget, arg.SnapshotID, arg.TargetKind, arg.TargetID)
	return err
}

const listActiveVerificationDefinitions = `-- name: ListActiveVerificationDefinitions :many
SELECT snapshot_id, definition_id, project_name, definition_type, scope, kind, definition_hash, definition_json, spec_hash, active, created_at, updated_at FROM verification_definitions
WHERE project_name = ? AND active = 1
ORDER BY definition_type, scope, definition_id
`

func (q *Queries) ListActiveVerificationDefinitions(ctx context.Context, projectName string) ([]VerificationDefinition, error) {
	rows, err := q.db.QueryContext(ctx, listActiveVerificationDefinitions, projectName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VerificationDefinition
	for rows.Next() {
		var i VerificationDefinition
		if err := rows.Scan(
			&i.SnapshotID,
			&i.DefinitionID,
			&i.ProjectName,
			&i.DefinitionType,
			&i.Scope,
			&i.Kind,
			&i.DefinitionHash,
			&i.DefinitionJson,
			&i.SpecHash,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentVerificationEvidence = `-- name: ListCurrentVerificationEvidence :many
SELECT id, run_id, evidence_id, source_tree_hash, definition_hash, classification, currency, created_at, invalidated_at FROM verification_evidence_records
WHERE evidence_id = ? AND currency = 'current'
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListCurrentVerificationEvidence(ctx context.Context, evidenceID string) ([]VerificationEvidenceRecord, error) {
	rows, err := q.db.QueryContext(ctx, listCurrentVerificationEvidence, evidenceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VerificationEvidenceRecord
	for rows.Next() {
		var i VerificationEvidenceRecord
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.EvidenceID,
			&i.SourceTreeHash,
			&i.DefinitionHash,
			&i.Classification,
			&i.Currency,
			&i.CreatedAt,
			&i.InvalidatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listValidationArtifactsByExecution = `-- name: ListValidationArtifactsByExecution :many
SELECT execution_id, path, content_blob, content_hash, byte_size, captured_bytes, truncated, missing FROM validation_artifacts WHERE execution_id = ? ORDER BY path
`

func (q *Queries) ListValidationArtifactsByExecution(ctx context.Context, executionID string) ([]ValidationArtifact, error) {
	rows, err := q.db.QueryContext(ctx, listValidationArtifactsByExecution, executionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ValidationArtifact
	for rows.Next() {
		var i ValidationArtifact
		if err := rows.Scan(
			&i.ExecutionID,
			&i.Path,
			&i.ContentBlob,
			&i.ContentHash,
			&i.ByteSize,
			&i.CapturedBytes,
			&i.Truncated,
			&i.Missing,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listValidationExecutionsByRun = `-- name: ListValidationExecutionsByRun :many
SELECT id, run_id, execution_role, command_json, command_hash, working_directory, environment_json, environment_hash, source_tree_hash, executable_hash, stdout_blob, stderr_blob, stdout_hash, stderr_hash, stdout_bytes, stderr_bytes, stdout_truncated, stderr_truncated, exit_code, timed_out, launch_error, started_at, completed_at, duration_ms FROM validation_executions WHERE run_id = ? ORDER BY execution_role
`

func (q *Queries) ListValidationExecutionsByRun(ctx context.Context, runID string) ([]ValidationExecution, error) {
	rows, err := q.db.QueryContext(ctx, listValidationExecutionsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ValidationExecution
	for rows.Next() {
		var i ValidationExecution
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.ExecutionRole,
			&i.CommandJson,
			&i.CommandHash,
			&i.WorkingDirectory,
			&i.EnvironmentJson,
			&i.EnvironmentHash,
			&i.SourceTreeHash,
			&i.ExecutableHash,
			&i.StdoutBlob,
			&i.StderrBlob,
			&i.StdoutHash,
			&i.StderrHash,
			&i.StdoutBytes,
			&i.StderrBytes,
			&i.StdoutTruncated,
			&i.StderrTruncated,
			&i.ExitCode,
			&i.TimedOut,
			&i.LaunchError,
			&i.StartedAt,
			&i.CompletedAt,
			&i.DurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listValidationPredicateResults = `-- name: ListValidationPredicateResults :many
SELECT run_id, execution_id, ordinal, field_name, operator, expected_json, observed_json, passed, reason FROM validation_predicate_results WHERE run_id = ? ORDER BY execution_id, ordinal
`

func (q *Queries) ListValidationPredicateResults(ctx context.Context, runID string) ([]ValidationPredicateResult, error) {
	rows, err := q.db.QueryContext(ctx, listValidationPredicateResults, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ValidationPredicateResult
	for rows.Next() {
		var i ValidationPredicateResult
		if err := rows.Scan(
			&i.RunID,
			&i.ExecutionID,
			&i.Ordinal,
			&i.FieldName,
			&i.Operator,
			&i.ExpectedJson,
			&i.ObservedJson,
			&i.Passed,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listValidationRunTargets = `-- name: ListValidationRunTargets :many
SELECT run_id, target_kind, target_id FROM validation_run_targets WHERE run_id = ? ORDER BY target_kind, target_id
`

func (q *Queries) ListValidationRunTargets(ctx context.Context, runID string) ([]ValidationRunTarget, error) {
	rows, err := q.db.QueryContext(ctx, listValidationRunTargets, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ValidationRunTarget
	for rows.Next() {
		var i ValidationRunTarget
		if err := rows.Scan(&i.RunID, &i.TargetKind, &i.TargetID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listValidationRuns = `-- name: ListValidationRuns :many
SELECT id, definition_snapshot_id, definition_id, session_id, attempt_id, execution_id, source_tree_hash, classification, reason, started_at, completed_at, duration_ms, created_at FROM validation_runs ORDER BY created_at DESC, id DESC LIMIT ?
`

func (q *Queries) ListValidationRuns(ctx context.Context, limit int64) ([]ValidationRun, error) {
	rows, err := q.db.QueryContext(ctx, listValidationRuns, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ValidationRun
	for rows.Next() {
		var i ValidationRun
		if err := rows.Scan(
			&i.ID,
			&i.DefinitionSnapshotID,
			&i.DefinitionID,
			&i.SessionID,
			&i.AttemptID,
			&i.ExecutionID,
			&i.SourceTreeHash,
			&i.Classification,
			&i.Reason,
			&i.StartedAt,
			&i.CompletedAt,
			&i.DurationMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listValidationRunsByDefinition = `-- name: ListValidationRunsByDefinition :many
SELECT id, definition_snapshot_id, definition_id, session_id, attempt_id, execution_id, source_tree_hash, classification, reason, started_at, completed_at, duration_ms, created_at FROM validation_runs WHERE definition_id = ? ORDER BY created_at DESC, id DESC LIMIT ?
`

type ListValidationRunsByDefinitionParams struct {
	DefinitionID string
	Limit        int64
}

func (q *Queries) ListValidationRunsByDefinition(ctx context.Context, arg ListValidationRunsByDefinitionParams) ([]ValidationRun, error) {
	rows, err := q.db.QueryContext(ctx, listValidationRunsByDefinition, arg.DefinitionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ValidationRun
	for rows.Next() {
		var i ValidationRun
		if err := rows.Scan(
			&i.ID,
			&i.DefinitionSnapshotID,
			&i.DefinitionID,
			&i.SessionID,
			&i.AttemptID,
			&i.ExecutionID,
			&i.SourceTreeHash,
			&i.Classification,
			&i.Reason,
			&i.StartedAt,
			&i.CompletedAt,
			&i.DurationMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerificationDefinitionTargets = `-- name: ListVerificationDefinitionTargets :many
SELECT snapshot_id, target_kind, target_id FROM verification_definition_targets
WHERE snapshot_id = ? ORDER BY target_kind, target_id
`

func (q *Queries) ListVerificationDefinitionTargets(ctx context.Context, snapshotID string) ([]VerificationDefinitionTarget, error) {
	rows, err := q.db.QueryContext(ctx, listVerificationDefinitionTargets, snapshotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VerificationDefinitionTarget
	for rows.Next() {
		var i VerificationDefinitionTarget
		if err := rows.Scan(&i.SnapshotID, &i.TargetKind, &i.TargetID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerificationEvidenceByRun = `-- name: ListVerificationEvidenceByRun :many
SELECT id, run_id, evidence_id, source_tree_hash, definition_hash, classification, currency, created_at, invalidated_at FROM verification_evidence_records WHERE run_id = ? ORDER BY evidence_id
`

func (q *Queries) ListVerificationEvidenceByRun(ctx context.Context, runID string) ([]VerificationEvidenceRecord, error) {
	rows, err := q.db.QueryContext(ctx, listVerificationEvidenceByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VerificationEvidenceRecord
	for rows.Next() {
		var i VerificationEvidenceRecord
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.EvidenceID,
			&i.SourceTreeHash,
			&i.DefinitionHash,
			&i.Classification,
			&i.Currency,
			&i.CreatedAt,
			&i.InvalidatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markVerificationEvidenceStale = `-- name: MarkVerificationEvidenceStale :many
UPDATE verification_evidence_records
SET currency = 'stale', invalidated_at = ?
WHERE evidence_id = ? AND currency = 'current'
RETURNING id, run_id, evidence_id, source_tree_hash, definition_hash, classification, currency, created_at, invalidated_at
`

type MarkVerificationEvidenceStaleParams struct {
	InvalidatedAt *string
	EvidenceID    string
}

func (q *Queries) MarkVerificationEvidenceStale(ctx context.Context, arg MarkVerificationEvidenceStaleParams) ([]VerificationEvidenceRecord, error) {
	rows, err := q.db.QueryContext(ctx, markVerificationEvidenceStale, arg.InvalidatedAt, arg.EvidenceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VerificationEvidenceRecord
	for rows.Next() {
		var i VerificationEvidenceRecord
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.EvidenceID,
			&i.SourceTreeHash,
			&i.DefinitionHash,
			&i.Classification,
			&i.Currency,
			&i.CreatedAt,
			&i.InvalidatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putParsedObservation = `-- name: PutParsedObservation :exec
INSERT INTO parsed_observations (
    execution_id, schema_json, schema_hash, observation_json,
    observation_hash, parse_error
) VALUES (?, ?, ?, ?, ?, ?)
`

type PutParsedObservationParams struct {
	ExecutionID     string
	SchemaJson      string
	SchemaHash      string
	ObservationJson string
	ObservationHash string
	ParseError      string
}

func (q *Queries) PutParsedObservation(ctx context.Context, arg PutParsedObservationParams) error {
	_, err := q.db.ExecContext(ctx, putParsedObservation,
		arg.ExecutionID,
		arg.SchemaJson,
		arg.SchemaHash,
		arg.ObservationJson,
		arg.ObservationHash,
		arg.ParseError,
	)
	return err
}

const putValidationArtifact = `-- name: PutValidationArtifact :exec
INSERT INTO validation_artifacts (
    execution_id, path, content_blob, content_hash, byte_size,
    captured_bytes, truncated, missing
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type PutValidationArtifactParams struct {
	ExecutionID   string
	Path          string
	ContentBlob   *string
	ContentHash   string
	ByteSize      int64
	CapturedBytes int64
	Truncated     int64
	Missing       int64
}

func (q *Queries) PutValidationArtifact(ctx context.Context, arg PutValidationArtifactParams) error {
	_, err := q.db.ExecContext(ctx, putValidationArtifact,
		arg.ExecutionID,
		arg.Path,
		arg.ContentBlob,
		arg.ContentHash,
		arg.ByteSize,
		arg.CapturedBytes,
		arg.Truncated,
		arg.Missing,
	)
	return err
}

const putValidationExecution = `-- name: PutValidationExecution :exec
INSERT INTO validation_executions (
    id, run_id, execution_role, command_json, command_hash,
    working_directory, environment_json, environment_hash, source_tree_hash,
    executable_hash, stdout_blob, stderr_blob, stdout_hash, stderr_hash,
    stdout_bytes, stderr_bytes, stdout_truncated, stderr_truncated,
    exit_code, timed_out, launch_error, started_at, completed_at, duration_ms
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type PutValidationExecutionParams struct {
	ID               string
	RunID            string
	ExecutionRole    string
	CommandJson      string
	CommandHash      string
	WorkingDirectory string
	EnvironmentJson  string
	EnvironmentHash  string
	SourceTreeHash   string
	ExecutableHash   string
	StdoutBlob       string
	StderrBlob       string
	StdoutHash       string
	StderrHash       string
	StdoutBytes      int64
	StderrBytes      int64
	StdoutTruncated  int64
	StderrTruncated  int64
	ExitCode         int64
	TimedOut         int64
	LaunchError      string
	StartedAt        string
	CompletedAt      string
	DurationMs       int64
}

func (q *Queries) PutValidationExecution(ctx context.Context, arg PutValidationExecutionParams) error {
	_, err := q.db.ExecContext(ctx, putValidationExecution,
		arg.ID,
		arg.RunID,
		arg.ExecutionRole,
		arg.CommandJson,
		arg.CommandHash,
		arg.WorkingDirectory,
		arg.EnvironmentJson,
		arg.EnvironmentHash,
		arg.SourceTreeHash,
		arg.ExecutableHash,
		arg.StdoutBlob,
		arg.StderrBlob,
		arg.StdoutHash,
		arg.StderrHash,
		arg.StdoutBytes,
		arg.StderrBytes,
		arg.StdoutTruncated,
		arg.StderrTruncated,
		arg.ExitCode,
		arg.TimedOut,
		arg.LaunchError,
		arg.StartedAt,
		arg.CompletedAt,
		arg.DurationMs,
	)
	return err
}

const putValidationPredicateResult = `-- name: PutValidationPredicateResult :exec
INSERT INTO validation_predicate_results (
    run_id, execution_id, ordinal, field_name, operator, expected_json,
    observed_json, passed, reason
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type PutValidationPredicateResultParams struct {
	RunID        string
	ExecutionID  string
	Ordinal      int64
	FieldName    string
	Operator     string
	ExpectedJson string
	ObservedJson string
	Passed       int64
	Reason       string
}

func (q *Queries) PutValidationPredicateResult(ctx context.Context, arg PutValidationPredicateResultParams) error {
	_, err := q.db.ExecContext(ctx, putValidationPredicateResult,
		arg.RunID,
		arg.ExecutionID,
		arg.Ordinal,
		arg.FieldName,
		arg.Operator,
		arg.ExpectedJson,
		arg.ObservedJson,
		arg.Passed,
		arg.Reason,
	)
	return err
}

const putValidationRun = `-- name: PutValidationRun :exec
INSERT INTO validation_runs (
    id, definition_snapshot_id, definition_id, session_id, attempt_id,
    execution_id, source_tree_hash, classification, reason, started_at,
    completed_at, duration_ms, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type PutValidationRunParams struct {
	ID                   string
	DefinitionSnapshotID string
	DefinitionID         string
	SessionID            *string
	AttemptID            *string
	ExecutionID          *string
	SourceTreeHash       string
	Classification       string
	Reason               string
	StartedAt            string
	CompletedAt          string
	DurationMs           int64
	CreatedAt            string
}

func (q *Queries) PutValidationRun(ctx context.Context, arg PutValidationRunParams) error {
	_, err := q.db.ExecContext(ctx, putValidationRun,
		arg.ID,
		arg.DefinitionSnapshotID,
		arg.DefinitionID,
		arg.SessionID,
		arg.AttemptID,
		arg.ExecutionID,
		arg.SourceTreeHash,
		arg.Classification,
		arg.Reason,
		arg.StartedAt,
		arg.CompletedAt,
		arg.DurationMs,
		arg.CreatedAt,
	)
	return err
}

const putValidationRunTarget = `-- name: PutValidationRunTarget :exec
INSERT INTO validation_run_targets (run_id, target_kind, target_id) VALUES (?, ?, ?)
`

type PutValidationRunTargetParams struct {
	RunID      string
	TargetKind string
	TargetID   string
}

func (q *Queries) PutValidationRunTarget(ctx context.Context, arg PutValidationRunTargetParams) error {
	_, err := q.db.ExecContext(ctx, putValidationRunTarget, arg.RunID, arg.TargetKind, arg.TargetID)
	return err
}

const putVerificationEvidenceInvalidation = `-- name: PutVerificationEvidenceInvalidation :exec
INSERT INTO verification_evidence_invalidations (
    id, evidence_record_id, reason, source_type, source_id, created_at
) VALUES (?, ?, ?, ?, ?, ?)
`

type PutVerificationEvidenceInvalidationParams struct {
	ID               string
	EvidenceRecordID string
	Reason           string
	SourceType       string
	SourceID         string
	CreatedAt        string
}

func (q *Queries) PutVerificationEvidenceInvalidation(ctx context.Context, arg PutVerificationEvidenceInvalidationParams) error {
	_, err := q.db.ExecContext(ctx, putVerificationEvidenceInvalidation,
		arg.ID,
		arg.EvidenceRecordID,
		arg.Reason,
		arg.SourceType,
		arg.SourceID,
		arg.CreatedAt,
	)
	return err
}

const putVerificationEvidenceRecord = `-- name: PutVerificationEvidenceRecord :exec
INSERT INTO verification_evidence_records (
    id, run_id, evidence_id, source_tree_hash, definition_hash,
    classification, currency, created_at
) VALUES (?, ?, ?, ?, ?, ?, 'current', ?)
`

type PutVerificationEvidenceRecordParams struct {
	ID             string
	RunID          string
	EvidenceID     string
	SourceTreeHash string
	DefinitionHash string
	Classification string
	CreatedAt      string
}

func (q *Queries) PutVerificationEvidenceRecord(ctx context.Context, arg PutVerificationEvidenceRecordParams) error {
	_, err := q.db.ExecContext(ctx, putVerificationEvidenceRecord,
		arg.ID,
		arg.RunID,
		arg.EvidenceID,
		arg.SourceTreeHash,
		arg.DefinitionHash,
		arg.Classification,
		arg.CreatedAt,
	)
	return err
}

const upsertVerificationDefinition = `-- name: UpsertVerificationDefinition :exec
INSERT INTO verification_definitions (
    snapshot_id, definition_id, project_name, definition_type, scope, kind,
    definition_hash, definition_json, spec_hash, active, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 1, ?, ?)
ON CONFLICT(snapshot_id) DO UPDATE SET
    active = 1,
    spec_hash = excluded.spec_hash,
    updated_at = excluded.updated_at
`

type UpsertVerificationDefinitionParams struct {
	SnapshotID     string
	DefinitionID   string
	ProjectName    string
	DefinitionType string
	Scope          string
	Kind           string
	DefinitionHash string
	DefinitionJson string
	SpecHash       string
	CreatedAt      string
	UpdatedAt      string
}

func (q *Queries) UpsertVerificationDefinition(ctx context.Context, arg UpsertVerificationDefinitionParams) error {
	_, err := q.db.ExecContext(ctx, upsertVerificationDefinition,
		arg.SnapshotID,
		arg.DefinitionID,
		arg.ProjectName,
		arg.DefinitionType,
		arg.Scope,
		arg.Kind,
		arg.DefinitionHash,
		arg.DefinitionJson,
		arg.SpecHash,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
